/*** = Синхронизировано со скриптом конвертации: не редактировать. */
/** D_AG — символы сновидений А-Г. */

export const D_AG = [
/** Сонник · символи сновидінь (повний словник, синхронізований з БД). */

  { id: "s0", icon: "🚌",
    name: { uk: "Автобус", ru: "Автобус", en: "Bus" },
    keywords: { uk: "рух, колектив, маршрут", ru: "движение, коллектив, маршрут", en: "movement, group, route" },
    text: { uk: "Автобус — дорога, якою ти їдеш не сам, а з іншими. Він показує твій маршрут у житті: чи зручно тобі в колективі, чи «не на своїй зупинці» ти виходиш. Якщо запізнюєшся — боїшся не встигнути за своїми планами.", ru: "Автобус — дорога, которой ты едешь не один, а с другими. Он показывает твой маршрут в жизни: комфортно ли тебе в коллективе, не на «чужой остановке» ли ты выходишь. Если опаздываешь — боишься не успеть за своими планами.", en: "A bus is a journey you take with others, not alone. It reflects your route in life: whether you are comfortable in a group or getting off at the wrong stop. Being late signals a fear of missing your plans." }, },
  { id: "s1", icon: "🚗",
    name: { uk: "Автомобіль", ru: "Автомобиль", en: "Car" },
    keywords: { uk: "шлях, контроль, рух, відповідальність", ru: "путь, контроль, движение, ответственность", en: "path, control, movement, responsibility" },
    text: { uk: "Автомобіль — твій шлях і спосіб ним керувати: ти сам за кермом свого життя. Несправна машина — знак, що час «сервісу»: подбати про себе.", ru: "Автомобиль — твой путь и способ им управлять: ты сам сидишь за рулём своей жизни. Неисправная машина — знак, что пора «сервис» — позаботиться о себе.", en: "A car is your path and how you steer it: you drive your own life. A broken car — a sign it is time for a 'service': take care of yourself." }, },
  { id: "s2", icon: "🛫",
    name: { uk: "Аеропорт", ru: "Аэропорт", en: "Airport" },
    keywords: { uk: "старт, зміни, очікування", ru: "старт, перемены, ожидание", en: "departure, change, waiting" },
    text: { uk: "Аеропорт — місце між «тут» і «там»: ти готовий до змін, але ще чекаєш свого часу. Сон каже: твій політ уже скоро, лишається зібратися в дорогу й не боятися нового.", ru: "Аэропорт — место между «здесь» и «там»: ты готов к переменам, но ещё ждёшь своего часа. Сон говорит: твой полёт уже скоро, остаётся собраться в дорогу и не бояться нового.", en: "An airport is the place between 'here' and 'there': you are ready for change but still waiting for your moment. The dream says your flight is coming soon — all that remains is to pack and not fear the new." }, },
  { id: "s3", icon: "🦈",
    name: { uk: "Акула", ru: "Акула", en: "Shark" },
    keywords: { uk: "сила, загроза, конкуренція", ru: "сила, угроза, конкуренция", en: "power, threat, competition" },
    text: { uk: "Акула — велика й сильна сила, яка може лякати: тиск, конкуренція або щось небезпечне, що насувається. Якщо ти не тікаєш і бачиш її здалеку — в тебе досить сміливості зустріти виклик.", ru: "Акула — большая и сильная сила, которая может пугать: давление, конкуренция или что-то опасное, что надвигается. Если ты не убегаешь и видишь её издалека — в тебе достаточно смелости встретить вызов.", en: "A shark is a large, powerful force that may frighten you: pressure, competition, or something threatening approaching. Watching it from a distance without fleeing means you have enough courage to meet the challenge." }, },
  { id: "s4", icon: "😇",
    name: { uk: "Ангел", ru: "Ангел", en: "Angel" },
    keywords: { uk: "захист, підтримка, надія", ru: "защита, поддержка, надежда", en: "protection, support, hope" },
    text: { uk: "Ангел уві сні — відчуття, що ти не сам: хтось або щось тебе береже. Це заклик довіритися, дозволити допомозі прийти і памʼятати: навіть у складний час ти під опікою.", ru: "Ангел во сне — ощущение, что ты не один: кто-то или что-то тебя бережёт. Это приглашение довериться, позволить помощи прийти и помнить: даже в трудное время ты под защитой.", en: "An angel is the feeling that you are not alone — someone or something is watching over you. It invites you to trust, allow help to arrive, and remember you are protected even in hard times." }, },
  { id: "s5", icon: "👵",
    name: { uk: "Бабуся", ru: "Бабушка", en: "Grandmother" },
    keywords: { uk: "мудрість, рід, підтримка", ru: "мудрость, род, поддержка", en: "wisdom, family, support" },
    text: { uk: "Бабуся — досвід і тепло попередніх поколінь. Вона зʼявляється, коли потрібна підтримка чи відповідь: поруч є сила, якою ти вже давно «успадковано» володієш.", ru: "Бабушка — опыт и тепло предыдущих поколений. Она появляется, когда нужна поддержка или ответ: рядом есть сила, которой ты уже давно «по наследству» владеешь.", en: "A grandmother is the wisdom and warmth of earlier generations. She appears when you need support or an answer: a strength you have long 'inherited' is close at hand." }, },
  { id: "s6", icon: "⚡",
    name: { uk: "Блискавка", ru: "Молния", en: "Lightning" },
    keywords: { uk: "осяяння, раптовість, зміна", ru: "озарение, внезапность, перемена", en: "insight, suddenness, change" },
    text: { uk: "Блискавка — раптове бачення: відповідь, що «вдарила» чітко й ясно. Вона лякає й водночас освітлює всю картину — сон про момент, який миттєво змінює погляд на речі.", ru: "Молния — внезапное прозрение: ответ, который «ударил» чётко и ясно. Она пугает и одновременно освещает всю картину — сон о моменте, который мгновенно меняет взгляд на вещи.", en: "Lightning is sudden insight: an answer that strikes sharp and clear. It frightens yet illuminates the whole scene — a dream about a moment that instantly changes how you see things." }, },
  { id: "s7", icon: "🤰",
    name: { uk: "Вагітність", ru: "Беременность", en: "Pregnancy" },
    keywords: { uk: "нове, дозрівання, очікування, потенціал", ru: "новое, созревание, ожидание, потенциал", en: "new, maturing, waiting, potential" },
    text: { uk: "Вагітність — дозрівання чогось нового: ідея, проєкт чи почуття зріють усередині й одного дня зʼявляться на світ. Час терпіння й турботи.", ru: "Беременность — созревание чего-то нового: идея, проект или чувство зреют внутри и однажды появятся на свет. Время набраться терпения и заботы.", en: "Pregnancy is the maturing of something new: an idea, a project or a feeling grows inside and one day comes to light. Time for patience and care." }, },
  { id: "s8", icon: "🐻",
    name: { uk: "Ведмідь", ru: "Медведь", en: "Bear" },
    keywords: { uk: "сила, захист, спокій, усамітнення", ru: "сила, защита, покой, уединение", en: "strength, protection, calm, solitude" },
    text: { uk: "Ведмідь — сила й опора: ти міцніший, ніж здається, і маєш право зайняти своє місце. Його сон — про те, щоб відстояти межі, піти в «берлогу» відновитись і прокинутися впевненішим.", ru: "Медведь — сила и опора: ты крепче, чем кажешься, и имеешь право занять своё место. Этот сон — про то, чтобы отстоять границы, уйти в «берлогу» восстановиться и проснуться увереннее.", en: "A bear is strength and grounding: you are stronger than you think and have the right to take your space. The dream is about defending your boundaries, retreating to your 'den' to recover, and waking more confident." }, },
  { id: "s9", icon: "🌿",
    name: { uk: "Верба", ru: "Верба", en: "Willow" },
    keywords: { uk: "гнучкість, весна, оновлення", ru: "гибкость, весна, обновление", en: "flexibility, spring, renewal" },
    text: { uk: "Верба — гнучкість, яка переживає будь-який вітер: нахилиться, але не зламається. Сон нагадує, що мʼякість — не слабкість, а вміння оновлюватися з настанням «весни» твого життя.", ru: "Верба — гибкость, которая переживает любой ветер: наклонится, но не сломается. Сон напоминает, что мягкость — не слабость, а умение обновляться с наступлением «весны» твоей жизни.", en: "A willow is flexibility that survives any wind: it bends yet never breaks. The dream reminds you that softness is not weakness, but the ability to renew when your life's 'spring' arrives." }, },
  { id: "s10", icon: "💒",
    name: { uk: "Весілля", ru: "Свадьба", en: "Wedding" },
    keywords: { uk: "союз, гармонія, любов, обʼєднання", ru: "союз, гармония, любовь, объединение", en: "union, harmony, love, joining" },
    text: { uk: "Весілля — союз і обʼєднання: усередині ти зʼєднуєш протилежні сторони або готовий до близького союзу. Символізує злиття, радість і новий етап.", ru: "Свадьба — союз и объединение: внутри себя ты соединяешь противоположные стороны или готов к близкому союзу. Это слияние, радость и новый этап.", en: "A wedding is union and joining: within yourself you connect opposing sides, or you are ready for a close bond. It is merging, joy and a new stage." }, },
  { id: "s11", icon: "🧙‍♀️",
    name: { uk: "Відьма", ru: "Ведьма", en: "Witch" },
    keywords: { uk: "інтуїція, тінь, жіноча сила", ru: "интуиция, тень, женская сила", en: "intuition, shadow, feminine power" },
    text: { uk: "Відьма — твоя інтуїція й ті сторони тебе, що «незручні» або приховані. Сон запрошує не лякатися власної сили: те, що ти вважаєш «чарами», часто — просто вміння бачити глибше.", ru: "Ведьма — твоя интуиция и те стороны тебя, которые «неудобны» или скрыты. Сон приглашает не бояться собственной силы: то, что ты считаешь «чарами», часто — просто умение видеть глубже.", en: "A witch is your intuition and the parts of yourself that feel 'inconvenient' or hidden. The dream invites you to stop fearing your own power: what seems like 'magic' is often just seeing deeper." }, },
  { id: "s12", icon: "🪟",
    name: { uk: "Вікно", ru: "Окно", en: "Window" },
    keywords: { uk: "погляд, можливість, межа", ru: "взгляд, возможность, граница", en: "view, opportunity, boundary" },
    text: { uk: "Вікно — погляд зі свого простору назовні: можливості, що чекають, або світ, на який ти дивишся, не виходячи з дому. Відчинене — запрошення стати ближче до того, що бачиш.", ru: "Окно — взгляд из своего пространства наружу: возможности, что ждут, или мир, на который ты смотришь, не выходя из дома. Открытое — приглашение стать ближе к тому, что видишь.", en: "A window is a view from your own space outward: opportunities waiting, or a world you watch without leaving home. An open window invites you closer to what you see." }, },
  { id: "s13", icon: "🐺",
    name: { uk: "Вовк", ru: "Волк", en: "Wolf" },
    keywords: { uk: "інстинкти, свобода, згуртованість", ru: "инстинкты, свобода, единство", en: "instinct, freedom, belonging" },
    text: { uk: "Вовк — дика, вільна частина тебе, що вміє бути сильною і водночас належати зграї. Сон закликає слухати інстинкти й не приручати себе заради чужих правил.", ru: "Волк — дикая, свободная часть тебя, что умеет быть сильной и при этом принадлежать стае. Сон зовёт слушать инстинкты и не приручать себя ради чужих правил.", en: "A wolf is the wild, free part of you that knows how to be strong and still belong. The dream calls you to trust your instincts and not tame yourself for others' rules." }, },
  { id: "s14", icon: "🔥",
    name: { uk: "Вогонь", ru: "Огонь", en: "Fire" },
    keywords: { uk: "енергія, пристрасть, очищення", ru: "энергия, страсть, очищение", en: "energy, passion, cleansing" },
    text: { uk: "Вогонь — сила, що зігріває або знищує, залежно від того, як із нею поводитися. Він про твою енергію: живить вона чи випалює? Вогонь очищає старе, аби звільнити місце новому.", ru: "Огонь — сила, что согревает или уничтожает, в зависимости от того, как с ним обращаться. Он о твоей энергии: питает она или выжигает? Огонь очищает старое, чтобы освободить место новому.", en: "Fire is a force that warms or destroys, depending on how you tend it. It is about your energy: does it nourish or burn? Fire clears the old to make room for the new." }, },
  { id: "s15", icon: "💧",
    name: { uk: "Вода", ru: "Вода", en: "Water" },
    keywords: { uk: "почуття, гнучкість, очищення", ru: "чувства, гибкость, очищение", en: "emotions, flexibility, cleansing" },
    text: { uk: "Вода — те, як ти проживаєш почуття. Чиста й спокійна — внутрішній світ у порядку, ти вільно «пливеш» життям. Каламутна чи бурхлива — емоції накопичились і просять уваги.", ru: "Вода — то, как ты переживаешь чувства. Чистая и спокойная — внутренний мир в порядке, ты свободно «плывёшь» по жизни. Мутная или бурная — эмоции накопились и просят внимания.", en: "Water is how you experience feelings. Calm and clear — your inner world is in order and you move through life freely. Murky or rough — emotions have piled up and ask for attention." }, },
  { id: "s16", icon: "🚉",
    name: { uk: "Вокзал", ru: "Вокзал", en: "Railway station" },
    keywords: { uk: "роздоріжжя, вибір, очікування", ru: "перепутье, выбор, ожидание", en: "crossroads, choice, waiting" },
    text: { uk: "Вокзал — місце, де сходяться всі дороги: ти стоїш перед вибором і думаєш, куди далі. Сон каже: тобі не обовʼязково сідати в перший потяг — є час обрати свій.", ru: "Вокзал — место, где сходятся все дороги: ты стоишь перед выбором и думаешь, куда дальше. Сон говорит: тебе не обязательно садиться в первый поезд — есть время выбрать свой.", en: "A station is where all roads meet: you stand at a choice, wondering where to go next. The dream says you do not have to board the first train — there is time to choose your own." }, },
  { id: "s17", icon: "⛩️",
    name: { uk: "Ворота", ru: "Ворота", en: "Gate" },
    keywords: { uk: "перехід, межа, запрошення", ru: "переход, граница, приглашение", en: "passage, boundary, invitation" },
    text: { uk: "Ворота — межа між звичним і новим. Відчинені — запрошують увійти в наступний етап; зачинені — підказують: поки не час, або ключ ще треба знайти.", ru: "Ворота — граница между привычным и новым. Открытые — приглашают войти в следующий этап; закрытые — подсказывают: пока не время, или ключ ещё нужно найти.", en: "A gate is the boundary between the familiar and the new. Open gates invite you to the next stage; closed ones suggest it is not time yet, or a key still needs to be found." }, },
  { id: "s18", icon: "🏃",
    name: { uk: "Втеча", ru: "Побег", en: "Escape" },
    keywords: { uk: "уникнення, пошук свободи, двері", ru: "избегание, поиск свободы, выход", en: "avoidance, search for freedom, exit" },
    text: { uk: "Втеча — потреба віддалитися: від тиску, очікувань чи від самого себе. Вона показує, що тобі важливо «вийти за двері» — щоправда, варто запитати: від чого саме ти втікаєш і куди хочеш прийти?", ru: "Побег — потребность отдалиться: от давления, ожиданий или от самого себя. Он показывает, что тебе важно «выйти за дверь» — правда, стоит спросить: от чего именно ты убегаешь и куда хочешь прийти?", en: "Escape is a need to get away: from pressure, expectations, or yourself. It shows a need to 'go out the door' — though it is worth asking what exactly you flee and where you want to arrive." }, },
  { id: "s19", icon: "🛤️",
    name: { uk: "Вулиця", ru: "Улица", en: "Street" },
    keywords: { uk: "напрям, рух, людей", ru: "направление, движение, люди", en: "direction, movement, people" },
    text: { uk: "Вулиця — загальний рух, у якому ти живеш щодня: робота, справи, люди поруч. Обрати напрям свій — це зробити вулицю не просто перехрестям чужих шляхів, а своїм маршрутом.", ru: "Улица — общее движение, в котором ты живёшь каждый день: работа, дела, люди рядом. Выбрать своё направление — это сделать улицу не просто перекрёстком чужих путей, а своим маршрутом.", en: "A street is the shared movement of daily life: work, errands, people around. Choosing your own direction turns the street from a crossroad of others' paths into your own route." }, },
  { id: "s20", icon: "🥗",
    name: { uk: "Гірчиця", ru: "Горчица", en: "Mustard" },
    keywords: { uk: "гострота, очищення, енергія", ru: "острота, очищение, энергия", en: "sharpness, cleansing, energy" },
    text: { uk: "Гірчиця — гостра добавка, що «вмикає» смак і бадьорість: іноді саме напруги чи пікантності бракує, щоб відчути себе жваво. Сон про те, що не все в житті має бути солодким і спокійним.", ru: "Горчица — острая добавка, что «включает» вкус и бодрость: иногда именно остроты или пикантности не хватает, чтобы почувствовать себя живо. Сон о том, что не всё в жизни должно быть сладким и спокойным.", en: "Mustard is a sharp addition that 'switches on' flavor and vigor: sometimes a little heat or piquancy is what you lack to feel alive. The dream notes that not everything needs to be sweet and serene." }, },
  { id: "s21", icon: "🧠",
    name: { uk: "Голова", ru: "Голова", en: "Head" },
    keywords: { uk: "думки, розум, тиск", ru: "мысли, разум, давление", en: "thoughts, mind, pressure" },
    text: { uk: "Голова — твої думки й внутрішній шум. Важка, болить чи «гуде» — надто багато обмірковуєш і мало відпочиваєш. Сон просить дати розуму паузу й не «крутити» одне й те саме.", ru: "Голова — твои мысли и внутренний шум. Тяжёлая, болит или «гудит» — слишком много обдумываешь и мало отдыхаешь. Сон просит дать разуму паузу и не «крутить» одно и то же.", en: "The head is your thoughts and inner noise. Heavy, aching, or buzzing means you overthink and under-rest. The dream asks you to give your mind a pause and stop replaying the same thing." }, },
  { id: "s22", icon: "⛰️",
    name: { uk: "Гора", ru: "Гора", en: "Mountain" },
    keywords: { uk: "ціль, виклик, висота", ru: "цель, вызов, высота", en: "goal, challenge, height" },
    text: { uk: "Гора — велика ціль і виклик: вона кличе вгору, а шлях на вершину — напруження заради важливого. Підйом означає, що ти зростаєш.", ru: "Гора — большая цель и вызов: она зовёт вверх, а путь на вершину — напряжение ради чего-то важного. Подъём означает, що ты растёшь.", en: "A mountain is a big goal and a challenge: it calls upward, and the climb is effort for something important. Ascending means you are growing." }, },
  { id: "s23", icon: "🕊️",
    name: { uk: "Горлиця", ru: "Горлица", en: "Dove" },
    keywords: { uk: "мир, ніжність, надія", ru: "мир, нежность, надежда", en: "peace, tenderness, hope" },
    text: { uk: "Горлиця — мир і тиха радість: після складнощів настає спокій. Сон говорить, що в тебе досить ніжності й довіри, аби помиритися зі світом і з собою.", ru: "Горлица — мир и тихая радость: после сложностей наступает покой. Сон говорит, что в тебе достаточно нежности и доверия, чтобы помириться с миром и с собой.", en: "A dove is peace and quiet joy: calm returns after difficulties. The dream says you have enough tenderness and trust to make peace with the world and with yourself." }, },
  { id: "s24", icon: "⛈️",
    name: { uk: "Гроза", ru: "Гроза", en: "Storm" },
    keywords: { uk: "напруження, розрядка, очищення", ru: "напряжение, разрядка, очищение", en: "tension, release, cleansing" },
    text: { uk: "Гроза — накопичене напруження, яке шукає розрядки. Після неї стає легше, а повітря чистіше: підказка випустити емоції й почати заново.", ru: "Гроза — накопившееся напряжение, которое ищет разрядки. После неё становится легче, а воздух чище: подсказка выпустить эмоции и начать заново.", en: "A storm is accumulated tension seeking release. After it comes relief and cleaner air: a hint to let emotions out and begin afresh." }, },
  { id: "s25", icon: "💰",
    name: { uk: "Гроші", ru: "Деньги", en: "Money" },
    keywords: { uk: "самоцінність, достаток, щедрість, впевненість", ru: "самоценность, достаток, щедрость, уверенность", en: "self-worth, abundance, generosity, confidence" },
    text: { uk: "Гроші уві сні — не про багатство, а про самоцінність: скільки ти «вартий» у власних очах, чи почуваєшся гідним успіху й достатку.", ru: "Деньги во сне — не про богатство, а про самоценность: сколько ты «стоишь» в своих глазах, чувствуешь ли себя достойным успеха и обилия.", en: "Money in a dream is not about wealth but self-worth: how much you are 'worth' in your own eyes, whether you feel deserving of success and abundance." }, },
];
