/*** = Синхронизировано со скриптом конвертации: не редактировать. */
/** D_DK — символы сновидений А-Г. */

export const D_DK = [
/** Сонник · символи сновидінь (повний словник, синхронізований з БД). */

  { id: "s26", icon: "🚪",
    name: { uk: "Двері", ru: "Дверь", en: "Door" },
    keywords: { uk: "перехід, можливості, вибір, новий етап", ru: "переход, возможности, выбор, новый этап", en: "transition, opportunity, choice, new stage" },
    text: { uk: "Двері — межа між «зараз» і «далі». Відчинені — запрошують крокувати в нове; зачинені — момент вибору: постукати, знайти інший вхід чи зачекати.", ru: "Дверь — граница между «сейчас» и «дальше»: открытая — приглашение шагнуть в новое; закрытая — момент выбрать: постучаться, найти другой вход или подождать.", en: "The door is the border between 'now' and 'next': open — an invitation to step into the new; closed — a moment to choose: knock, find another entrance, or wait." }, },
  { id: "s27", icon: "🌳",
    name: { uk: "Дерево", ru: "Дерево", en: "Tree" },
    keywords: { uk: "коріння, рід, ріст, стійкість", ru: "корни, род, рост, устойчивость", en: "roots, kin, growth, stability" },
    text: { uk: "Дерево — коріння, рід і ріст: твоя сила й опора, звʼязок з історією сімʼї та власним розвитком. Квітуче дерево — життя у розквіті.", ru: "Дерево — корни, род и рост: твоя сила и опора, связь с историей семьи и с собственным развитием. Цветущее дерево — жизнь в расцвете.", en: "The tree is roots, kin and growth: your strength and support, the link to family history and your own development. A blooming tree — life in full bloom." }, },
  { id: "s28", icon: "🪞",
    name: { uk: "Дзеркало", ru: "Зеркало", en: "Mirror" },
    keywords: { uk: "самопізнання, чесність, самоприйняття, двоїстість", ru: "самопонимание, честность, самопринятие, двойственность", en: "self-knowledge, honesty, self-acceptance, duality" },
    text: { uk: "Дзеркало — погляд на себе справжнього: те, що бачиш, — так себе сприймаєш. Прохання прийняти всі свої відображення, включно з тими, які ховаєш від інших.", ru: "Зеркало — взгляд на себя настоящего: что видишь — так себя воспринимаешь. Просьба принять свои отражения, включая те, что прячешь от других.", en: "The mirror is a look at your true self: what you see is how you perceive yourself. A request to accept your reflections, including those you hide from others." }, },
  { id: "s29", icon: "👶",
    name: { uk: "Дитина", ru: "Ребёнок", en: "Child" },
    keywords: { uk: "початок, чистота, біль прийняття", ru: "начало, чистота, принятие", en: "beginning, innocence, acceptance" },
    text: { uk: "Дитина — нове, що народжується в тобі: ідея, проєкт, частина тебе. Сон про піклування про дитину — про піклування про молодий і вразливий початок.", ru: "Ребёнок — новое, что рождается в тебе: идея, проект, часть тебя. Сон об уходе за ребёнком — об уходе за молодым и уязвимым началом.", en: "A child is something new being born in you: an idea, a project, a part of yourself. Caring for a child in a dream is about caring for a young, vulnerable beginning." }, },
  { id: "s30", icon: "👴",
    name: { uk: "Дідусь", ru: "Дедушка", en: "Grandfather" },
    keywords: { uk: "коріння, опора, усталеність", ru: "корни, опора, устоев", en: "roots, anchor, stability" },
    text: { uk: "Дідусь — коріння, на яких стоїть твоє життя: традиція, порядок, спокійна впевненість. Сон нагадує, що в тебе є опора, яка не залежить від хитких днів.", ru: "Дедушка — корни, на которых стоит твоя жизнь: традиция, порядок, спокойная уверенность. Сон напоминает, что у тебя есть опора, которая не зависит от шатких дней.", en: "A grandfather is the roots your life stands on: tradition, order, quiet confidence. The dream reminds you that you have an anchor not shaken by unsteady days." }, },
  { id: "s31", icon: "🏠",
    name: { uk: "Дім", ru: "Дом", en: "House" },
    keywords: { uk: "внутрішній світ, безпека, затишок", ru: "внутренний мир, безопасность, уют", en: "inner world, safety, comfort" },
    text: { uk: "Дім — образ тебе самого: кімнати — різні сторони життя, дах — захист, двері — межі. Затишно вдома — ти у злагоді з собою; хаос чи ремонт — зміни в тому, як ти облаштовуєш свій внутрішній простір.", ru: "Дом — образ тебя самого: комнаты — разные стороны жизни, крыша — защита, двери — границы. Уютно дома — ты в ладу с собой; хаос или ремонт — перемены в том, как ты обустраиваешь своё внутреннее пространство.", en: "A house is an image of yourself: rooms are life's different sides, the roof is protection, doors are boundaries. Feeling cozy means you are at peace; chaos or renovation points to how you rearrange your inner space." }, },
  { id: "s32", icon: "🛤",
    name: { uk: "Дорога", ru: "Дорога", en: "Road" },
    keywords: { uk: "шлях, вибір, напрямок, рух", ru: "путь, выбор, направление, движение", en: "path, choice, direction, movement" },
    text: { uk: "Дорога — твій життєвий шлях: широка й світла — впевнений рух, звивиста — багато поворотів і виборів. Важливо просто йти в обрану сторону.", ru: "Дорога — твой жизненный путь: широкая и светлая — уверенное движение, извилистая — много поворотов и выборов. Важно просто идти в выбранную сторону.", en: "The road is your life path: wide and bright — confident movement, winding — many turns and choices. What matters is to simply walk your chosen way." }, },
  { id: "s33", icon: "🌧",
    name: { uk: "Дощ", ru: "Дождь", en: "Rain" },
    keywords: { uk: "очищення, оновлення, сльози-полегшення, ріст", ru: "очищение, обновление, слёзы-облегчение, рост", en: "cleansing, renewal, relief, growth" },
    text: { uk: "Дощ — очищення і свіжість: він «змиває» старий біль і втому, даючи ріст. Після зливи завжди прояснюється — так і в житті.", ru: "Дождь — очищение и свежесть: он «смывает» старую боль и усталость, давая рост; после ливня всегда проясняется, как и в жизни.", en: "Rain is cleansing and freshness: it 'washes away' old pain and tiredness, allowing growth. After a downpour the sky always clears — so it is in life." }, },
  { id: "s34", icon: "🚿",
    name: { uk: "Душ", ru: "Душ", en: "Shower" },
    keywords: { uk: "очищення, змиття, новий початок", ru: "очищение, смыть, новое начало", en: "cleansing, washing off, fresh start" },
    text: { uk: "Душ — те, що змиває втому дня й лишає тільки свіже: перезавантаження. Сон про потребу «вимкнути шум», очиститися й почати чисто — з нової сторінки, без старого пилу.", ru: "Душ — то, что смывает усталость дня и оставляет только свежее: перезагрузка. Сон о потребности «выключить шум», очиститься и начать начисто — с новой страницы, без старой пыли.", en: "A shower washes off the day's fatigue and leaves only freshness: a reset. The dream is about a need to 'switch off the noise', cleanse, and start clean — on a new page, without old dust." }, },
  { id: "s35", icon: "📝",
    name: { uk: "Екзамен", ru: "Экзамен", en: "Exam" },
    keywords: { uk: "перевірка, сумнів, готовність, зібраність", ru: "проверка, сомнение, готовность, собранность", en: "test, doubt, readiness, composure" },
    text: { uk: "Екзамен чи запізнення — перевірка себе і страх не встигнути: у підсвідомості зріє сумнів «чи готовий я». Відповідь — зібратися, підготуватись і довіритися силам.", ru: "Экзамен или опоздание — проверка себя и страх не успеть: в подсознании зреет сомнение «достаточно ли я готов». Ответ — собраться, подготовиться и довериться своим силам.", en: "An exam or being late is a self-test and fear of missing out: a doubt 'am I ready enough' ripens inside. The answer — gather yourself, prepare and trust your strength." }, },
  { id: "s36", icon: "🎗️",
    name: { uk: "Жар", ru: "Жар", en: "Heat" },
    keywords: { uk: "пристрасть, напруження, інтенсивність", ru: "страсть, напряжение, интенсивность", en: "passion, tension, intensity" },
    text: { uk: "Жар — проявлений інтерес або розжарення почуттів: щось у тобі «горить». Приємно гаряче — життя цікаве й насичене; занадто гаряче — час додати охолодження, тверезого погляду, паузи.", ru: "Жар — проявленный интерес или накал чувств: что-то в тебе «горит». Приятно горячо — жизнь интересна и насыщена; слишком горячо — время добавить охлаждение, трезвый взгляд, паузу.", en: "Heat is expressed interest or the intensity of feelings: something in you 'burns'. Pleasant warmth means life is interesting and full; too hot signals it is time for cooling, a sober view, a pause." }, },
  { id: "s37", icon: "👩",
    name: { uk: "Жінка", ru: "Женщина", en: "Woman" },
    keywords: { uk: "прийняття, інтуїція, стосунки", ru: "принятие, интуиция, отношения", en: "acceptance, intuition, relationships" },
    text: { uk: "Жінка уві сні — образ прийняття й чутливості: як ти ставишся до мʼякості в собі та в інших. Вона може вказувати на важливі стосунки або на частину тебе, якій потрібна турбота.", ru: "Женщина во сне — образ принятия и чуткости: как ты относишься к мягкости в себе и в других. Она может указывать на важные отношения или на часть тебя, которой нужна забота.", en: "A woman in a dream is an image of acceptance and sensitivity: how you relate to gentleness in yourself and others. She may point to important relationships or to the part of you that needs care." }, },
  { id: "s38", icon: "🪲",
    name: { uk: "Жук", ru: "Жук", en: "Beetle" },
    keywords: { uk: "намистина, наполегливість, терпіння", ru: "настойчивость, упорство, терпение", en: "persistence, patience, small steps" },
    text: { uk: "Жук — наполегливість маленьких «непомітних» діл, які врешті дають великий результат. Сон заохочує йти крок за кроком, не здаватися й не боятися бути непомітним під час шляху.", ru: "Жук — настойчивость маленьких «незаметных» дел, которые в итоге дают большой результат. Сон побуждает идти шаг за шагом, не сдаваться и не бояться быть незаметным в пути.", en: "A beetle is the persistence of small, barely noticed efforts that eventually bring a big result. The dream encourages step-by-step progress, not giving up, and being fine with going unnoticed along the way." }, },
  { id: "s39", icon: "🔍",
    name: { uk: "Загубити", ru: "Потерять", en: "Losing things" },
    keywords: { uk: "втрата, самоцінність, пошук, пріоритети", ru: "потеря, самоценность, поиск, расстановка приоритетов", en: "loss, self-worth, search, priorities" },
    text: { uk: "Загубити річ — втрата звʼязку з собою: щось цінне для тебе «загубилося» — увага, відпочинок чи сенс. Підказка зупинитись і знайти, що важливе.", ru: "Потерять вещи — потеря связи с собой: что-то ценное для тебя «потерялось» — внимание, отдых, смысл. Подсказка остановиться и найти, что для тебя важно.", en: "Losing something is losing touch with yourself: something valuable is 'lost' — attention, rest or meaning. Stop and find what matters to you." }, },
  { id: "s40", icon: "🌍",
    name: { uk: "Земля", ru: "Земля", en: "Earth" },
    keywords: { uk: "опора, матеріальне, життєдайність", ru: "опора, материальное, жизнедательность", en: "ground, material life, nourishment" },
    text: { uk: "Земля — опора й те, на чому стоїть життя: дім, достаток, здоровʼя. Мʼяка та плодюча — хороший ґрунт для задумів; тверда й неприступна — час обирати, куди і як вкопувати коріння.", ru: "Земля — опора и то, на чём стоит жизнь: дом, достаток, здоровье. Мягкая и плодородная — хорошая почва для замыслов; твёрдая и неприступная — время решать, куда и как впускать корни.", en: "Earth is ground and what life stands on: home, abundance, health. Soft and fertile — good soil for your plans; hard and impenetrable — time to decide where and how to put down roots." }, },
  { id: "s41", icon: "⭐",
    name: { uk: "Зірка", ru: "Звезда", en: "Star" },
    keywords: { uk: "надія, мета, керунок", ru: "надежда, цель, направление", en: "hope, goal, direction" },
    text: { uk: "Зірка — орієнтир у темряві: те, заради чого варто рухатися. Сон нагадує, що навіть у непевні часи в тебе є напрям — і світло, яке ти сам можеш нести.", ru: "Звезда — ориентир в темноте: то, ради чего стоит двигаться. Сон напоминает, что даже в неопределённые времена у тебя есть направление — и свет, который ты сам можешь нести.", en: "A star is a guide in the dark: something worth moving toward. The dream reminds you that even in uncertain times you have a direction — and a light you can carry yourself." }, },
  { id: "s42", icon: "⭐",
    name: { uk: "Зірки", ru: "Звёзды", en: "Stars" },
    keywords: { uk: "надія, мрії, орієнтир, удача", ru: "надежда, мечты, ориентир, удача", en: "hope, dreams, guidance, luck" },
    text: { uk: "Зірки — надія й орієнтир: навіть у темряві є світло, яке веде. Знак, що мрії досяжні й у тебе є шлях, що веде.", ru: "Звёзды — надежда и ориентир: даже в темноте есть свет, который ведёт. Знак, что мечты достижимы и у тебя есть путеводное направление.", en: "Stars are hope and guidance: even in the dark there is light that leads. A sign that dreams are reachable and you have a guiding course." }, },
  { id: "s43", icon: "🥷",
    name: { uk: "Злодій", ru: "Вор", en: "Thief" },
    keywords: { uk: "втрата, страх, межа", ru: "потеря, страх, граница", en: "loss, fear, boundary" },
    text: { uk: "Злодій — страх утратити щось цінне: час, увагу, стосунки, себе. Сон питає: хто чи що «краде» твої сили, і де варто зачинити двері міцніше.", ru: "Вор — страх потерять что-то ценное: время, внимание, отношения, себя. Сон спрашивает: кто или что «крадёт» твои силы, и где стоит закрыть двери крепче.", en: "A thief is the fear of losing something valuable: time, attention, relationships, yourself. The dream asks who or what is 'stealing' your energy, and where you should lock the doors tighter." }, },
  { id: "s44", icon: "🐍",
    name: { uk: "Змія", ru: "Змея", en: "Snake" },
    keywords: { uk: "мудрість, зміни, тривога", ru: "мудрость, перемены, тревога", en: "wisdom, change, anxiety" },
    text: { uk: "Змія — гнучкість, уміння «скидати шкуру» старих форм і оновлюватися. Вона нагадує про тривогу або про глибинну мудрість — залежно від того, як ти почуваєшся поруч із нею.", ru: "Змея — гибкость, умение «сбрасывать кожу» старых форм и обновляться. Она напоминает о тревоге или о глубинной мудрости — в зависимости от того, как ты себя чувствуешь рядом с ней.", en: "A snake is flexibility and the ability to shed old forms like skin and renew. It points to anxiety or to deep wisdom, depending on how you feel near it." }, },
  { id: "s45", icon: "🐍",
    name: { uk: "Змія кусає", ru: "Змея кусает", en: "Snake bite" },
    keywords: { uk: "пробудження, попередження, зцілення, зміни", ru: "пробуждение, предупреждение, исцеление, перемены", en: "awakening, warning, healing, change" },
    text: { uk: "Укус змії — пробудження: він «підштовхує» звернути увагу, будить, лікує чи попереджає. Знак, що прийшов час щось змінити.", ru: "Змея кусает — пробуждение: укус «побуждает» обратить внимание — толчок, который будит, лечит или предупреждает. Знак, что пришло время что-то изменить.", en: "A snake bite is awakening: it 'pushes' you to notice — a jolt that wakes, heals or warns. A sign that the time has come to change something." }, },
  { id: "s46", icon: "🪙",
    name: { uk: "Золото", ru: "Золото / монеты", en: "Gold" },
    keywords: { uk: "цінність, достаток, таланти, самооцінка", ru: "ценность, достаток, таланты, самооценка", en: "value, abundance, talents, self-esteem" },
    text: { uk: "Золото й монети — цінне в тобі й навколо: не лише гроші, а самоцінність, таланти й накопичений досвід. Знак достатку й уміння цінувати себе.", ru: "Золото и монеты — ценное в себе и вокруг: не только деньги, а самоценность, таланты и накопленный опыт. Знак достатка и умения ценить себя.", en: "Gold and coins are what is valuable in and around you: not only money but self-worth, talents and gathered experience. A sign of abundance and valuing yourself." }, },
  { id: "s47", icon: "🦷",
    name: { uk: "Зуби", ru: "Зубы", en: "Teeth" },
    keywords: { uk: "впевненість, контроль, перехід", ru: "уверенность, контроль, переход", en: "confidence, control, transition" },
    text: { uk: "Зуби — укус, слово, впевненість: як ти «тримаєш» розмову й межі. Випадають чи крошаться — відчуття втрати міцності в житті; лікуються — відновлення впевненості й порядку.", ru: "Зубы — укус, слово, уверенность: как ты «держишь» разговор и границы. Выпадают или крошатся — ощущение потери прочности в жизни; лечатся — восстановление уверенности и порядка.", en: "Teeth are bite, speech, and confidence: how you 'hold' conversation and boundaries. Falling or crumbling signals a sense of lost strength; being treated signals the return of confidence and order." }, },
  { id: "s48", icon: "🌌",
    name: { uk: "Інший світ", ru: "Иной мир", en: "The otherworld" },
    keywords: { uk: "таємниця, кордони, запитання", ru: "тайна, границы, вопрос", en: "mystery, boundaries, question" },
    text: { uk: "Інший світ уві сні — не про проживання «там», а про межу, за якою починається невідоме. Це запитання до тебе: що лежить за межами твоєї звичної картини, і чим ти готовий розширити її?", ru: "Иной мир во сне — не про проживание «там», а о границе, за которой начинается неизведанное. Это вопрос к тебе: что лежит за пределами твоей привычной картины, и чем ты готов её расширить?", en: "The otherworld in a dream is not about living 'there' but about a boundary beyond which the unknown begins. It poses a question: what lies beyond your familiar picture, and how willing are you to widen it?" }, },
  { id: "s49", icon: "✨",
    name: { uk: "Іскра", ru: "Искра", en: "Spark" },
    keywords: { uk: "запал, початок, натхнення", ru: "запал, начало, вдохновение", en: "spark, beginning, inspiration" },
    text: { uk: "Іскра — маленький запал великої справи: натхнення, яким поки що легко знехтувати. Сон закликає помітити те, що «заіскрилося», і не залишити його згаснути.", ru: "Искра — маленький запал большого дела: вдохновение, которым пока легко пренебречь. Сон призывает заметить то, что «заискрилось», и не дать ему погаснуть.", en: "A spark is the small ignition of a big thing: inspiration it is still easy to overlook. The dream urges you to notice what has 'sparkled' and not let it die out." }, },
  { id: "s50", icon: "🦔",
    name: { uk: "Їжак", ru: "Ёжик", en: "Hedgehog" },
    keywords: { uk: "захист, колючість, самостійність", ru: "защита, колючесть, самостоятельность", en: "protection, prickliness, self-reliance" },
    text: { uk: "Їжак — уміння захиститися, «виставити голки», коли потрібно. Він мирний, поки його не турбують: сон про те, як ти тримаєш дистанцію й обороняєш свій внутрішній простір.", ru: "Ёжик — умение защититься, «выставить иголки», когда нужно. Он мирный, пока его не тревожат: сон о том, как ты держишь дистанцию и защищаешь своё внутреннее пространство.", en: "A hedgehog is the ability to defend yourself, to 'raise your quills' when needed. He is peaceful while unbothered: the dream is about keeping distance and guarding your inner space." }, },
  { id: "s51", icon: "🍉",
    name: { uk: "Кавун", ru: "Арбуз", en: "Watermelon" },
    keywords: { uk: "насолода, соковитість, щедрість", ru: "удовольствие, сочность, щедрость", en: "pleasure, juiciness, generosity" },
    text: { uk: "Кавун — щось солодке й соковите, що дарує життя: радість, щедрість, нагорода за працю. Стиглий — усе дозріло й час насолоджуватися; порожній — пошук смаку в тому, що вже втратило сенс.", ru: "Арбуз — что-то сладкое и сочное, что дарит жизнь: радость, щедрость, награда за труд. Спелый — всё созрело и пора наслаждаться; пустой — поиск вкуса в том, что уже потеряло смысл.", en: "A watermelon is something sweet and juicy that life gives you: joy, generosity, a reward for your work. Ripe — all has matured and it is time to enjoy; hollow — looking for taste in what has already lost its meaning." }, },
  { id: "s52", icon: "🪨",
    name: { uk: "Камінь", ru: "Камень", en: "Stone" },
    keywords: { uk: "опора, тягар, сталість", ru: "опора, тяжесть, постоянство", en: "support, weight, steadiness" },
    text: { uk: "Камінь — і опора, і тягар: усе залежить від того, як ти з ним поводишся. Узяти в руки основу для будівництва — будувати міцне; нести щось неможливе — час скласти частину ноші.", ru: "Камень — и опора, и тяжесть: всё зависит от того, как ты с ним обращаешься. Взять в руки основу для строительства — строить прочное; нести неподъёмное — время сбросить часть ноши.", en: "A stone is both support and weight — it depends on how you handle it. Taking it as a foundation means building something solid; carrying impossible weight means it is time to put part of it down." }, },
  { id: "s53", icon: "🎠",
    name: { uk: "Карусель", ru: "Карусель", en: "Carousel" },
    keywords: { uk: "повторення, дитинство, ритм", ru: "повторение, детство, ритм", en: "repetition, childhood, rhythm" },
    text: { uk: "Карусель — коло, що крутиться на одному місці: знайомі повтори, улюблені або засвоєні звички. Вона нагадує про радість упізнавання, але й питає: ти готовий вийти на новий атракціон?", ru: "Карусель — круг, что крутится на одном месте: знакомые повторы, любимые или усвоенные привычки. Она напоминает о радости узнавания, но и спрашивает: готов ли ты выйти на новый аттракцион?", en: "A carousel is a wheel spinning in place: familiar repetitions, beloved or learned habits. It recalls the joy of recognition, yet asks whether you are ready for a new ride." }, },
  { id: "s54", icon: "🌸",
    name: { uk: "Квіти", ru: "Цветы", en: "Flowers" },
    keywords: { uk: "краса, ріст, любов, плоди турботи", ru: "красота, рост, любовь, плоды заботы", en: "beauty, growth, love, fruit of care" },
    text: { uk: "Квіти та сад — краса, любов і розквіт: усе хороше в тобі росте й зріє. Сад, що доглядають, — нагадування бережно піклуватися про цінне.", ru: "Цветы и сад — красота, любовь и расцвет: всё хорошее в тебе растёт и зреет. Сад в уходе — напоминание бережно заботиться о том, что для тебя ценно.", en: "Flowers and a garden are beauty, love and blooming: all the good in you is growing and ripening. A tended garden is a reminder to care for what you value." }, },
  { id: "s55", icon: "🐎",
    name: { uk: "Кінь", ru: "Лошадь", en: "Horse" },
    keywords: { uk: "сила, свобода, рух, енергія", ru: "сила, свобода, движение, энергия", en: "strength, freedom, movement, energy" },
    text: { uk: "Кінь — сила і рух уперед: твоя внутрішня енергія, пристрасть і прагнення свободи. Керувати конем — означає самому вести своє життя.", ru: "Лошадь — сила и движение вперёд: твоя внутренняя энергия, страсть и стремление к свободе. Управлять конём — значит самому вести свою жизнь.", en: "The horse is strength and forward motion: your inner energy, passion and urge for freedom. Steering the horse means leading your own life." }, },
  { id: "s56", icon: "🐱",
    name: { uk: "Кіт", ru: "Кошка", en: "Cat" },
    keywords: { uk: "незалежність, інтуїція, гнучкість", ru: "независимость, интуиция, гибкость", en: "independence, intuition, grace" },
    text: { uk: "Кіт — незалежність і вміння «приземлятися на лапи» за будь-яких обставин. Він закликає довіряти інтуїції та тому, що тобі зараз насправді потрібно, а не чужим очікуванням.", ru: "Кошка — независимость и умение «приземляться на лапы» при любых обстоятельствах. Она призывает доверять интуиции и тому, что тебе сейчас на самом деле нужно, а не чужим ожиданиям.", en: "A cat is independence and the grace to 'land on its feet' in any circumstances. It calls you to trust your intuition and what you truly need now, not others' expectations." }, },
  { id: "s57", icon: "🐈",
    name: { uk: "Кішка", ru: "Кошка", en: "Cat" },
    keywords: { uk: "незалежність, інтуїція, гнучкість, загадка", ru: "независимость, интуиция, гибкость, загадка", en: "independence, intuition, flexibility, mystery" },
    text: { uk: "Кішка — незалежна й граціозна частина тебе, що йде своїм шляхом. Підказка довіритися інстинктам і мʼякості.", ru: "Кошка — независимость и интуиция: свободная и грациозная часть тебя, которая идёт своим путём. Подсказка — довериться инстинктам и мягкости.", en: "The cat is independence and intuition: the free, graceful part of you that walks its own path. Trust your instincts and softness." }, },
  { id: "s58", icon: "⚰",
    name: { uk: "Кладовище", ru: "Кладбище", en: "Cemetery" },
    keywords: { uk: "памʼять, минуле, спокій, оновлення", ru: "память, прошлое, покой, обновление", en: "memory, past, peace, renewal" },
    text: { uk: "Кладовище — памʼять і повага до минулого: його можна шанувати, але не жити там. Образ «залишити старі тривоги позаду».", ru: "Кладбище — память и уважение к прошлому: его можно чтить, но не жить там. Образ «оставить старые тревоги в прошлом».", en: "A cemetery is memory and respect for the past: you can honour it but not live there. An image of 'leaving old worries behind'." }, },
  { id: "s59", icon: "🔑",
    name: { uk: "Ключ", ru: "Ключ", en: "Key" },
    keywords: { uk: "відповідь, доступ, рішення", ru: "ответ, доступ, решение", en: "answer, access, solution" },
    text: { uk: "Ключ — відповідь чи доступ до чогось зачиненого: рішення, якого ти шукаєш, або вихід, що вже в тебе в руках. Сон каже: можливо, ти ближче до розвʼязку, ніж думаєш.", ru: "Ключ — ответ или доступ к чему-то закрытому: решение, которое ты ищешь, или выход, что уже в твоих руках. Сон говорит: возможно, ты ближе к разгадке, чем думаешь.", en: "A key is an answer or access to something locked: the solution you seek, or an exit already in your hands. The dream says you may be closer to the answer than you think." }, },
  { id: "s60", icon: "🩸",
    name: { uk: "Кров", ru: "Кровь", en: "Blood" },
    keywords: { uk: "життєва сила, енергія, рід, пристрасть", ru: "жизненная сила, энергия, родство, страсть", en: "vitality, energy, kinship, passion" },
    text: { uk: "Кров — життєва сила й енергія. Втрачати її уві сні — почуватися спустошеним; бачити кров — міцні звʼязки, рід, пристрасть, життя бʼє ключем.", ru: "Кровь — жизненная сила и энергия: потерять её во сне — ощущать себя опустошённым; видеть кровь — прочные связи, род, страсть, жизнь бьёт ключом.", en: "Blood is vitality and energy: losing it in a dream feels like emptiness; seeing it — strong bonds, kin, passion, life at full flow." }, },
];
