/*** = Синхронизировано со скриптом конвертации: не редактировать. */
/** D_LO — символы сновидений А-Г. */

export const D_LO = [
/** Сонник · символи сновидінь (повний словник, синхронізований з БД). */

  { id: "s61", icon: "🧖",
    name: { uk: "Лазня", ru: "Баня", en: "Bathhouse" },
    keywords: { uk: "очищення, відпочинок, відновлення", ru: "очищение, отдых, восстановление", en: "cleansing, rest, renewal" },
    text: { uk: "Лазня — очищення тіла й душі: зняти зайве, відпустити напругу й вийти «новим». Якщо жар лякає — час розібратися з тим, що ти довго тримав усередині.", ru: "Баня — очищение тела и души: снять лишнее, отпустить напряжение и выйти «новым». Если жар пугает — время разобраться с тем, что ты долго держал внутри.", en: "A bathhouse is cleansing for body and soul: shed the excess, release tension, and step out renewed. If the heat frightens you, it is time to face what you have long kept inside." }, },
  { id: "s62", icon: "🦊",
    name: { uk: "Лисиця", ru: "Лиса", en: "Fox" },
    keywords: { uk: "хитрість, гнучкість, пильність", ru: "хитрость, гибкость, зоркость", en: "wit, adaptability, alertness" },
    text: { uk: "Лисиця — кмітливість і вміння бачити, що справді стоїть за словами. Сон підказує: обставини можна обійти, а не лише «пробивати лобом» — головне не плутати хитрість з оманою себе.", ru: "Лиса — смекалка и умение видеть, что на самом деле стоит за словами. Сон подсказывает: обстоятельства можно обойти, а не только «пробивать лбом» — главное не путать хитрость с самообманом.", en: "A fox is cleverness and the ability to see what really stands behind words. The dream hints that circumstances can be outsmarted rather than only 'bumped through' — just do not confuse cleverness with self-deception." }, },
  { id: "s63", icon: "🛏️",
    name: { uk: "Ліжко", ru: "Кровать", en: "Bed" },
    keywords: { uk: "відпочинок, довіра, близькість", ru: "отдых, доверие, близость", en: "rest, trust, intimacy" },
    text: { uk: "Ліжко — місце, де ти нібито «без оборони»: відпочинок, довіра, близькість. Неспокій на ліжку — недосказане в стосунках чи невміння дозволити собі справді відпочити.", ru: "Кровать — место, где ты как будто «без обороны»: отдых, доверие, близость. Беспокойство в кровати — невысказанное в отношениях или неумение позволить себе по-настоящему отдохнуть.", en: "A bed is where you are, as it were, 'unguarded': rest, trust, intimacy. Restlessness there points to the unspoken in relationships or an inability to really allow yourself to rest." }, },
  { id: "s64", icon: "🌲",
    name: { uk: "Ліс", ru: "Лес", en: "Forest" },
    keywords: { uk: "безумовність, глибина, відкриття", ru: "глушь, глубина, открытия", en: "wilderness, depth, discovery" },
    text: { uk: "Ліс — місце, де життя йде за своїми законами: туди можна піти, щоб зустрітися з собою. Він показує, що не все в тобі «причесане», і це нормально: саме в гущавині росте найбільше.", ru: "Лес — место, где жизнь идёт по своим законам: туда можно уйти, чтобы встретиться с собой. Он показывает, что не всё в тебе «причесано», и это нормально: именно в чаще растёт больше всего.", en: "A forest is where life runs on its own rules: you can go there to meet yourself. It shows that not everything in you is 'tamed', and that is fine: the most growth happens in the thicket." }, },
  { id: "s65", icon: "✈",
    name: { uk: "Літак", ru: "Самолёт", en: "Plane" },
    keywords: { uk: "мрія, швидкість, зміни, зліт", ru: "мечта, скорость, перемены, взлёт", en: "dream, speed, change, takeoff" },
    text: { uk: "Літак — швидкі зміни й висота мрії: ти прагнеш більшого і «літаєш» над буденністю. Зліт — сміливий старт у нове.", ru: "Самолёт — быстрые перемены и высота мечты: ты стремишься к большему и «летаешь» над обыденностью. Взлёт — смелый старт в новое.", en: "A plane is rapid change and the height of a dream: you aim higher and 'fly' above the everyday. Takeoff — a bold start into the new." }, },
  { id: "s66", icon: "🦋",
    name: { uk: "Метелик", ru: "Бабочка", en: "Butterfly" },
    keywords: { uk: "легкість, перетворення, краса", ru: "лёгкость, преображение, красота", en: "lightness, transformation, beauty" },
    text: { uk: "Метелик — легкість і перетворення: гусінь стає крилатою, і ти теж виростаєш у щось нове. Сон нагадує про красу змін і про те, що не все важливе має бути «важким».", ru: "Бабочка — лёгкость и преображение: гусеница становится крылатой, и ты тоже вырастаешь во что-то новое. Сон напоминает о красоте перемен и о том, что не всё важное должно быть «тяжёлым».", en: "A butterfly is lightness and transformation: a caterpillar grows wings, and so do you become something new. The dream reminds you that change can be beautiful and that not everything important has to be heavy." }, },
  { id: "s67", icon: "🌉",
    name: { uk: "Міст", ru: "Мост", en: "Bridge" },
    keywords: { uk: "зʼєднання, перехід, рішення", ru: "соединение, переход, решение", en: "connection, crossing, decision" },
    text: { uk: "Міст — спосіб потрапити на інший бік: зʼєднання людей, світів, етапів життя. Переходиш — готовий до переходу; вагаєшся — питання не в мосту, а в готовності зробити крок.", ru: "Мост — способ попасть на другую сторону: соединение людей, миров, этапов жизни. Переходишь — готов к переходу; колебаешься — вопрос не в мосту, а в готовности сделать шаг.", en: "A bridge is how you get to the other side: it connects people, worlds, and stages of life. Crossing means you are ready; hesitating is not about the bridge but about readiness to step." }, },
  { id: "s68", icon: "🌙",
    name: { uk: "Місяць", ru: "Луна", en: "Moon" },
    keywords: { uk: "інтуїція, ніч, цикл", ru: "интуиция, ночь, цикл", en: "intuition, night, cycle" },
    text: { uk: "Місяць — частина тебе, що бачить у темряві: відчуття, передчуття, тихі знання. Місяць росте чи спадає — нагадування, що все має цикл, і зараз ти десь на його колі.", ru: "Луна — часть тебя, что видит в темноте: чувства, предчувствия, тихие знания. Луна растёт или убывает — напоминание, что у всего есть цикл, и сейчас ты где-то на его круге.", en: "The moon is the part of you that can see in the dark: feelings, hunches, quiet knowing. Whether it waxes or wanes, the moon reminds you that everything has a cycle — and you are somewhere on its wheel." }, },
  { id: "s69", icon: "🥛",
    name: { uk: "Молоко", ru: "Молоко", en: "Milk" },
    keywords: { uk: "живлення, турбота, чистота", ru: "питание, забота, чистота", en: "nourishment, care, purity" },
    text: { uk: "Молоко — те, що живить і гріє: турбота про себе й про інших. Воно нагадує про просту «дитячу» щедрість — давати й приймати з легкістю, без умов.", ru: "Молоко — то, что питает и согревает: забота о себе и о других. Оно напоминает о простой «детской» щедрости — давать и принимать легко, без условий.", en: "Milk is what nourishes and warms: care for yourself and others. It recalls the simple, 'childlike' generosity of giving and receiving easily, without conditions." }, },
  { id: "s70", icon: "🌊",
    name: { uk: "Море", ru: "Море", en: "Sea" },
    keywords: { uk: "багато почуттів, глибина, діапазон", ru: "много чувств, глубина, размах", en: "depth of feeling, vastness, scope" },
    text: { uk: "Море — великий простір почуттів: усе, що ти проживаєш, має глибину й розмах. Спокійне море — внутрішня згода; бурхливе — великі хвилі емоцій, з якими можна «переплисти» разом із хвилями.", ru: "Море — большое пространство чувств: всё, что ты переживаешь, имеет глубину и размах. Спокойное море — внутреннее согласие; бурное — большие волны эмоций, с которыми можно «переплыть» вместе с волнами.", en: "The sea is a vast space of feeling: all you experience has depth and scope. A calm sea is inner agreement; a rough one is great emotional waves you can cross by moving with them." }, },
  { id: "s71", icon: "🏛️",
    name: { uk: "Музей", ru: "Музей", en: "Museum" },
    keywords: { uk: "памʼять, цінність, минуле", ru: "память, ценность, прошлое", en: "memory, value, past" },
    text: { uk: "Музей — те, що тобі цінно зберегти: спогади, досвід, особисту історію. Він показує, що дещо з минулого варто лишити «на полиці», а дещо — дістати і згадати, ким ти вже був.", ru: "Музей — то, что тебе ценно сохранить: воспоминания, опыт, личную историю. Он показывает, что кое-что из прошлого стоит оставить «на полке», а кое-что — достать и вспомнить, кем ты уже был.", en: "A museum is what you value preserving: memories, experience, personal history. It shows that some of the past belongs 'on the shelf', while some deserves to be taken out and remembered — who you have already been." }, },
  { id: "s72", icon: "🚼",
    name: { uk: "Народження", ru: "Рождение", en: "Birth" },
    keywords: { uk: "перехід, новий етап, сила", ru: "переход, новый этап, сила", en: "transition, new stage, strength" },
    text: { uk: "Народження — початок нового етапу не тільки зовні, а й усередині. Це завершення «вагітності» думки чи справи: те, що зріло, нарешті виходить на світ.", ru: "Рождение — начало нового этапа не только снаружи, но и внутри. Это завершение «беременности» мысли или дела: то, что созревало, наконец выходит на свет.", en: "Birth is the beginning of a new stage, both outside and within. It completes the 'pregnancy' of a thought or undertaking: what has been maturing finally comes into the light." }, },
  { id: "s73", icon: "🌤️",
    name: { uk: "Небо", ru: "Небо", en: "Sky" },
    keywords: { uk: "простір, перспектива, прагнення", ru: "простор, перспектива, устремление", en: "space, perspective, aspiration" },
    text: { uk: "Небо — твій внутрішній простір: як там, чисто чи хмарно, — так тобі зараз «дихається». Воно запрошує підняти погляд вище й побачити можливість, що була всюди навколо.", ru: "Небо — твоё внутреннее пространство: чисто там или облачно, так тебе сейчас «дышится». Оно приглашает поднять взгляд выше и увидеть возможность, которая была всё это время вокруг.", en: "The sky is your inner space: whether it is clear or cloudy is how you 'breathe' right now. It invites you to lift your gaze and see a possibility that was around you all along." }, },
  { id: "s74", icon: "🧵",
    name: { uk: "Нитка", ru: "Нитка", en: "Thread" },
    keywords: { uk: "звʼязок, шлях, плетіння", ru: "связь, путь, плетение", en: "connection, path, weaving" },
    text: { uk: "Нитка — те, що зшиває твоє життя: звʼязки, лінія долі, наступність. Розмотав клубок — розмотуєш власну історію й дивишся, куди вона веде.", ru: "Нитка — то, что сшивает твою жизнь: связи, линия судьбы, преемственность. Размотал клубок — распутываешь собственную историю и смотришь, куда она ведёт.", en: "A thread is what stitches your life together: bonds, a life-line, continuity. Unwinding a ball means unraveling your own story and seeing where it leads." }, },
  { id: "s75", icon: "💅",
    name: { uk: "Нігті", ru: "Ногти", en: "Nails" },
    keywords: { uk: "догляд, образ, захист", ru: "уход, образ, защита", en: "care, image, defense" },
    text: { uk: "Нігті — дрібна увага до себе: як ти «прибираєш краї», так тримаєш образ і межі. Рівні, доглянуті — порядок навколо тебе; ламаються — дрібні подразнення, що просять уваги.", ru: "Ногти — мелкая забота о себе: как ты «убираешь края», так держишь образ и границы. Ровные, ухоженные — порядок вокруг тебя; ломаются — мелкие раздражения, что просят внимания.", en: "Nails are small care for yourself: how you 'trim the edges' mirrors how you keep your image and boundaries. Neat and groomed — order around you; breaking — small irritations asking for attention." }, },
  { id: "s76", icon: "🔪",
    name: { uk: "Ніж", ru: "Нож", en: "Knife" },
    keywords: { uk: "різкість, межа, вибір", ru: "резкость, граница, выбор", en: "sharpness, boundary, choice" },
    text: { uk: "Ніж — здатність розділяти, відсікати, захищатися: іноді треба «відрізати» зайве, щоб зберегти ціле. Сон питає: що варто нарешті відпустити гострим і чесним жестом?", ru: "Нож — способность разделять, отсекать, защищаться: иногда нужно «отрезать» лишнее, чтобы сохранить целое. Сон спрашивает: что стоит наконец отпустить острым и честным жестом?", en: "A knife is the ability to divide, cut away, and defend: sometimes you must 'cut off' the excess to keep the whole. The dream asks what is finally worth letting go with a sharp, honest gesture." }, },
  { id: "s77", icon: "🧥",
    name: { uk: "Одяг", ru: "Одежда", en: "Clothes" },
    keywords: { uk: "образ, роль, соціальна шкіра", ru: "образ, роль, социальная кожа", en: "image, role, social skin" },
    text: { uk: "Одяг — те, як ти показуєш себе світу: ролі, образ, «броня». Новий і зручний — ти впевнено приміряєш своє; чужий або не по тобі — час бути щирішим у тому, ким «одягаєшся» щодня.", ru: "Одежда — то, как ты показываешь себя миру: роли, образ, «броня». Новая и удобная — ты уверенно примеряешь своё; чужая или не по размеру — время быть искреннее в том, кем «одеваешься» каждый день.", en: "Clothes are how you present yourself to the world: roles, image, 'armor'. New and comfortable — you confidently wear what is yours; ill-fitting or borrowed — it is time to be more honest about 'who you put on' daily." }, },
  { id: "s78", icon: "🌐",
    name: { uk: "Океан", ru: "Океан", en: "Ocean" },
    keywords: { uk: "неосяжність, безодня, спільність", ru: "необъятность, бездна, общность", en: "vastness, depth, belonging" },
    text: { uk: "Океан — надто великий простір, щоб його контролювати: він про звʼязок з усім і про те, що є речі могутніші за нас. Пливи разом із рухами, а не проти всього океану.", ru: "Океан — слишком большой простор, чтобы его контролировать: он о связи со всем и о том, что есть вещи могущественнее нас. Плыви вместе с движениями, а не против всего океана.", en: "The ocean is too vast to control: it is about connection to everything and about forces greater than us. Swim with its movements, not against the whole ocean." }, },
  { id: "s79", icon: "🦌",
    name: { uk: "Олень", ru: "Олень", en: "Deer" },
    keywords: { uk: "грація, пильність, тиха сила", ru: "грация, внимательность, тихая сила", en: "grace, alertness, quiet strength" },
    text: { uk: "Олень — тиха сила, що вміє бути і ніжною, і рішучою: він виглядає спокійно, але весь увага. Сон про вміння тримати внутрішню грацію, попри те, що навколо може бути неспокій.", ru: "Олень — тихая сила, что умеет быть и нежной, и решительной: он выглядит спокойно, но весь во внимании. Сон об умении сохранять внутреннюю грацию, даже когда вокруг неспокойно.", en: "A deer is quiet strength that is both gentle and decisive: it looks calm yet is fully alert. The dream is about keeping inner grace even when the world around is restless." }, },
  { id: "s80", icon: "🏝️",
    name: { uk: "Острів", ru: "Остров", en: "Island" },
    keywords: { uk: "усамітнення, самодостатність, тиша", ru: "уединение, самодостаточность, тишина", en: "solitude, self-sufficiency, silence" },
    text: { uk: "Острів — місце, де є тільки ти й твоя територія: перепочинок або ізоляція — залежить від почуттів. Сон питає: тобі добре наодинці чи бракує мосту назад до людей?", ru: "Остров — место, где есть только ты и твоя территория: передышка или изоляция — зависит от чувств. Сон спрашивает: тебе хорошо наедине или не хватает моста обратно к людям?", en: "An island is a place with only you and your territory: rest or isolation, depending on how it feels. The dream asks whether you enjoy being alone or miss a bridge back to people." }, },
];
