/*** = Синхронизировано со скриптом конвертации: не редактировать. */
/** D_PZ — символы сновидений А-Г. */

export const D_PZ = [
/** Сонник · символи сновидінь (повний словник, синхронізований з БД). */

  { id: "s81", icon: "🕷",
    name: { uk: "Павук", ru: "Паук", en: "Spider" },
    keywords: { uk: "творчість, терпіння, устройство життя, майстерність", ru: "творчество, терпение, устройство жизни, мастерство", en: "creativity, patience, life design, mastery" },
    text: { uk: "Павук — творчість і терпіння: ти «плетеш» своє життя з ниток, які сам обираєш. Нагадує, що прилежна праця принесе плоди.", ru: "Паук — творчество и терпение: ты «плетёшь» свою жизнь из нитей, которые сам выбираешь. Он напоминает, что прилежная работа принесёт плоды.", en: "The spider is creativity and patience: you 'weave' your life from the threads you choose. It reminds that diligent work brings fruit." }, },
  { id: "s82", icon: "🕸️",
    name: { uk: "Павутиння", ru: "Паутина", en: "Spider web" },
    keywords: { uk: "сплетіння, тонка праця, звʼязки", ru: "сплетение, тонкая работа, связи", en: "weaving, fine work, connections" },
    text: { uk: "Павутиння — мережа того, що ти тихо й довго створював: звʼязки, плани, звички. Подивись, звідки воно росте: що ти плечеш і чи в цю мережу хочеш ловити свою «здобич»?", ru: "Паутина — сеть того, что ты тихо и долго создавал: связей, планов, привычек. Посмотри, откуда она растёт: что ты плетёшь и туда ли хочешь ловить свою «добычу»?", en: "A spider web is the net of what you have quietly built for a long time: bonds, plans, habits. Look at where it grows: what are you weaving, and what 'prey' do you actually want to catch?" }, },
  { id: "s83", icon: "🪂",
    name: { uk: "Падіння", ru: "Падение", en: "Falling" },
    keywords: { uk: "втрата контролю, страх, приземлення", ru: "потеря контроля, страх, приземление", en: "loss of control, fear, landing" },
    text: { uk: "Падіння — відчуття, що ґрунт «йде з-під ніг»: перевантаженість, втома, страх не впоратися. Сон часто зʼявляється, коли ти тримаєш надто багато на собі, і нагадує: падіння не вічне, земля завжди є.", ru: "Падение — ощущение, что земля «уходит из-под ног»: перегрузка, усталость, страх не справиться. Сон часто появляется, когда ты держишь слишком много на себе, и напоминает: падение не вечно, земля всегда есть.", en: "Falling is the feeling that the ground is giving way: overload, fatigue, fear of failing. It often comes when you carry too much and reminds you that falling is not eternal — the ground is always there." }, },
  { id: "s84", icon: "🖼️",
    name: { uk: "Парасолька", ru: "Зонт", en: "Umbrella" },
    keywords: { uk: "захист, турбота, тимчасовість", ru: "защита, забота, скоротечность", en: "protection, care, temporary shelter" },
    text: { uk: "Парасолька — захист, який тримаєш у власних руках: вона не зупиняє дощи, але прикриває тебе від нього. Сон про те, що ти вмієш подбати про себе, і про те, що будь-який захист — тимчасовий помічник, а не постійна стіна.", ru: "Зонт — защита, которую держишь в собственных руках: он не останавливает дождь, но укрывает тебя от него. Сон о том, что ты умеешь позаботиться о себе, и о том, что любая защита — временный помощник, а не постоянная стена.", en: "An umbrella is protection held in your own hands: it does not stop the rain, but shelters you from it. The dream is about your ability to care for yourself — and that all protection is a temporary helper, not a permanent wall." }, },
  { id: "s85", icon: "🚶",
    name: { uk: "Первісна стежка", ru: "Первозданная тропа", en: "Bygone trail" },
    keywords: { uk: "вибір шляху, слід, повернення", ru: "выбор пути, след, возвращение", en: "path choice, trace, return" },
    text: { uk: "Стежка — напрям, яким ти вже ходив і який досі тебе кличе: звички, знайомі місця, «протоптані» рішення. Іти нею легше, але чи веде вона туди, куди ти насправді прагнеш?", ru: "Тропа — направление, по которому ты уже ходил и которое до сих пор зовёт: привычки, знакомые места, «протоптанные» решения. Идти по ней легче, но ведёт ли она туда, куда ты на самом деле хочешь?", en: "A trail is a direction you have walked before and which still calls you: habits, familiar places, well-worn decisions. It is easier to follow, but does it lead where you truly want to go?" }, },
  { id: "s86", icon: "🦪",
    name: { uk: "Перлина", ru: "Жемчуг", en: "Pearl" },
    keywords: { uk: "рідкісність, винятковість, пошук", ru: "редкость, исключительность, поиск", en: "rarity, uniqueness, search" },
    text: { uk: "Перлина — цінність, яку не здобувають поспіхом: вона росте всередині раковини. Сон про рідкісне в тобі — те, що потребувало терпіння й тепер може бути твоєю опорою.", ru: "Жемчуг — ценность, которую не добывают второпях: она растёт внутри раковины. Сон о редком в тебе — том, что требовало терпения и теперь может стать твоей опорой.", en: "A pearl is a value not gathered in haste: it grows inside a shell. The dream speaks of the rare in you — what has taken patience and can now become your anchor." }, },
  { id: "s87", icon: "🐓",
    name: { uk: "Півень", ru: "Петух", en: "Rooster" },
    keywords: { uk: "сприйняття, голос, ранок", ru: "восприятие, голос, утро", en: "awareness, voice, morning" },
    text: { uk: "Півень — той, хто будить і заявляє про себе: голос, який не боїться бути почутим. Спів півня — початок нового дня, заклик недовго лишитися в темряві, а вийти у світло.", ru: "Петух — тот, кто будит и заявляет о себе: голос, который не боится быть услышанным. Крик петуха — начало нового дня, призыв недолго оставаться в темноте, а выйти на свет.", en: "A rooster is one who wakes others and announces himself: a voice unafraid to be heard. Its crow marks the start of a new day — an invitation not to linger in the dark but to step into light." }, },
  { id: "s88", icon: "🏊",
    name: { uk: "Плавання", ru: "Плыть / утонуть", en: "Swimming" },
    keywords: { uk: "почуття, потік, витривалість, допомога", ru: "чувства, поток, выносливость, помощь", en: "feelings, flow, endurance, help" },
    text: { uk: "Плавання — чи справляєшся ти з потоком почуттів: пливеш — справляєшся і рухаєшся; тонеш — тебе «захльостує», час попросити допомоги й виринути до світла.", ru: "Плаванье/утопление — справляешься ли ты с потоком чувств: плывёшь — справляешься и движешься; тонешь — чувствуешь себя захлестнутым, пора попросить помощи и вынырнуть к свету.", en: "Swimming is whether you cope with the flow of feelings: swimming — you cope and move; drowning — you feel overwhelmed, time to ask for help and rise to the light." }, },
  { id: "s89", icon: "🏃",
    name: { uk: "Погоня", ru: "Погоня", en: "Being chased" },
    keywords: { uk: "уникнення, страх, сміливість, зустріч зі страхом", ru: "избегание, страх, смелость, встреча со страхом", en: "avoidance, fear, courage, facing fear" },
    text: { uk: "Погоня означає: від чогось у житті ти «тікаєш» — страх, обовʼязок чи власні почуття. Підказка — повернутись і розібратись, тоді «переслідувач» ослабне.", ru: "Погоня означает: от чего-то в жизни ты «убегаешь» — страх, обязанность, собственные чувства. Подсказка — повернуться и разобраться, тогда «преследователь» ослабнет.", en: "Being chased means you are 'running from' something in life — a fear, a duty, or your own feelings. The hint: turn around and sort it out, then the 'pursuer' weakens." }, },
  { id: "s90", icon: "🕊",
    name: { uk: "Політ", ru: "Полёт", en: "Flying" },
    keywords: { uk: "свобода, натхнення, висота, зростання", ru: "свобода, вдохновение, высота, рост", en: "freedom, inspiration, height, growth" },
    text: { uk: "Політ — легкість, свобода і погляд на життя «згори»: ти піднявся над проблемами і бачиш перспективу. Підказка — відпустити обмеження і мріяти сміливіше.", ru: "Полёт — лёгкость, свобода и взгляд на жизнь «свысока»: ты поднялся над проблемами и видишь перспективу. Подсказка — отпустить ограничения и мечтать смелее.", en: "Flying is lightness, freedom, and a view of life 'from above': you have risen over problems and see the big picture. A hint to drop limits and dream bolder." }, },
  { id: "s91", icon: "🕊",
    name: { uk: "Померлий родич", ru: "Умерший близкий", en: "Deceased loved one" },
    keywords: { uk: "памʼять, любов, прощання, втіха", ru: "память, любовь, прощание, утешение", en: "memory, love, farewell, comfort" },
    text: { uk: "Померлий близький — зустріч із памʼяттю й любовʼю, а не зі страхом: душа нагадує про звʼязок, що не зникає, і про те, що життя триває й у нас.", ru: "Умерший близкий — встреча с памятью и любовью, а не со страхом: душа напоминает о связи, которая не исчезает, и о том, что жизнь продолжается и в нас.", en: "A deceased loved one is a meeting with memory and love, not with fear: the soul reminds that the bond never fades and that life continues within us." }, },
  { id: "s92", icon: "🚂",
    name: { uk: "Потяг", ru: "Поезд", en: "Train" },
    keywords: { uk: "шлях, ритм, плани, своєчасність", ru: "путь, ритм, планы, своевременность", en: "path, rhythm, plans, timing" },
    text: { uk: "Потяг — рух наміченим шляхом разом з іншими: ритм життя, плани й попутники долі. Встигнути на потяг — бути в потрібний момент на своєму шляху.", ru: "Поезд — движение по намеченной дороге вместе с другими: ритм жизни, планы и пассажиры судьбы. Успеть на поезд — быть в нужный момент на своём пути.", en: "A train is movement along a set route with others: the rhythm of life, plans and fellow travellers of fate. Catching the train — being where you need at the right time." }, },
  { id: "s93", icon: "🕯",
    name: { uk: "Похорон", ru: "Похороны", en: "Funeral" },
    keywords: { uk: "прощання, відпускання, підсумок, полегшення", ru: "прощание, отпускание, итог, облегчение", en: "farewell, letting go, closure, relief" },
    text: { uk: "Похорон — прощання і відпускання: ти «ховаєш» стару главу — звичку, біль чи колишнього себе — заради звільнення і місця для нового.", ru: "Похороны — прощание и отпускание: ты хоронишь старую главу — привычку, боль или прежнего себя — ради освобождения и нового места для жизни.", en: "A funeral is farewell and letting go: you 'bury' an old chapter — a habit, a pain or a former self — for the sake of freedom and room for the new." }, },
  { id: "s94", icon: "🕊️",
    name: { uk: "Птах", ru: "Птица", en: "Bird" },
    keywords: { uk: "легкість, свобода, новина", ru: "лёгкость, свобода, весть", en: "lightness, freedom, news" },
    text: { uk: "Птах — свобода й уміння дивитися на світ «з висоти»: злетіти над рутиною. Він приносить звістку — можливо, закодуйся внутрішньо: щось нове вже летить до тебе.", ru: "Птица — свобода и умение смотреть на мир «с высоты»: взлететь над рутиной. Она приносит весть — возможно, прислушайся внутренне: что-то новое уже летит к тебе.", en: "A bird is freedom and the ability to see the world 'from above' — to rise above routine. It carries a message; listen inwardly, something new may already be flying your way." }, },
  { id: "s95", icon: "🐟",
    name: { uk: "Риба", ru: "Рыба", en: "Fish" },
    keywords: { uk: "інтуїція, достаток, глибина, почуття", ru: "интуиция, изобилие, глубина, чувства", en: "intuition, abundance, depth, feelings" },
    text: { uk: "Риба — глибинні почуття, інтуїція й достаток: вона живе у «воді» душі, тож сон зве прислухатися до чуття й внутрішніх бажань.", ru: "Рыба — глубинные чувства, интуиция и достаток: она живёт в «воде» души, поэтому сон зовёт прислушаться к чутью и внутренним желаниям.", en: "Fish are deep feelings, intuition and abundance: they live in the 'water' of the soul, so the dream calls to listen to instinct and inner desires." }, },
  { id: "s96", icon: "🗝️",
    name: { uk: "Ручник", ru: "Ручей", en: "Stream" },
    keywords: { uk: "потік, чисті почуття, легкий рух", ru: "поток, чистые чувства, лёгкое движение", en: "flow, clear feelings, easy movement" },
    text: { uk: "Русло — спокійний потік, який тече собі, не тисне й не зупиняється: так можуть текти твої почуття, якщо їм дати простір. Сон нагадує: життя рухається навіть «неспішно».", ru: "Ручей — спокойный поток, который течёт себе, не давит и не останавливается: так могут течь твои чувства, если дать им пространство. Сон напоминает: жизнь движется даже «неспешно».", en: "A stream is a calm flow that simply runs — it neither pushes nor stops: your feelings can flow the same way when given space. The dream reminds you that life moves even unhurriedly." }, },
  { id: "s97", icon: "🌳",
    name: { uk: "Сад", ru: "Сад", en: "Garden" },
    keywords: { uk: "турбота, зростання, урожай", ru: "забота, рост, урожай", en: "care, growth, harvest" },
    text: { uk: "Сад — те, що ти плекаєш у довгостроковій перспективі: стосунки, навички, саму себе. Квітучий сад — твоя турбота повертається; занедбаний — запитання, про що ти хочеш дбати наступним.", ru: "Сад — то, что ты взращиваешь в долгосрочной перспективе: отношения, навыки, саму себя. Цветущий сад — твоя забота возвращается; запущенный — вопрос, о чём ты хочешь заботиться далее.", en: "A garden is what you nurture long-term: relationships, skills, yourself. A blooming garden shows your care returning; an overgrown one asks what you want to tend next." }, },
  { id: "s98", icon: "🕯️",
    name: { uk: "Свічка", ru: "Свеча", en: "Candle" },
    keywords: { uk: "світло, памʼять, тиша", ru: "свет, память, тишина", en: "light, memory, stillness" },
    text: { uk: "Свічка — обережне, живе світло в темряві: воно не осліплює, але показує дорогу. Вона про памʼять, тишу й те, що навіть маленьке світло може тримати ніч подалі.", ru: "Свеча — бережное, живое пламя в темноте: оно не ослепляет, но показывает путь. Она о памяти, тишине и о том, что даже маленький свет может держать ночь на расстоянии.", en: "A candle is a gentle, living light in the dark: it does not dazzle, yet shows the way. It speaks of memory, stillness, and how even a small flame can hold the night at bay." }, },
  { id: "s99", icon: "🕰️",
    name: { uk: "Смерть", ru: "Смерть", en: "Death" },
    keywords: { uk: "завершення, зміна, межа", ru: "завершение, перемена, грань", en: "ending, change, boundary" },
    text: { uk: "Смерть уві сні — майже ніколи не про буквальну подію, а про завершення етапу: старі звички, образи, ролі «вмирають», щоб звільнити місце. Край — це також початок іншого берега.", ru: "Смерть во сне — почти никогда не о буквальном событии, а о завершении этапа: старые привычки, обиды, роли «умирают», чтобы освободить место. Край — это также начало другого берега.", en: "Death in a dream is almost never literal — it marks the end of a stage: old habits, grievances, and roles 'die' to make room. An edge is also the start of another shore." }, },
  { id: "s100", icon: "❄",
    name: { uk: "Сніг", ru: "Снег", en: "Snow" },
    keywords: { uk: "спокій, чистота, тиша, новий початок", ru: "покой, чистота, тишина, новое начало", en: "calm, purity, silence, new beginning" },
    text: { uk: "Сніг — спокій і чистий аркуш: біле покривало вкриває світ, даючи тишу й паузу, а також можливість почати з нуля.", ru: "Снег — покой и чистый лист: белый покров укрывает мир, давая тишину и паузу, а также возможность начать с чистого листа.", en: "Snow is calm and a clean slate: the white cover wraps the world, giving silence and a pause, and the chance to start from scratch." }, },
  { id: "s101", icon: "❄️",
    name: { uk: "Сніжинки", ru: "Снежинки", en: "Snowflakes" },
    keywords: { uk: "легкість, унікальність, сезонність", ru: "лёгкость, уникальность, сезонность", en: "lightness, uniqueness, seasonality" },
    text: { uk: "Сніжинки — краса, що прилітає тихо й без попередження: бачити особливе в дрібницях. Кожна з них унікальна, а разом вони вкривають землю ніжністю — як моменти, що складаються в твою зиму.", ru: "Снежинки — красота, что прилетает тихо и без предупреждения: видеть особенное в мелочах. Каждая из них уникальна, а вместе они укрывают землю нежностью — как моменты, что складываются в твою зиму.", en: "Snowflakes are beauty arriving quietly and unannounced: noticing the special in small things. Each is unique, and together they soften the ground — like the moments composing your winter." }, },
  { id: "s102", icon: "🐕",
    name: { uk: "Собака", ru: "Собака", en: "Dog" },
    keywords: { uk: "вірність, дружба, захист, довіра", ru: "верность, дружба, защита, доверие", en: "loyalty, friendship, protection, trust" },
    text: { uk: "Собака — вірність і дружба: близькі поруч, і на них можна спертися. Нагадує про відданість собі й своїм людям, про довіру й захист.", ru: "Собака — верность и дружба: твои близкие рядом и можно на них опереться. Она напоминает про преданность себе и своим людям, доверие и защиту.", en: "The dog is loyalty and friendship: your close ones are near and you can lean on them. It recalls devotion to yourself and your people, trust and protection." }, },
  { id: "s103", icon: "☀️",
    name: { uk: "Сонце", ru: "Солнце", en: "Sun" },
    keywords: { uk: "тепло, ясність, життєдайність", ru: "тепло, ясность, жизнедательность", en: "warmth, clarity, vitality" },
    text: { uk: "Сонце — саме життя: тепло, енергія, ясність. Воно вказує на твою здатність «світити» навіть тим, хто поруч; сон нагадує, що твої сили відновлюються з днями, як світло зі сходом.", ru: "Солнце — сама жизнь: тепло, энергия, ясность. Оно указывает на твою способность «освещать» даже тех, кто рядом; сон напоминает, что твои силы восстанавливаются день за днём, как свет на рассвете.", en: "The sun is life itself: warmth, energy, clarity. It speaks of your capacity to 'shine' even for those nearby, and reminds you that your strength returns day by day, like light at dawn." }, },
  { id: "s104", icon: "🧭",
    name: { uk: "Схід і Захід", ru: "Восток и Запад", en: "East and West" },
    keywords: { uk: "початок і завершення, шлях", ru: "начало и завершение, путь", en: "beginning and ending, path" },
    text: { uk: "Схід — ранковий світ початків, а захід — вечірній спокій завершення. Якщо уві сні ти бачиш напрям, прислухайся: що ще лише «сходить», а що вже «сідає» у твоєму житті.", ru: "Восток — утренний свет начинаний, а запад — вечерний покой завершения. Если во сне ты видишь направление, прислушайся: что ещё лишь «восходит», а что уже «заходит» в твоей жизни.", en: "East carries the morning light of beginnings; west holds the evening calm of endings. If a direction appears in your dream, listen: what is still only 'rising', and what is already 'setting' in your life?" }, },
  { id: "s105", icon: "🌑",
    name: { uk: "Темна кімната", ru: "Тёмная комната", en: "Dark room" },
    keywords: { uk: "незвідане, страх, самопізнання, внутрішнє світло", ru: "неизведанное, страх, самопознание, внутренний свет", en: "unknown, fear, self-discovery, inner light" },
    text: { uk: "Темна кімната — непізнана частина тебе, яку не хочеш помічати. У темряві можна боятись, але варто «увімкнути світло» розуміння — і там виявиться щось важливе й рідне.", ru: "Тёмная комната — непознанная часть тебя, которую ты не хочешь замечать: в темноте можно бояться, но достаточно «включить свет» понимания — и там окажется что-то важное и родное.", en: "A dark room is an unexplored part of you that you ignore: in the dark you may fear, but once you 'turn on' understanding, something important and familiar is there." }, },
  { id: "s106", icon: "🌫️",
    name: { uk: "Туман", ru: "Туман", en: "Fog" },
    keywords: { uk: "непевність, перехід, можливість", ru: "неопределённость, переход, возможность", en: "uncertainty, transition, chance" },
    text: { uk: "Туман — непевність, коли не видно далеко наперед: страх перед «наосліп». Він минає, коли робиш крок уперед: те, що близько, завжди видно крізь туман.", ru: "Туман — неопределённость, когда не видно далеко вперёд: страх идти «вслепую». Он рассеивается, когда делаешь шаг вперёд: то, что близко, всегда видно сквозь туман.", en: "Fog is uncertainty when you cannot see far ahead: fear of going 'blind'. It lifts once you step forward — the close and near is always visible through fog." }, },
  { id: "s107", icon: "🍞",
    name: { uk: "Хліб", ru: "Хлеб", en: "Bread" },
    keywords: { uk: "достаток, основа, щедрість", ru: "достаток, основа, щедрость", en: "abundance, foundation, generosity" },
    text: { uk: "Хліб — основа життя: достаток, праця, що годує. Свіжий тепло хліб — час і діла приносять плоди; черствий — заклик цінувати те, що вже є, поки воно не «засохло».", ru: "Хлеб — основа жизни: достаток, труд, что кормит. Свежий тёплый хлеб — время и дела приносят плоды; чёрствый — призыв ценить то, что уже есть, пока оно не «засохло».", en: "Bread is the foundation of life: abundance and labor that feeds. Warm fresh bread means time and effort bear fruit; stale bread urges you to value what you have before it 'dries up'." }, },
  { id: "s108", icon: "⛪",
    name: { uk: "Церква", ru: "Церковь", en: "Church" },
    keywords: { uk: "спокій, віра, захист, сенс", ru: "покой, вера, защита, смысл", en: "peace, faith, protection, meaning" },
    text: { uk: "Церква — пошук сенсу, спокою й захисту: внутрішній «храм», де можна побути наодинці з собою. Заклик звернутися до душі й того, у що віриш.", ru: "Церковь — поиск смысла, покоя и защиты: внутренний «храм», где можно побыть наедине с собой. Зов обратиться к душе и тому, во что веришь.", en: "A church is the search for meaning, peace and protection: an inner 'temple' where you can be alone with yourself. A call to your soul and what you believe." }, },
  { id: "s109", icon: "🎪",
    name: { uk: "Цирк", ru: "Цирк", en: "Circus" },
    keywords: { uk: "свято, гра, видовище", ru: "праздник, игра, зрелище", en: "festivity, play, spectacle" },
    text: { uk: "Цирк — місце, де «неможливе» стає звичкою: жонглювання, фокуси, сміливість на канаті. Він каже: уяви в житті — теж навичка, і не соромно бути трохи клоуном, аби зберегти легкість.", ru: "Цирк — место, где «невозможное» становится привычкой: жонглирование, фокусы, смелость на канате. Он говорит: воображение в жизни — тоже навык, и не стыдно быть немного клоуном, чтобы сохранить лёгкость.", en: "A circus is where the 'impossible' becomes routine: juggling, tricks, daring on the tightrope. It says imagination is also a skill — and there is no shame in being a little clownish to keep lightness." }, },
  { id: "s110", icon: "⛵",
    name: { uk: "Човен", ru: "Лодка", en: "Boat" },
    keywords: { uk: "шлях, почуття, самостійність", ru: "путь, чувства, самостоятельность", en: "journey, emotions, self-reliance" },
    text: { uk: "Човен — маленький рух по великій воді: ти сам кермуєш своїм шляхом серед почуттів. Човен тримається на плаву навіть тоді, коли навколо хвилі, — тримайся й ти.", ru: "Лодка — маленькое движение по большой воде: ты сам правишь своим путём среди чувств. Лодка держится на плаву даже когда вокруг волны — держись и ты.", en: "A boat is a small craft moving across great water: you steer your own way among feelings. A boat stays afloat even when the waves rise — so do you." }, },
  { id: "s111", icon: "🍎",
    name: { uk: "Яблуко", ru: "Яблоко", en: "Apple" },
    keywords: { uk: "цілісність, зваба, здоровʼя", ru: "целостность, соблазн, здоровье", en: "wholeness, temptation, health" },
    text: { uk: "Яблуко — цілісність і проста радість життя: те, чим можна поділитися й насолодитися. Воно поєднує здоровʼя, кохання й вибір — як вміння розпізнати, чи «дозріло» твоє рішення.", ru: "Яблоко — целостность и простая радость жизни: то, чем можно поделиться и насладиться. Оно соединяет здоровье, любовь и выбор — как умение распознать, «созрело» ли твоё решение.", en: "An apple is wholeness and the simple joy of life: something to share and savor. It links health, love, and choice — the ability to tell whether your decision has 'ripened'." }, },
  { id: "s112", icon: "🐍",
    name: { uk: "Ящірка", ru: "Ящерица", en: "Lizard" },
    keywords: { uk: "відновлення, майстерність, тихість", ru: "восстановление, ловкость, незаметность", en: "renewal, agility, unobtrusiveness" },
    text: { uk: "Ящірка — вміння відпускати частинки себе, щоб відростити нові: вона не чіпляється за хвіст, який уже не служить. Сон про тихе оновлення — зміни, що відбуваються делікатно, як доглянута шкіра.", ru: "Ящерица — умение отпускать частицы себя, чтобы отрастить новые: она не держится за хвост, который уже не служит. Сон о тихом обновлении — переменах, что происходят деликатно, как обновлённая кожа.", en: "A lizard is the ability to release parts of yourself to grow new ones: it does not cling to a tail that no longer serves. The dream speaks of quiet renewal — changes that happen delicately, like fresh skin." }, },
];
