# -*- coding: utf-8 -*-
"""enrich_tzolkin.py — збагачення колоди «Цолькин» (deck 13).
20 печаток (S01–S20) та 13 тонів (T01–T13) системи Цолькін/Dreamspell.
Основна мова — українська; повні переклади en/ru (включно з symbolism).
Власний навчальний виклад традиційних асоціацій.
Формат кожної карти: (kw_u_uk, kw_r_uk, gen_uk, sym_uk, kw_u_en, kw_r_en, gen_en, sym_en,
                      kw_u_ru, kw_r_ru, gen_ru, sym_ru)
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
CARDS_DIR = Path(__file__).resolve().parents[1] / "Database" / "cards"

TZOLKIN = {
    "S01": (
        "народження, мати", "залежність",
        "Іміш, червоний дракон: початок усього й живлення. Ти стоїш біля джерела — нової справи, нового витка, нової відповідальності. Дракон не просто народжує: він живить, тож подбай про тіло, дім і тих, хто від тебе залежить. Карта радить прийняти роль того, хто дає опору, і не втікати від зрілості. Перевернута — залежність або гіперопіка: годувати інших, забувши про себе.",
        "Голова червоного дракона з широкою пащею та крилами; енергія сходу, що сходить. Колір — червоний, сторона світу — схід.",
        "birth, mother", "dependence",
        "Imix, red dragon: the beginning of all and nourishment. You stand at the source — a new affair, a new turn, a new responsibility. The dragon does not only give birth: it nourishes, so tend the body, home and those who depend on you. The card advises accepting the role of the one who anchors, and not fleeing maturity. Reversed — dependence or overprotection: feeding others while forgetting yourself.",
        "The head of a red dragon with a wide maw and wings; rising east energy. Color — red, direction — east.",
        "рождение, мать", "зависимость",
        "Имиш, красный дракон: начало всего и питание. Ты стоишь у источника — нового дела, нового витка, новой ответственности. Дракон не только рождает: он питает, так что позаботься о теле, доме и тех, кто зависит от тебя. Карта советует принять роль опоры и не бежать от зрелости. Перевёрнутая — зависимость или гиперопека: кормить других, забыв о себе.",
        "Голова красного дракона с широкой пастью и крыльями; восходящая энергия востока. Цвет — красный, сторона света — восток.",
    ),
    "S02": (
        "дух, слово", "порожні слова",
        "Ік, білий вітер: дихання й слово. Усе, що ти говориш, має дух — тож кажи правду вголос, інакше правда скаже тебе. Вітер невидимий, але рухає кронами: так само слово, сказане вчасно, змінює напрям справ. Карта радить провітрювати застояне: розмови, які відкладав, натхнення, яким душився. Перевернута — порожні слова: багато обіцянок, мало вітру.",
        "Вите гліф вітру — завиток, схожий на подих; стріли, що розлітаються. Колір — білий, сторона світу — північ.",
        "spirit, word", "empty words",
        "Ik, white wind: breath and word. All you speak has spirit — so say the truth aloud, or the truth will say you. The wind is invisible yet moves the crowns: so does a word spoken in time change the course of affairs. The card advises airing the stagnant: talks you postponed, inspiration you stifled. Reversed — empty words: many promises, little wind.",
        "The curled glyph of wind, resembling a breath; darts scattering. Color — white, direction — north.",
        "дух, слово", "пустые слова",
        "Ик, белый ветер: дыхание и слово. Всё, что ты говоришь, несёт дух — так что говори правду вслух, иначе правда скажет тебя. Ветер невидим, но движет кронами: так и слово, сказанное вовремя, меняет ход дел. Карта советует проветривать застоявшееся: разговоры, которые откладывал, вдохновение, которое душил. Перевёрнутая — пустые слова: много обещаний, мало ветра.",
        "Витой глиф ветра — завиток, похожий на дыхание; разлетающиеся стрелы. Цвет — белый, сторона света — север.",
    ),
    "S03": (
        "сон, інтуїція", "страх темряви",
        "Акбаль, синя ніч: сни й підсвідоме. Запиши сон — те, що приходить уночі, тримає ключ до денного питання. Ніч не є порожнечею: вона — ґрунт, де проростають відповіді. Карта радить не світити ліхтарем у кожен куток себе, а довіритися тому, що відомо без слів. Перевернута — страх темряви: бійся не саму ніч, а те, що ти в ній приховуєш.",
        "Синя ніч із місяцем; гліф, що нагадує лице, що спить. Колір — синій, сторона світу — захід.",
        "dream, intuition", "fear of dark",
        "Akbal, blue night: dreams and the subconscious. Write the dream down — what comes by night holds the key to the day's question. Night is not emptiness: it is the soil where answers sprout. The card advises not to shine a lamp into every corner of yourself, but to trust what is known without words. Reversed — fear of the dark: fear not the night itself, but what you hide in it.",
        "The blue night with a moon; a glyph resembling a sleeping face. Color — blue, direction — west.",
        "сон, интуиция", "страх темноты",
        "Акбаль, синяя ночь: сны и подсознание. Запиши сон — то, что приходит ночью, хранит ключ к дневному вопросу. Ночь не пуста: она — почва, где прорастают ответы. Карта советует не светить фонарём в каждый уголок себя, а довериться тому, что известно без слов. Перевёрнутая — страх темноты: бойся не самой ночи, а того, что ты в ней прячешь.",
        "Синяя ночь с луной; глиф, напоминающий спящее лицо. Цвет — синий, сторона света — запад.",
    ),
    "S04": (
        "насіння, увага", "безпліддя",
        "Кан, жовте насіння: увага пророщує. Поливай один намір — не те, що хочеш зробити, а те, що хочеш стати. Насіння не вимагає ажіотажу: воно вимагає сталої турботи. Карта радить обрати головне зараз і віддати йому місце в розкладі дня. Перевернута — безпліддя: насіння сохне не від браку дощу, а від метання між грядками.",
        "Жовте зерно, з якого пробивається паросток; гліф, схожий на перевернуте насіння. Колір — жовтий, сторона світу — південь.",
        "seed, attention", "barrenness",
        "Kan, yellow seed: attention makes things sprout. Water one intent — not what you want to do, but what you want to become. The seed does not demand fuss: it demands steady care. The card advises choosing the main thing now and giving it a place in the day. Reversed — barrenness: the seed dries not from lack of rain, but from flitting between beds.",
        "A yellow grain from which a sprout breaks; a glyph like an inverted seed. Color — yellow, direction — south.",
        "семя, внимание", "бесплодие",
        "Кан, жёлтое семя: внимание проращивает. Поливай одно намерение — не то, что хочешь сделать, а то, чем хочешь стать. Семя не требует суеты: оно требует постоянной заботы. Карта советует выбрать главное сейчас и дать ему место в распорядке дня. Перевёрнутая — бесплодие: семя сохнет не от нехватки дождя, а от метания между грядками.",
        "Жёлтое зерно, из которого пробивается росток; глиф, похожий на перевёрнутое семя. Цвет — жёлтый, сторона света — юг.",
    ),
    "S05": (
        "життєва сила", "отрута",
        "Чикчан, червоний змій: тілесна сила, що звивається в спині. Рухайся, дихай, пробуди чуття — енергія не терпить застою. Змія скидає шкіру: так і ти скидаєш те, що вже стало тісно. Карта радить довіритися природі тіла, а не приручати його розкладом. Перевернута — отрута: сила, спрямована проти себе — заздрість, гнів, що жалить.",
        "Змій, що повз нескінченністю; гліф із роздвоєним жалом. Колір — червоний, сторона світу — схід.",
        "life force", "venom",
        "Chicchan, red serpent: bodily force coiling in the spine. Move, breathe, awaken the senses — energy hates stagnation. The snake sheds its skin: so you shed what has become tight. The card advises trusting the body's nature rather than taming it by schedule. Reversed — venom: force turned against itself — envy, a stinging anger.",
        "A serpent crawling through infinity; a glyph with a forked sting. Color — red, direction — east.",
        "жизненная сила", "яд",
        "Чикчан, красный змей: телесная сила, извивающаяся в позвоночнике. Двигайся, дыши, пробуди чувства — энергия не терпит застоя. Змея сбрасывает кожу: так и ты сбрасываешь то, что стало тесным. Карта советует довериться природе тела, а не приручать её расписанием. Перевёрнутая — яд: сила, направленная против себя — зависть, жалящий гнев.",
        "Змей, ползущий сквозь бесконечность; глиф с раздвоенным жалом. Цвет — красный, сторона света — восток.",
    ),
    "S06": (
        "відпускання", "заперечення смерті",
        "Кімі, білий міст: відпусти мертве. Кінець — двері, а не стіна: те, що закінчилося, звільняє місце тому, що іде. Міст зʼєднує обидва береги — не обривай його люто, переходь свідомо. Карта радить попрощатися без затягування: із справою, роллю, людиною, версією себе. Перевернута — заперечення смерті: тримати закриту сторінку, бо починати нову страшно.",
        "Білий міст-гліф, схожий на череп із проваллям; хода, що сполучає береги. Колір — білий, сторона світу — північ.",
        "release", "denying death",
        "Kimi, white world-bridger: let the dead go. An ending is a door, not a wall: what finished frees room for what comes. The bridge joins both banks — do not break it in fury, cross it consciously. The card advises saying goodbye without dragging: to a matter, role, person, version of yourself. Reversed — denying death: holding a closed page because starting a new one is frightening.",
        "A white bridge-glyph like a skull over a chasm; a crossing joining the banks. Color — white, direction — north.",
        "отпускание", "отрицание смерти",
        "Кими, белый мост: отпусти мертвое. Конец — дверь, а не стена: завершившееся освобождает место грядущему. Мост соединяет оба берега — не обрывай его в ярости, переходи осознанно. Карта советует попрощаться без затягивания: с делом, ролью, человеком, версией себя. Перевёрнутая — отрицание смерти: держать закрытую страницу, потому что начинать новую страшно.",
        "Белый глиф-мост, похожий на череп над пропастью; переход, соединяющий берега. Цвет — белый, сторона света — север.",
    ),
    "S07": (
        "зцілення, дія", "бездіяльність",
        "Манік, синя рука: зцілення через дію. Зроби щось руками — лікує не думка про турботу, а сама турбота, втілена в дотику, вчинку, праці. Рука — інструмент благословення, коли вона служить, а не хапає. Карта радить перейти від «що мені сказали» до «що я зроблю». Перевернута — бездіяльність: руки складені, а зцілення не приходить само.",
        "Синя рука, розкрита долонею до світла; гліф у вигляді долоні й променя. Колір — синій, сторона світу — захід.",
        "healing, action", "inaction",
        "Manik, blue hand: healing through action. Do something with your hands — heals not the thought of care, but the care itself realized in touch, deed, labor. The hand is an instrument of blessing when it serves rather than grabs. The card advises moving from 'what they told me' to 'what I will do'. Reversed — inaction: hands folded, and healing does not come on its own.",
        "A blue hand open palm-up to the light; a glyph in the shape of a palm and a ray. Color — blue, direction — west.",
        "исцеление, действие", "бездействие",
        "Маник, синяя рука: исцеление через действие. Сделай что-то руками — лечит не мысль о заботе, а сама забота, воплощённая в прикосновении, поступке, труде. Рука — инструмент благословения, когда служит, а не хватает. Карта советует перейти от «что мне сказали» к «что я сделаю». Перевёрнутая — бездействие: руки сложены, а исцеление не приходит само.",
        "Синяя рука, раскрытая ладонью к свету; глиф в виде ладони и луча. Цвет — синий, сторона света — запад.",
    ),
    "S08": (
        "краса, мистецтво", "марнославство",
        "Ламат, жовта зірка: краса й мистецтво. Прикрась день — гармонія не додаток до життя, а сама його тканина. Зірка вказує шлях, бо світить: тож твоє талант не для шафи. Карта радить створювати заради радості, а не заради оцінки. Перевернута — марнославство: милуватися відблиском своєї зірки, а не справжнім світлом.",
        "Жовта зірка у восьми променях; гліф, схожий на складену квітку. Колір — жовтий, сторона світу — південь.",
        "beauty, art", "vanity",
        "Lamat, yellow star: beauty and art. Decorate the day — harmony is not an addition to life but its very fabric. The star shows the way because it shines: so your gift is not for the closet. The card advises creating for joy, not for appraisal. Reversed — vanity: admiring the glint of your own star, not the true light.",
        "A yellow star with eight rays; a glyph like a folded flower. Color — yellow, direction — south.",
        "красота, искусство", "тщеславие",
        "Ламат, жёлтая звезда: красота и искусство. Укрась день — гармония не приложение к жизни, а сама её ткань. Звезда указывает путь, потому что светит: так и твой дар не для шкафа. Карта советует творить ради радости, а не ради оценки. Перевёрнутая — тщеславие: любоваться отблеском своей звезды, а не настоящим светом.",
        "Жёлтая звезда в восемь лучей; глиф, похожий на сложенный цветок. Цвет — жёлтый, сторона света — юг.",
    ),
    "S09": (
        "потік, очищення", "повінь",
        "Мулук, червоний місяць: потік змиває зайве. Життя — як вода: вона обходить камінь, а не бʼє в нього. Дозволь емоціям текти крізь тебе, не тримаючи їх у запруді, — інакше вони прорвуть греблю. Карта радить синхронізуватися з ритмом, який уже є, а не навʼязувати свій. Перевернута — повінь: коли залито береги, не пливти проти, а знайти високе місце.",
        "Червоний місяць із краплями, що спадають; гліф, схожий на місяць у воді. Колір — червоний, сторона світу — схід.",
        "flow, cleansing", "flood",
        "Muluc, red moon: the flow washes away the excess. Life is like water: it goes around the stone rather than striking it. Let emotions stream through you without damming them — or they will break the levee. The card advises syncing with the rhythm already present, not imposing your own. Reversed — a flood: when the banks are overrun, do not swim against it — seek high ground.",
        "A red moon with falling drops; a glyph like a moon on water. Color — red, direction — east.",
        "поток, очищение", "наводнение",
        "Мулук, красная луна: поток смывает лишнее. Жизнь — как вода: она обходит камень, а не бьёт в него. Позволь эмоциям течь сквозь себя, не запирая их в запруду, — иначе они прорвут плотину. Карта советует синхронизироваться с уже существующим ритмом, а не навязывать свой. Перевёрнутая — наводнение: когда залиты берега, не плыть против, а найти возвышенность.",
        "Красная луна с падающими каплями; глиф, похожий на луну в воде. Цвет — красный, сторона света — восток.",
    ),
    "S10": (
        "вірність, серце", "зрада",
        "Ок, білий собака: вірність серця. Будь поруч — не за обовʼязком, а за вибором, як собака, що не питає умов. Вірність не сліпа: вона лишається там, де вважає дім. Карта радить бути відданим собі й тим, кого обрав, і не торгувати прихильністю. Перевернута — зрада: або зраджуєш ти, або тебе.",
        "Білий собака з вухом догори й серцем у грудях; гліф, схожий на морду. Колір — білий, сторона світу — північ.",
        "loyalty, heart", "betrayal",
        "Oc, white dog: loyalty of the heart. Be present — not out of duty, but out of choice, like a dog that asks no terms. Loyalty is not blind: it stays where it calls home. The card advises being true to yourself and those you chose, and not trading affection. Reversed — betrayal: either you betray, or you are betrayed.",
        "A white dog with an ear raised and a heart in its chest; a glyph like a snout. Color — white, direction — north.",
        "верность, сердце", "измена",
        "Ок, белая собака: верность сердца. Будь рядом — не по обязанности, а по выбору, как собака, что не спрашивает условий. Верность не слепа: она остаётся там, где считает домом. Карта советует быть верным себе и тем, кого выбрал, и не торговать привязанностью. Перевёрнутая — измена: сердце, которое то шерстится, то предаёт, — или предаёшь ты, или тебя.",
        "Белая собака с поднятым ухом и сердцем в груди; глиф, похожий на морду. Цвет — белый, сторона света — север.",
    ),
    "S11": (
        "гра, ілюзія", "дурість",
        "Чуен, синя мавпа: гра розкриває ілюзії. Посмійся з себе — те, над чим можна сміятися, перестає тримати. Мавпа дражнить, але її дражники показують, де штучне, а де живе. Карта радить грати щиро: мистецтво несерйозності повертає втрачену ловкість. Перевернута — дурість: гра заради гри, коли посмішка стає маскою.",
        "Синя мавпа, що гойдається на гілці; гліф у вигляді макової квітки-обличчя. Колір — синій, сторона світу — захід.",
        "play, illusion", "foolishness",
        "Chuen, blue monkey: play reveals illusions. Laugh at yourself — what can be laughed at stops holding you. The monkey teases, but its jibes show where the artificial ends and the living begins. The card advises playing sincerely: the art of playfulness restores lost agility. Reversed — foolishness: play for play's sake, when the smile becomes a mask.",
        "A blue monkey swinging on a branch; a glyph like a poppy-face. Color — blue, direction — west.",
        "игра, иллюзия", "глупость",
        "Чуэн, синяя обезьяна: игра вскрывает иллюзии. Посмейся над собой — то, над чем можно смеяться, перестаёт держать. Обезьяна дразнит, но её дразнилки показывают, где искусственное, а где живое. Карта советует играть искренне: искусство несерьёзности возвращает утраченную ловкость. Перевёрнутая — глупость: игра ради игры, когда улыбка становится маской.",
        "Синяя обезьяна, качающаяся на ветке; глиф в виде макового цветка-лица. Цвет — синий, сторона света — запад.",
    ),
    "S12": (
        "людяність, мудрість", "втеча від людей",
        "Еб, жовта людина: мудрість через досвід. Ділися прожитим — мудрість не закривається в скриню, вона дозріває в передачі. Людина визначається вибором: волю маєш ти, а не обставини. Карта радить памʼятати: бути людяним — означає вміти помилятися й виправлятися. Перевернута — втеча від людей: відлюдництво, що висушує, а не наповнює.",
        "Жовта постать із розставленими руками; гліф, що нагадує передпліччя й кисть. Колір — жовтий, сторона світу — південь.",
        "humanity, wisdom", "fleeing people",
        "Eb, yellow human: wisdom through experience. Share what you lived — wisdom is not locked in a chest, it ripens in the giving. A human is defined by choice: the will is yours, not the circumstances'. The card advises remembering: being humane means being able to err and mend. Reversed — fleeing people: a hermitage that dries out rather than fills.",
        "A yellow figure with outstretched arms; a glyph resembling a forearm and hand. Color — yellow, direction — south.",
        "человечность, мудрость", "бегство от людей",
        "Эб, жёлтый человек: мудрость через опыт. Делись прожитым — мудрость не запирается в сундук, она созревает в передаче. Человека определяет выбор: воля — твоя, а не обстоятельств. Карта советует помнить: быть человечным — значит уметь ошибаться и исправляться. Перевёрнутая — бегство от людей: отшельничество, которое иссушает, а не наполняет.",
        "Жёлтая фигура с распростёртыми руками; глиф, напоминающий предплечье и кисть. Цвет — жёлтый, сторона света — юг.",
    ),
    "S13": (
        "простір, пошук", "блукання",
        "Бен, червоний небесний мандрівник: простір кличе. Вирушай — пошуки не закінчуються знахідкою, вони закінчуються тим, ким ти став дорогою. Мандрівник несе дім у заплічній торбі: йому не страшно пустоти, бо він сам собі опора. Карта радить досліджувати широчінь, не забуваючи про глибину. Перевернута — блукання: рух без мети, за яким не видно стежки.",
        "Червоний мандрівник із ціпком і торбою; гліф, схожий на крок із піднятою ногою. Колір — червоний, сторона світу — схід.",
        "space, quest", "wandering",
        "Ben, red skywalker: space calls. Set out — a quest does not end with a find; it ends with who you became along the way. The traveler carries home in a shoulder bag; the void does not scare him, for he is his own anchor. The card advises exploring the breadth without forgetting the depth. Reversed — wandering: movement without aim, behind which no path is seen.",
        "A red traveler with a staff and bundle; a glyph like a step with a raised leg. Color — red, direction — east.",
        "пространство, поиск", "блуждание",
        "Бен, красный небесный странник: пространство зовёт. Отправляйся — поиск заканчивается не находкой, а тем, кем ты стал в пути. Странник несёт дом в заплечной сумке: пустота ему не страшна, ибо он сам себе опора. Карта советует исследовать ширь, не забывая о глубине. Перевёрнутая — блуждание: движение без цели, за которым не видно тропы.",
        "Красный странник с посохом и сумой; глиф, похожий на шаг с поднятой ногой. Цвет — красный, сторона света — восток.",
    ),
    "S14": (
        "магія, сприйняття", "ілюзії",
        "Іш, білий маг: реальність пластична. Зміни погляд — і зміниться те, що ти бачиш: маг не робить див, він бачить їх. Час і простір — матеріал, а не вʼязниця. Карта радить обернути увагу всередину: чим спокійніший спостерігач, тим покірніший матеріал. Перевернута — ілюзії: маг, що ошукав сам себе, прийнявши видимість за суть.",
        "Білий шлях до храму зі сходів; гліф, схожий на око зі зіницею-вістрям. Колір — білий, сторона світу — північ.",
        "magic, perception", "illusions",
        "Ix, white wizard: reality is plastic. Change your view and what you see changes: the wizard does not make wonders, he sees them. Time and space are material, not a prison. The card advises turning attention inward: the calmer the observer, the more obedient the material. Reversed — illusions: a wizard who fooled himself, taking appearance for essence.",
        "A white stairway-path to a temple; a glyph like an eye with a pupil-point. Color — white, direction — north.",
        "магия, восприятие", "иллюзии",
        "Иш, белый маг: реальность пластична. Измени взгляд — и изменится то, что ты видишь: маг не творит чудес, он их видит. Время и пространство — материал, а не тюрьма. Карта советует обратить внимание внутрь: чем спокойнее наблюдатель, тем послушнее материал. Перевёрнутая — иллюзии: маг, обманувший сам себя, принявший видимость за суть.",
        "Белая лестница-путь к храму; глиф, похожий на глаз со зрачком-остриём. Цвет — белый, сторона света — север.",
    ),
    "S15": (
        "бачення, розум", "короткозорість",
        "Мен, синій орел: погляд з висоти. Побач систему цілком — згори видно, як стежки сходяться до одного центру. Орел не летить у боці справи: він ширяє над нею. Карта радить шукати загальний малюнок подій, а не застрягати в окремій гілці. Перевернута — короткозорість: деталі видно, а карта не читається.",
        "Синій орел із розгорнутими крилами й зором-променем; гліф у вигляді крила. Колір — синій, сторона світу — захід.",
        "vision, mind", "shortsightedness",
        "Men, blue eagle: sight from the heights. See the system whole — from above one sees how the paths converge to one center. The eagle does not flit beside the matter; it soars over it. The card advises seeking the overall pattern of events rather than sticking in a single branch. Reversed — shortsightedness: details are visible, but the map does not read.",
        "A blue eagle with spread wings and a sight-ray; a glyph in the shape of a wing. Color — blue, direction — west.",
        "видение, разум", "близорукость",
        "Мен, синий орёл: взгляд с высоты. Увидь систему целиком — сверху видно, как тропы сходятся к одному центру. Орёл не порхает рядом с делом: он парит над ним. Карта советует искать общий рисунок событий, а не застревать в отдельной ветке. Перевёрнутая — близорукость: детали видны, но карта не читается.",
        "Синий орёл с распахнутыми крыльями и лучом зрения; глиф в виде крыла. Цвет — синий, сторона света — запад.",
    ),
    "S16": (
        "воїн, питання", "боягузтво",
        "Кіб, жовтий воїн: сміливість питати. Постав головне питання — відвага не в тому, щоб не боятися, а в тому, щоб питати попри страх. Сумнів, промовлений уголос, втрачає половину влади. Карта радить протистояти невизначеності запитом, а не мовчанням. Перевернута — боягузтво: питання застрягло в горлі, і ти платиш за мовчанку.",
        "Жовтий щит із гостроверхим гліфом; воїн, що стоїть обличчям до виклику. Колір — жовтий, сторона світу — південь.",
        "warrior, question", "cowardice",
        "Cib, yellow warrior: the courage to ask. Ask the main question — bravery is not about not fearing, but about asking despite the fear. A doubt voiced aloud loses half its hold. The card advises meeting uncertainty with a question, not with silence. Reversed — cowardice: the question stuck in the throat, and you pay for the silence.",
        "A yellow shield with a pointed glyph; a warrior facing the challenge. Color — yellow, direction — south.",
        "воин, вопрос", "трусость",
        "Киб, жёлтый воин: смелость спрашивать. Задай главный вопрос — отвага не в том, чтобы не бояться, а в том, чтобы спрашивать вопреки страху. Сомнение, произнесённое вслух, теряет половину власти. Карта советует встречать неопределённость вопросом, а не молчанием. Перевёрнутая — трусость: вопрос застрял в горле, и ты платишь за молчание.",
        "Жёлтый щит с остроконечным глифом; воин, стоящий лицом к вызову. Цвет — жёлтый, сторона света — юг.",
    ),
    "S17": (
        "земля, синхронність", "землетрус",
        "Кабан, червона земля: знаки синхронні. Зверни увагу на збіги — Всесвіт не пише листів, він залишає прикмети. Земля не поспішає, але все тримає: вона — надійна опора, коли ти з нею згідний. Карта радить дослухатися до ритмів природи й власного сезону. Перевернута — землетрус: те, що будувалося на нечесній основі, ходить ходоромом.",
        "Червона скиба землі з корінням і паростком; гліф, схожий на пошарування ґрунту. Колір — червоний, сторона світу — схід.",
        "earth, synchronicity", "earthquake",
        "Caban, red earth: signs are synchronous. Notice the coincidences — the universe does not write letters; it leaves marks. The earth does not hurry yet holds everything: it is a sure foundation when you agree with it. The card advises listening to the rhythms of nature and your own season. Reversed — an earthquake: what was built on a dishonest base quakes.",
        "A red clod of earth with roots and a sprout; a glyph like layers of soil. Color — red, direction — east.",
        "земля, синхронность", "землетрясение",
        "Кабан, красная земля: знаки синхронны. Обрати внимание на совпадения — Вселенная не пишет писем, она оставляет приметы. Земля не спешит, но всё держит: она — надёжная опора, когда ты с ней согласен. Карта советует прислушиваться к ритмам природы и собственного сезона. Перевёрнутая — землетрясение: то, что строилось на нечестном фундаменте, ходит ходуном.",
        "Красный ком земли с корнями и ростком; глиф, похожий на слои почвы. Цвет — красный, сторона света — восток.",
    ),
    "S18": (
        "дзеркало, правда", "самообман",
        "Ецнаб, біле дзеркало: правда без прикрас. Дивись прямо — відображення не втішає, але воно єдине знає, хто ти. Дзеркало показує й те, що закрито за обличчям: тінь, яку ти відмальовуєш іншим. Карта радить приймати те, що є, як точку відліку для змін. Перевернуте — самообман: дзеркало чесне, а глядач заплющує очі.",
        "Біле дзеркало з овальною рамою; гліф, що нагадує зіницю в двох дзеркалах. Колір — білий, сторона світу — північ.",
        "mirror, truth", "self-deception",
        "Etznab, white mirror: truth without adornment. Look straight — the reflection does not comfort, but it alone knows who you are. The mirror also shows what is hidden behind the face: the shadow you draw for others. The card advises taking what is as the starting point of change. Reversed — self-deception: the mirror is honest, but the beholder closes the eyes.",
        "A white mirror with an oval frame; a glyph like a pupil in twin mirrors. Color — white, direction — north.",
        "зеркало, правда", "самообман",
        "Эцнаб, белое зеркало: правда без прикрас. Смотри прямо — отражение не утешает, но лишь оно знает, кто ты. Зеркало показывает и то, что спрятано за лицом: тень, которую ты рисуешь другим. Карта советует принимать то, что есть, как точку отсчёта перемен. Перевёрнутое — самообман: зеркало честно, а зритель жмурится.",
        "Белое зеркало в овальной раме; глиф, напоминающий зрачок в двух зеркалах. Цвет — белый, сторона света — север.",
    ),
    "S19": (
        "гроза, оновлення", "руйнування",
        "Кауак, синя буря: гроза чистить повітря. Перечекай — гроза не ворог, вона миє світ і тихе слово ясніє після неї. Оновлення не приходить делікатно: воно забирає із собою те, що трималося лише старим дощем. Карта радить не хапатися за те, що вітер ламає, — будуй від нового рівня. Перевернута — руйнування: буря, спрямована всередину, де треба було лишитися під дахом.",
        "Синя хмара з блискавками й краплями; гліф, схожий на вихор дощу. Колір — синій, сторона світу — захід.",
        "storm, renewal", "ruin",
        "Cauac, blue storm: the thunderstorm clears the air. Wait it out — the storm is not an enemy; it washes the world and the quiet word brightens after it. Renewal never comes gently: it takes with it what was held only by old rain. The card advises not to grab at what the wind breaks — build from the new level. Reversed — ruin: a storm turned inward, where one needed to stay under a roof.",
        "A blue cloud with lightning and drops; a glyph like a rain swirl. Color — blue, direction — west.",
        "гроза, обновление", "разрушение",
        "Кауак, синяя буря: гроза чистит воздух. Пережди — гроза не враг, она моет мир, и тихое слово после неё светлее. Обновление не приходит деликатно: оно забирает с собой то, что держалось лишь старым дождём. Карта советует не хвататься за то, что ломает ветер, — строй от нового уровня. Перевёрнутая — разрушение: буря, обращённая внутрь, когда нужно было остаться под крышей.",
        "Синее облако с молниями и каплями; глиф, похожий на вихрь дождя. Цвет — синий, сторона света — запад.",
    ),
    "S20": (
        "сонце, цілісність", "затьмарення",
        "Ахау, жовте сонце: цілісність і просвітлення. Сяй — ти не освітлюєшся ззовні, ти й є світло, якого чекали в кімнаті. Сонце не доводить свого: воно просто встає. Карта радить зібрати розрізнені частини себе в один день і не тримати висновки про себе вчорашні. Перевернуте — затьмарення: світло є, але його заступила тінь невирішеного.",
        "Жовтий сонячний диск із променями; гліф, схожий на квітку з чотирма пелюстками. Колір — жовтий, сторона світу — південь.",
        "sun, wholeness", "eclipse",
        "Ahau, yellow sun: wholeness and enlightenment. Shine — you are not lit from outside; you are the light a room was waiting for. The sun does not prove itself; it simply rises. The card advises gathering the scattered parts of yourself into one day and not keeping yesterday's conclusions about yourself. Reversed — an eclipse: the light is there, overshadowed by the shadow of the unresolved.",
        "A yellow solar disk with rays; a glyph like a four-petaled flower. Color — yellow, direction — south.",
        "солнце, целостность", "затмение",
        "Ахау, жёлтое солнце: целостность и просветление. Сияй — ты не освещаешься извне, ты и есть свет, которого ждала комната. Солнце не доказывает себя: оно просто встаёт. Карта советует собрать разрозненные части себя в один день и не держать вчерашние выводы о себе. Перевёрнутое — затмение: свет есть, но его заслонила тень нерешённого.",
        "Жёлтый солнечный диск с лучами; глиф, похожий на четырёхлепестковый цветок. Цвет — жёлтый, сторона света — юг.",
    ),
    "T01": (
        "магніт, мета", "розпорошення",
        "Тон 1, магнітний: притягни мету. Назви її — початок циклу ставиться словом, а не мовчанкою. Перший тон тягне до себе всі наступні: задай напрямок, і події вишикуються до стрижня. Карта радить визначити мету так, ніби її вже видно з першого кроку. Перевернутий — розпорошення: не назване не магнітиться.",
        "Одна крапка в центрі — ядро і притягання; точковий знак тону на гліфі.",
        "magnet, purpose", "scattering",
        "Tone 1, magnetic: attract the goal. Name it — the start of a cycle is set by a word, not by silence. The first tone pulls all subsequent ones: set the direction and events will line up to the core. The card advises defining the goal as though it were already visible from the first step. Reversed — scattering: the unnamed does not magnetize.",
        "A single dot at the center — core and attraction; the dot sign of the tone on the glyph.",
        "магнит, цель", "рассеивание",
        "Тон 1, магнитный: притяни цель. Назови её — начало цикла ставится словом, а не молчанием. Первый тон притягивает все последующие: задай направление, и события выстроятся к стержню. Карта советует определить цель так, будто она уже видна с первого шага. Перевёрнутый — рассеивание: неназванное не магнитится.",
        "Одна точка в центре — ядро и притяжение; точечный знак тона на глифе.",
    ),
    "T02": (
        "виклик, полярність", "розкол",
        "Тон 2, місячний: виклик розділяє. Обери бік — кожне двосуччя (суперечність) вказує, куди тебе тягне, поки ти не визначився. Місяць зростає й спадає, і життя теж: нестабільність — не прикрість, а матеріал. Карта радить визнати полярність і зробити крок, а не зависнути між берегами. Перевернутий — розкол: те, що не вибрано, розʼїдає зсередини.",
        "Дві крапки — два полюси, що випробовують один одного; знак пари точок.",
        "challenge, polarity", "split",
        "Tone 2, lunar: the challenge divides. Choose a side — every duality shows where you are pulled as long as you are undecided. The moon waxes and wanes, and so does life: instability is not an annoyance but material. The card advises recognizing the polarity and taking a step rather than hovering between banks. Reversed — a split: the unchosen gnaws from within.",
        "Two dots — two poles testing each other; the sign of a pair of dots.",
        "вызов, полярность", "раскол",
        "Тон 2, лунный: вызов разделяет. Выбери сторону — каждая двойственность указывает, куда тебя тянет, пока ты не определился. Луна растёт и убывает, и жизнь тоже: нестабильность — не досада, а материал. Карта советует признать полярность и сделать шаг, а не зависнуть между берегами. Перевёрнутый — раскол: невыбранное разъедает изнутри.",
        "Две точки — два полюса, испытывающие друг друга; знак пары точек.",
    ),
    "T03": (
        "рух, енергія", "апатія",
        "Тон 3, електричний: увімкни струм. Дій — електричний тон не чекає, поки заряд накопичиться; він активує те, що вже є. Потрійність — міра руху: інтерес, дія, результат. Карта радить підключитися до того, що живить, і запустити першу дію сьогодні, а не понеділка. Перевернутий — апатія: провід є, а живлення відімкнено.",
        "Три крапки у вертикальний ряд — струм, що біжить знизу вгору; знак трьох крапок.",
        "motion, energy", "apathy",
        "Tone 3, electric: switch on the current. Act — the electric tone does not wait for the charge to build; it activates what is already there. Threeness is a measure of movement: interest, action, result. The card advises plugging into what nourishes and launching the first action today, not on Monday. Reversed — apathy: the wire is there, but the supply is off.",
        "Three dots in a vertical row — a current running upward; the sign of three dots.",
        "движение, энергия", "апатия",
        "Тон 3, электрический: включи ток. Действуй — электрический тон не ждёт, пока заряд накопится; он активирует то, что уже есть. Тройственность — мера движения: интерес, действие, результат. Карта советует подключиться к тому, что питает, и запустить первое действие сегодня, а не с понедельника. Перевёрнутый — апатия: провод есть, а питание отключено.",
        "Три точки в вертикальный ряд — ток, бегущий снизу вверх; знак трёх точек.",
    ),
    "T04": (
        "форма, міра", "хаос",
        "Тон 4, самосущий: надай форму. Виміряй — четвертий тон будує межі, які не стискають, а тримають. Форма не зраджує змісту: вона показує його межу. Карта радить означити рамки — час, бюджет, обсяг, ролі — інакше безмежне розсиплеться. Перевернутий — хаос: споруда без креслення стоїть на піску.",
        "Чотири крапки по кутах квадрата — стійка форма; знак квадрата з крапок.",
        "form, measure", "chaos",
        "Tone 4, self-existing: give form. Measure — the fourth tone builds boundaries that do not squeeze but hold. Form does not betray content: it shows its limit. The card advises defining frames — time, budget, scope, roles — or the boundless will scatter. Reversed — chaos: a building without a drawing stands on sand.",
        "Four dots at the corners of a square — stable form; the sign of a square of dots.",
        "форма, мера", "хаос",
        "Тон 4, самоосуществляющий: придай форму. Измерь — четвёртый тон строит границы, которые не сжимают, а держат. Форма не предаёт содержание: она показывает его предел. Карта советует определить рамки — время, бюджет, объём, роли — иначе безграничное рассыплется. Перевёрнутый — хаос: здание без чертежа стоит на песке.",
        "Четыре точки по углам квадрата — устойчивая форма; знак квадрата из точек.",
    ),
    "T05": (
        "резонанс, центр", "глухота",
        "Тон 5, обертонний: налаштуйся на центр. Слухай — пʼятий тон випромінює з середини, як звук із натягнутої струни. Обертон — голос, що звучить над основною частотою: твій внесок — те, що чути поверх тла. Карта радить віднайти власний ритм ізсередини, а не підлаштовуватися під чужий гамір. Перевернутий — глухота: резонатор є, а слуху бракує.",
        "Пʼять крапок хрестом із центром — резонанс і середина; знак центральної крапки.",
        "resonance, center", "deafness",
        "Tone 5, overtone: tune to the center. Listen — the fifth tone radiates from the middle, like sound from a taut string. The overtone is a voice sounding above the base frequency: your contribution is what is heard above the background. The card advises finding your own rhythm from within, not matching foreign noise. Reversed — deafness: the resonator is there, but the hearing is missing.",
        "Five dots in a cross with a center — resonance and mid-point; the sign of a central dot.",
        "резонанс, центр", "глухота",
        "Тон 5, обертонный: настройся на центр. Слушай — пятый тон излучает из середины, как звук из натянутой струны. Обертон — голос, звучащий над основной частотой: твой вклад — то, что слышно поверх фона. Карта советует найти собственный ритм изнутри, а не подстраиваться под чужой гам. Перевёрнутый — глухота: резонатор есть, а слуха нет.",
        "Пять точек крестом с центром — резонанс и середина; знак центральной точки.",
    ),
    "T06": (
        "ритм, баланс", "аритмія",
        "Тон 6, ритмічний: знайди свій такт. Шостий тон урівноважує протилежне: роботу й спокій, зусилля й довіру. Ритм — не розклад, а чергування, яке впізнається тілом. Карта радить владнати чергування дня й не стискати життя до одного мазка. Перевернутий — аритмія: серце живе у власному темпі, поки ти біжиш чужим.",
        "Шість крапок двома колонами — баланс лівого й правого; знак двох колон. Ритмічні тон.",
        "rhythm, balance", "arrhythmia",
        "Tone 6, rhythmic: find your beat. The sixth tone balances the opposites: work and rest, effort and trust. Rhythm is not a timetable but a succession recognized by the body. The card advises settling the alternation of the day and not squeezing life into a single stroke. Reversed — arrhythmia: the heart lives at its own tempo while you run at another's.",
        "Six dots in two columns — a balance of left and right; the sign of two columns. Rhythmic tone.",
        "ритм, баланс", "аритмия",
        "Тон 6, ритмичный: найди свой такт. Шестой тон уравновешивает противоположности: работу и отдых, усилие и доверие. Ритм — не расписание, а чередование, узнаваемое телом. Карта советует наладить чередование дня и не сжимать жизнь в один мазок. Перевёрнутый — аритмия: сердце живёт в своём темпе, пока ты бежишь чужим.",
        "Шесть точек двумя колоннами — баланс левого и правого; знак двух колонн. Ритмичный тон.",
    ),
    "T07": (
        "канал, натхнення", "розлад",
        "Тон 7, резонансний: стань каналом. Приймай — сьомий тон передає те, що ширше за тебе: ідею, пісню, рішення, які вибрали тебе провідником. Натхнення — це не твоя сила, а сила, що проходить крізь тебе наскрізь. Карта радить очистити канал від шуму, щоб голос ішов без спотворень. Перевернутий — розлад: канал забитий, і передача йде з перешкодами.",
        "Сім крапок двома колонами й вершиною — канал, що веде вгору; знак 7-ї позиції.",
        "channel, inspiration", "discord",
        "Tone 7, resonant: become a channel. Receive — the seventh tone passes on what is larger than you: an idea, a song, a decision that chose you as a conductor. Inspiration is not your power but a power passing through you. The card advises cleansing the channel of noise so the voice comes undistorted. Reversed — discord: the channel is clogged and the transmission comes with interference.",
        "Seven dots in two columns with a summit — a channel leading upward; the sign of the 7th position.",
        "канал, вдохновение", "разлад",
        "Тон 7, резонансный: стань каналом. Принимай — седьмой тон передаёт то, что шире тебя: идею, песню, решение, выбравшие тебя проводником. Вдохновение — не твоя сила, а сила, проходящая сквозь тебя. Карта советует очистить канал от шума, чтобы голос шёл без искажений. Перевёрнутый — разлад: канал забит, передача идёт с помехами.",
        "Семь точек двумя колоннами с вершиной — канал, ведущий вверх; знак 7-й позиции.",
    ),
    "T08": (
        "цілісність", "фанатизм",
        "Тон 8, галактичний: збери ціле. Інтегруй — восьмий тон складає частини в малюнок, де кожна дістає своє місце й смисл. Гармонія не в тому, щоб згладити кути, а в тому, щоб розташувати їх у загальній симетрії. Карта радить не дорікати собі за відмінності — вони частина фрактала. Перевернутий — фанатизм: одна частина вважає себе цілим.",
        "Вісім крапок по периметру квадрата — цілісна структура; знак рами з крапок.",
        "wholeness", "fanaticism",
        "Tone 8, galactic: gather the whole. Integrate — the eighth tone assembles parts into a pattern where each gains its place and meaning. Harmony is not about smoothing corners but placing them into overall symmetry. The card advises not to reproach yourself for differences — they are part of the fractal. Reversed — fanaticism: one part believes itself to be the whole.",
        "Eight dots along the square's perimeter — an integral structure; the sign of a frame of dots.",
        "целостность", "фанатизм",
        "Тон 8, галактический: собери целое. Интегрируй — восьмой тон складывает части в узор, где каждая получает своё место и смысл. Гармония не в том, чтобы сгладить углы, а в том, чтобы расположить их в общей симметрии. Карта советует не упрекать себя за отличия — они часть фрактала. Перевёрнутый — фанатизм: одна часть мнит себя целым.",
        "Восемь точек по периметру квадрата — целостная структура; знак рамы из точек.",
    ),
    "T09": (
        "намір, пульс", "тінь",
        "Тон 9, сонячний: пульсуй наміром. Випромінюй — девʼятий тон бʼється, як серце: намір стає ритмом, який чути без слів. Сонячний тон не просить уваги — він сам джерело, з якого гріються. Карта радить повторювати намір достатньо довго, щоб він увійшов у кров. Перевернутий — тінь: світло є, але не все потрапляє, куди мало.",
        "Девʼять крапок: дві колони й рядок під ними — пульс, що випромінює; знак 9-ї позиції.",
        "intent, pulse", "shadow",
        "Tone 9, solar: pulse with intent. Radiate — the ninth tone beats like a heart: intent becomes a rhythm heard without words. The solar tone does not ask for attention; it is itself a source from which others warm. The card advises repeating the intent long enough for it to enter the blood. Reversed — shadow: the light is there, but not all of it falls where it should.",
        "Nine dots: two columns and a row below — a radiating pulse; the sign of the 9th position.",
        "намерение, пульс", "тень",
        "Тон 9, солнечный: пульсируй намерением. Излучай — девятый тон бьётся, как сердце: намерение становится ритмом, слышным без слов. Солнечный тон не просит внимания — он сам источник, от которого греются. Карта советует повторять намерение достаточно долго, чтобы оно вошло в кровь. Перевёрнутая — тень: свет есть, но не всё попадает, куда должно.",
        "Девять точек: две колонны и ряд под ними — излучающий пульс; знак 9-й позиции.",
    ),
    "T10": (
        "прояв, досконалість", "ідеалізм",
        "Тон 10, планетарний: прояви у формі. Заверши — десятий тон спускає небо в землю: ідея стає предметом, рядок — книгою, намір — ділом. Досконалість тут — не глянець, а викінченість: доведена справа вже досконала своєю завершеністю. Карта радить додрукувати сторінку, а не правити її вічно. Перевернутий — ідеалізм: зразок у голові завжди кращий за роботу в руках.",
        "Десять крапок двома колонами по пʼять — завершена форма; знак 10-ї позиції.",
        "manifestation, perfection", "idealism",
        "Tone 10, planetary: manifest in form. Complete — the tenth tone brings sky down to earth: an idea becomes an object, a line becomes a book, an intent becomes a deed. Perfection here is not gloss but finish: a completed work is perfect by its completion. The card advises printing the page rather than editing it forever. Reversed — idealism: the sample in the head is always better than the work in the hands.",
        "Ten dots in two columns of five — a completed form; the sign of the 10th position.",
        "проявление, совершенство", "идеализм",
        "Тон 10, планетарный: прояви в форме. Заверши — десятый тон спускает небо на землю: идея становится предметом, строка — книгой, намерение — делом. Совершенство здесь — не глянец, а завершённость: доведённое дело совершенно своим завершением. Карта советует напечатать страницу, а не править её вечно. Перевёрнутый — идеализм: образец в голове всегда лучше работы в руках.",
        "Десять точек двумя колоннами по пять — завершённая форма; знак 10-й позиции.",
    ),
    "T11": (
        "відпускання", "руйнування",
        "Тон 11, спектральний: відпусти зайве. Розчини — одинадцятий тон вібрує на частоті розпаду: те, що відслужило, має повернутися в коло. Спектральний — колір, розкладений на складові: розбираючи пучок, бачиш, з чого він складений. Карта радить позбуватися не смаку, а того, що стало вагою. Перевернутий — руйнування: розчиняти те, що ще мало триматися.",
        "Одинадцять крапок: дві колони й риска — розчинення старого; знак 11-ї позиції.",
        "release", "ruin",
        "Tone 11, spectral: let the excess go. Dissolve — the eleventh tone vibrates at the frequency of decomposition: what has served must return to the circle. Spectral means a color split into components: breaking the beam, you see what it is made of. The card advises discarding not flavor but what has become weight. Reversed — ruin: dissolving what still should hold.",
        "Eleven dots: two columns and a bar — dissolving the old; the sign of the 11th position.",
        "отпускание", "разрушение",
        "Тон 11, спектральный: отпусти лишнее. Раствори — одиннадцатый тон вибрирует на частоте распада: отслужившее должно вернуться в круг. Спектральный — цвет, разложенный на составляющие: разбирая пучок, видишь, из чего он сложен. Карта советует избавляться не от вкуса, а от того, что стало весом. Перевёрнутый — разрушение: растворять то, что ещё должно держаться.",
        "Одиннадцать точек: две колонны и черта — растворение старого; знак 11-й позиции.",
    ),
    "T12": (
        "співпраця", "застій",
        "Тон 12, кристальний: збери коло. Співпрацюй — дванадцятий тон складає окремих у спільне ціле, де всі грані працюють на одне світло. Кристал не ділить світло: він розкладає й знову збирає його. Карта радить діяти не замість інших, а з ними, довіривши їм частину малюнка. Перевернутий — застій: коло не пряде, бо кожен тягне у свій бік.",
        "Дванадцять крапок по контуру — кристалічна решітка; знак сітки.",
        "cooperation", "standstill",
        "Tone 12, crystal: gather the circle. Cooperate — the twelfth tone joins separate ones into a common whole where every facet works for one light. The crystal does not divide light: it splits and reassembles it. The card advises acting not instead of others but with them, entrusting them part of the picture. Reversed — standstill: the wheel does not spin because each pulls their own way.",
        "Twelve dots along the contour — a crystal lattice; the sign of a grid.",
        "сотрудничество", "застой",
        "Тон 12, кристальный: собери круг. Сотрудничай — двенадцатый тон соединяет отдельных в общее целое, где все грани работают на один свет. Кристалл не делит свет: он разлагает и вновь собирает его. Карта советует действовать не вместо других, а с ними, доверив им часть узора. Перевёрнутый — застой: колесо не прядет, потому что каждый тянет в свою сторону.",
        "Двенадцать точек по контуру — кристаллическая решётка; знак сетки.",
    ),
    "T13": (
        "присутність, політ", "втеча вгору",
        "Тон 13, космічний: будь тут. Злети — останній тон замикає цикл і відкриває наступний: присутність у миті стає польотом над часом. Космічний — це те, що не додає, а завершує. Карта радить не тікати в мрію від сьогодення, а довести цикл до кінця, щоб новий почався легким стартом. Перевернутий — втеча вгору: паріння, яке уникає приземлення.",
        "Тринадцять крапок пірамідою — завершення циклу й зліт; знак вершини.",
        "presence, flight", "escape upward",
        "Tone 13, cosmic: be here. Take off — the final tone closes the cycle and opens the next: presence in the moment becomes a flight above time. Cosmic is what does not add but completes. The card advises not fleeing into a dream from the present, but finishing the cycle so the new one starts with an easy lift. Reversed — an escape upward: a soaring that avoids landing.",
        "Thirteen dots in a pyramid — the completion of the cycle and a takeoff; the sign of the summit.",
        "присутствие, полет", "бегство вверх",
        "Тон 13, космический: будь здесь. Взлети — последний тон замыкает цикл и открывает следующий: присутствие в мгновении становится полётом над временем. Космический — это не добавление, а завершение. Карта советует не бежать в мечту от настоящего, а довести цикл до конца, чтобы новый начался лёгким стартом. Перевёрнутый — бегство вверх: парение, избегающее приземления.",
        "Тринадцать точек пирамидой — завершение цикла и взлёт; знак вершины.",
    ),
}


def main():
    p = CARDS_DIR / "tzolkin33.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    cards = {}
    for e in data["cards"]:
        cards.setdefault(e["number"], []).append(e)
    dup = {k for k, v in cards.items() if len(v) > 1}
    assert not dup, f"Дублі номерів: {dup}"
    numbers = {e["number"] for e in data["cards"]}
    missing = numbers ^ set(TZOLKIN.keys())
    assert not missing, f"Розбіжність номерів: {missing}"
    for c in data["cards"]:
        e = TZOLKIN[c["number"]]
        c["keywords_upright"], c["keywords_reversed"] = e[0], e[1]
        c["meaning_general"], c["symbolism"] = e[2], e[3]
        t = c.get("translations", {})
        t.setdefault("en", {}).update({"keywords_upright": e[4], "keywords_reversed": e[5],
                                       "meaning_general": e[6], "symbolism": e[7]})
        t.setdefault("ru", {}).update({"keywords_upright": e[8], "keywords_reversed": e[9],
                                       "meaning_general": e[10], "symbolism": e[11]})
        c["translations"] = t
    p.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    print(f"[OK] tzolkin33.json: {len(data['cards'])} карт збагачено")


if __name__ == "__main__":
    main()