# -*- coding: utf-8 -*-
"""enrich_gypsy.py — збагачення колоди «Циганські карти (deck 11)».
Основна мова — українська; повні переклади en/ru. Традиційні побутові символи
циганської мантичної традиції у власному навчальному викладі.
Формат кожної карти: (kw_u_uk, kw_r_uk, gen_uk, sym_uk, kw_u_en, kw_r_en, gen_en, sym_en,
                      kw_u_ru, kw_r_ru, gen_ru, sym_ru)
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
CARDS_DIR = Path(__file__).resolve().parents[1] / "Database" / "cards"

GYPSY = {
    "1": (
        "кохання, пристрасть", "розлука",
        "Кохання — головна карта серця: сильне почуття, пристрасть або справа, що гріє. Якщо випала — час визнати своє ставлення відверто й берегти стосунок справами, а не тільки словами. У перевернутому вигляді — охолодження чи відстань між серцями.",
        "Серце, з якого рветься полумʼя; палаюча стріла над ним.",
        "love, passion", "separation",
        "Love is the chief card of the heart: strong feeling, passion or a matter that warms. If it appears — time to admit your attitude honestly and tend the bond by deeds, not only words. Reversed — cooling or a distance between hearts.",
        "A heart from which fire bursts; a burning arrow above it.",
        "любовь, страсть", "разлука",
        "Любовь — главная карта сердца: сильное чувство, страсть или дело, что греет. Выпала — пора честно признать своё отношение и беречь связь делами, а не словами. В перевёрнутом виде — охлаждение или расстояние между сердцами.",
        "Сердце, из которого рвётся пламя; горящая стрела над ним.",
    ),
    "2": (
        "вірність, собака", "зрада",
        "Вірність — надійна людина поруч: друг, партнер, той, хто не полишить у біді. Карта радить цінувати перевірених і не підмінювати справжню відданість словами. Перевернута — застереження: нещирість тих, кому довіряв(ла).",
        "Відданий собака біля вогню табору; вірне око, що не відводить погляд.",
        "loyalty, dog", "betrayal",
        "Loyalty is a reliable person nearby: a friend, partner, the one who will not leave in trouble. The card advises valuing the proven and not mistaking words for true devotion. Reversed — a warning of insincerity from those trusted.",
        "A faithful dog by the camp fire; a loyal eye that does not look away.",
        "верность, собака", "измена",
        "Верность — надёжный человек рядом: друг, партнёр, тот, кто не бросит в беде. Карта советует ценить проверенных и не подменять преданность словами. Перевёрнутая — предостережение: неискренность тех, кому доверял(а).",
        "Преданная собака у огня табора; верный глаз, не отводящий взгляд.",
    ),
    "3": (
        "ревнощі, пристрасть", "розрив",
        "Ревнощі — зіниця ока, що затьмарює: сильне почуття стає власницьким. Карта кличе говорити прямо замість стежити, інакше підозри спалять стосунок ізсередини. Перевернута — розрив через недоказану образу.",
        "Око з зіницею-вогнем; зелені нитки, що вʼяжуть дві руки докупи.",
        "jealousy, passion", "break",
        "Jealousy is a pupil that darkens: strong feeling turns possessive. The card calls to speak directly instead of spying, or suspicion will burn the bond from within. Reversed — a break over a proof-less offense.",
        "An eye with a fiery pupil; green threads binding two hands together.",
        "ревность, страсть", "разрыв",
        "Ревность — зрачок, что затмевает: сильное чувство становится собственническим. Карта зовёт говорить прямо, а не следить, иначе подозрения сожгут связь изнутри. Перевёрнутая — разрыв из-за недоказанной обиды.",
        "Глаз с огненным зрачком; зелёные нити, связывающие две руки.",
    ),
    "4": (
        "дорога, рух", "блукання",
        "Дорога — рух і зміни: переїзд, подорож, новий етап, що вже почався. Карта не питає, чи йти, — вона кличе збиратися: шлях відкритий. Перевернута — блукання без мети: час звірити напрямок.",
        "Пилова стежка, що зникає за обрієм; торби на плечі та ціпок у руці.",
        "road, movement", "wandering",
        "The Road is movement and change: relocation, journey, a new stage already begun. The card does not ask whether to go — it calls to pack: the path is open. Reversed — wandering without a goal: time to check the direction.",
        "A dusty path fading beyond the horizon; a bundle on the shoulder and a staff in hand.",
        "дорога, движение", "блуждание",
        "Дорога — движение и перемены: переезд, путешествие, новый этап. Карта не спрашивает, идти ли, — она зовёт собираться: путь открыт. Перевёрнутая — блуждание без цели: пора сверить направление.",
        "Пыльная тропа, уходящая за горизонт; котомка на плече и посох в руке.",
    ),
    "5": (
        "далечінь, табір", "втеча",
        "Далечінь — поїздка вдалину або звістка з чужини: телеграма, гість іздалеку, зміна обставин, що тягне з дому. Карта радить не уникати дороги, але й не тікати від себе. Перевернута — втеча: відірваність від коренів.",
        "Кибитка на горизонті та багаття табору; зоря вечірньої дороги.",
        "distance, camp", "escape",
        "Distance is a far trip or news from abroad: a telegram, a guest from afar, circumstances pulling from home. The card advises not to avoid the road but not to run from yourself either. Reversed — an escape: being torn from roots.",
        "A wagon on the horizon and a camp fire; the star of the evening road.",
        "даль, табор", "бегство",
        "Даль — поездка вдаль или весть из чужой стороны: телеграф, гость издалека, обстоятельства, тянущие из дома. Карта советует не избегать дороги, но и не убегать от себя. Перевёрнутая — бегство: оторванность от корней.",
        "Кибитка на горизонте и огонь табора; звезда вечерней дороги.",
    ),
    "6": (
        "лист, звістка", "погана звістка",
        "Лист — звістка в дорозі: лист, повідомлення, документ, чутка, що відкриє очі. Час чекати гінця й не вірити всьому написаному: перевіряй джерело. Перевернутий — неприємна новина або звістка, якої краще не поспішати поширювати.",
        "Запечатаний конверт із сургучевою печаткою; голуб, що несе згорток.",
        "letter, news", "bad news",
        "The Letter is news on the way: a letter, message, document, rumor that will open eyes. Time to await the messenger and not trust everything written: verify the source. Reversed — unpleasant news or news better not spread quickly.",
        "A sealed envelope with a wax stamp; a dove carrying a parcel.",
        "письмо, весть", "дурная весть",
        "Письмо — весть в пути: письмо, сообщение, документ, слух, открывающий глаза. Пора ждать гонца и не верить всему написанному: проверяй источник. Перевёрнутое — неприятная новость или весть, которую не стоит распространять второпях.",
        "Запечатанный конверт с сургучной печатью; голубь с посылкой.",
    ),
    "7": (
        "гроші, прибуток", "збитки",
        "Гроші — прибуток, що вже дзвенить: дохід, вигідна угода, матеріальне питання на часі. Карта радить рахувати й не тринькати: легкий прибуток любить тверезий розрахунок. Перевернута — збитки через недогляд чи легковажність.",
        "Стопка монет і кований гаманець; підкова над порогом.",
        "money, profit", "losses",
        "Money is profit already ringing: income, a profitable deal, a financial matter at hand. The card advises counting and not squandering: easy money likes sober calculation. Reversed — losses through neglect or carelessness.",
        "A stack of coins and a tooled purse; a horseshoe above the threshold.",
        "деньги, прибыль", "убытки",
        "Деньги — прибыль, что уже звенит: доход, выгодная сделка, материальный вопрос на повестке. Карта советует считать и не транжирить: лёгкая прибыль любит трезвый расчёт. Перевёрнутая — убытки из-за недосмотра или легкомыслия.",
        "Стопка монет и кованый кошелёк; подкова над порогом.",
    ),
    "8": (
        "подарунок, знак", "хабар",
        "Подарунок — приємна несподіванка чи знак уваги: подарунок, сюрприз, жест доброї волі. Карта кличе приймати з вдячністю, але розрізняти щирість і корисливість. Перевернута — підкуп або послуга, що стане боргом.",
        "Коробка зі стрічкою; рука, що дає й рука, що бере.",
        "gift, sign", "bribe",
        "The Gift is a pleasant surprise or a sign of attention: a present, surprise, gesture of goodwill. The card calls to receive with gratitude yet tell sincerity from self-interest. Reversed — a bribe or a favor that becomes a debt.",
        "A box with a ribbon; a hand giving and a hand taking.",
        "подарок, знак", "взятка",
        "Подарок — приятная неожиданность или знак внимания: подарок, сюрприз, жест доброй воли. Карта зовёт принимать с благодарностью, но отличать искренность от корысти. Перевёрнутая — взятка или услуга, оборачивающаяся долгом.",
        "Коробка с лентой; рука, дающая, и рука, берущая.",
    ),
    "9": (
        "дім, родина", "розбрат удома",
        "Дім — тепло родини та затишок: сімʼя, домівка, повернення, місце відновлення. Карта радить навідати рідних і зміцнити те, що тримає разом. Перевернута — розбрат удома: сварка через дрібниці, яку варто зупинити першими.",
        "Хата з димарем і комином; сімейний круг за столом.",
        "home, family", "discord at home",
        "Home is the warmth of the family and coziness: kin, hearth, return, a place of renewal. The card advises visiting relatives and strengthening what holds together. Reversed — discord at home: a quarrel over trifles worth stopping first.",
        "A house with a smoking chimney; a family circle at the table.",
        "дом, семья", "разлад дома",
        "Дом — тепло семьи и уют: родные, очаг, возвращение, место восстановления. Карта советует навестить близких и укрепить то, что держит вместе. Перевёрнутая — разлад дома: ссора из-за мелочей, которую стоит остановить первым.",
        "Дом с дымящей трубой; семейный круг за столом.",
    ),
    "10": (
        "весілля, союз", "скасоване весілля",
        "Весілля — союз і свято: шлюб, обʼєднання сил, домовленість, що закріплюється назавжди. Карта обіцяє радісну подію й кличе готуватися до свята. Перевернута — скасована угода або союз, що розпадається до святкового столу.",
        "Два персні, зʼєднані стрічкою; весільний табір під зорями.",
        "wedding, union", "canceled wedding",
        "Wedding is a union and a celebration: marriage, joining forces, an agreement sealed for good. The card promises a joyful event and calls to prepare for the feast. Reversed — a canceled deal or a union breaking before the feast.",
        "Two rings joined by a ribbon; a wedding camp under the stars.",
        "свадьба, союз", "отменённая свадьба",
        "Свадьба — союз и праздник: брак, объединение сил, договорённость, скреплённая навсегда. Карта обещает радостное событие и зовёт готовиться к празднику. Перевёрнутая — отменённая сделка или союз, распадающийся до праздничного стола.",
        "Два кольца, соединённые лентой; свадебный табор под звёздами.",
    ),
    "11": (
        "дитина, новина", "капризи",
        "Дитина — радісна новина чи початок: маля, звістка про поповнення, нова справа, що потребує турботи. Карта кличе берегти народжене — мрію, проєкт, стосунок. Перевернута — капризи й незрілість: вимагати, не дбаючи.",
        "Колиска з балдахіном; сонце, що сходить над нею.",
        "child, news", "whims",
        "The Child is joyful news or a beginning: a baby, news of an addition, a new affair needing care. The card calls to tend the born — a dream, project, bond. Reversed — whims and immaturity: demanding without caring.",
        "A cradle with a canopy; a rising sun above it.",
        "ребёнок, новость", "капризы",
        "Ребёнок — радостная новость или начало: младенец, весть о пополнении, новое дело, требующее заботы. Карта зовёт беречь рождённое — мечту, проект, отношения. Перевёрнутая — капризы и незрелость: требовать, не заботясь.",
        "Колыбель с балдахином; восходящее солнце над ней.",
    ),
    "12": (
        "нездужання, пауза", "тяжка недуга",
        "Хвороба — нездужання або вимушена пауза: тіло просить перепочинку, справи нагадують про межі сил. Карта радить відлежатися, не геройствувати. Перевернута — затяжна недуга: не відкладай звернення до лікаря.",
        "Ліжко з пологом; свічка, що згасає біля води.",
        "ailment, pause", "grave illness",
        "Illness is an ailment or a forced pause: the body asks for rest, affairs remind of limits. The card advises lying low rather than playing hero. Reversed — a lingering ailment: do not postpone the doctor.",
        "A bed with a canopy; a candle guttering by water.",
        "недомогание, пауза", "тяжкая хвороба",
        "Болезнь — недомогание или вынужденная пауза: тело просит передышки, дела напоминают о пределах сил. Карта советует отлежаться, не геройствовать. Перевёрнутая — затяжной недуг: не откладывай визит к врачу.",
        "Кровать с пологом; свеча, гаснущая у воды.",
    ),
    "13": (
        "ворог, заздрість", "відкрита ворожнеча",
        "Ворог — заздрість чи таємна протидія: хтось недоброзичливий орудує навколо твоєї справи. Карта радить не хвалитися планами й тримати силу при собі. Перевернута — ворожнеча виходить із тіні: готуйся відстоювати своє відкрито.",
        "Ніж у темряві; чорна тінь, що відділяється від стіни табору.",
        "enemy, envy", "open enmity",
        "The Enemy is envy or secret opposition: someone unkind is working around your affair. The card advises not to boast of plans and to keep strength to yourself. Reversed — enmity leaves the shadows: prepare to defend openly.",
        "A knife in the dark; a black shadow detaching from the camp wall.",
        "враг, зависть", "открытая вражда",
        "Враг — зависть или тайное противодействие: кто-то недоброжелательный действует вокруг твоего дела. Карта советует не хвастаться планами и держать силу при себе. Перевёрнутая — вражда выходит из тени: готовься отстаивать своё открыто.",
        "Нож во тьме; чёрная тень, отделяющаяся от стены табора.",
    ),
    "14": (
        "друг, підтримка", "фальшивий друг",
        "Друг — протягнута рука: поруч людина, на яку можна спертися в складний час. Карта кличє приймати допомогу й самому бути надійним плечем. Перевернута — фальшивий друг: слова про дружбу без справ за неї.",
        "Рукостискання над багаттям; дві чаші з одного казана.",
        "friend, support", "false friend",
        "The Friend is an outstretched hand: someone nearby to lean on in hard times. The card calls to accept help and to be a reliable shoulder yourself. Reversed — a false friend: words of friendship without deeds behind them.",
        "A handshake over the fire; two cups from one kettle.",
        "друг, поддержка", "ложный друг",
        "Друг — протянутая рука: рядом человек, на которого можно опереться в трудную минуту. Карта зовёт принимать помощь и самому быть надёжным плечом. Перевёрнутая — ложный друг: слова о дружбе без дел за ними.",
        "Рукопожатие над огнём; две чашки из одного котла.",
    ),
    "15": (
        "удача, шанс", "марна надія",
        "Удача — підкова над дверима: сприятливий знак, шанс, що сам іде в руки. Карта радить діяти, поки фортуна поруч, а не стояти осторонь. Перевернута — марна надія на випадок: удачу викликають рухом, а не очікуванням.",
        "Підкова з сімома дірками; чотирилисник у долоні.",
        "luck, chance", "vain hope",
        "Luck is a horseshoe over the door: a favorable sign, a chance that comes into hands. The card advises acting while fortune is near rather than standing aside. Reversed — vain hope on chance: luck is summoned by movement, not waiting.",
        "A horseshoe with seven holes; a four-leaf clover in the palm.",
        "удача, шанс", "напрасная надежда",
        "Удача — подкова над дверью: благоприятный знак, шанс, идущий в руки. Карта советует действовать, пока фортуна рядом, а не стоять в стороне. Перевёрнутая — напрасная надежда на случай: удача вызывается движением, а не ожиданием.",
        "Подкова с семью дырами; четырёхлистный клевер в ладони.",
    ),
    "16": (
        "перешкода", "біда",
        "Невдача — перешкода на шляху: затримка, розлад планів, складний відрізок. Карта не пророчить катастрофу — вона радить обійти перешкоду, а не ламатись об неї. Перевернута — «біда» на часі: дій обережно, крок за кроком.",
        "Розбитий глек і черепки; камінь поперек стежки.",
        "obstacle", "misfortune",
        "Misfortune is an obstacle on the path: a delay, ruined plans, a hard stretch. The card does not prophesy catastrophe — it advises going around the obstacle rather than breaking on it. Reversed — a 'disaster' at hand: act carefully, step by step.",
        "A broken jug and shards; a stone across the path.",
        "препятствие", "беда",
        "Неудача — препятствие на пути: задержка, расстройство планов, трудный отрезок. Карта не пророчит катастрофу — она советует обойти препятствие, а не разбиться об него. Перевёрнутая — «беда» на подходе: действуй осторожно, шаг за шагом.",
        "Разбитый кувшин и черепки; камень поперёк тропы.",
    ),
    "17": (
        "суд, рішення", "несправедливий вирок",
        "Суд — офіційне рішення: справа, якою займуться сторонні, документ, вирок чи контракт. Карта радить мати порядок у паперах і не плутати розгляд із вироком. Перевернута — несправедливість: готуй докази, не голі слова.",
        "Терези Феміди та меч; суддівський стіл із печаткою.",
        "court, decision", "unjust verdict",
        "Court is an official decision: a matter handled by third parties, a document, verdict or contract. The card advises keeping papers in order and not confusing the process with the sentence. Reversed — injustice: prepare evidence, not bare words.",
        "The scales and sword of justice; a judge's desk with a seal.",
        "суд, решение", "несправедливый приговор",
        "Суд — официальное решение: дело, которым займутся посторонние, документ, приговор или контракт. Карта советует держать бумаги в порядке и не путать разбирательство с приговором. Перевёрнутая — несправедливость: готовь доказательства, а не голые слова.",
        "Весы и меч Фемиды; судейский стол с печатью.",
    ),
    "18": (
        "влада, покровитель", "тиранія",
        "Влада — сильний покровитель або твоя влада: людина при посаді, що може відкрити двері, або ресурс впливу, який ти маєш. Карта радить використовувати вагу обережно й з користю для справи. Перевернута — тиранія: сила, що давить.",
        "Корона на оксамитовій подушці; поважна рука з перснем влади.",
        "power, patron", "tyranny",
        "Power is a strong patron or your own authority: a person in office who can open doors, or leverage you hold. The card advises using weight carefully and for the cause. Reversed — tyranny: force that presses.",
        "A crown on a velvet cushion; a dignified hand with a ring of power.",
        "власть, покровитель", "тирания",
        "Власть — сильный покровитель или твоя власть: человек при должности, способный открыть двери, или влияние, которым ты обладаешь. Карта советует использовать вес осторожно и на пользу делу. Перевёрнутая — тирания: сила, давящая.",
        "Корона на бархатной подушке; важная рука с перстнем власти.",
    ),
    "19": (
        "віра, храм", "ханжество",
        "Церква — віра й традиція: духовні питання, обряди, підтримка спільноти, звернення до вищого. Карта радить спертися на те, у що віриш, і не забувати норми. Перевернута — ханжество: показна побожність без чистоти серця.",
        "Купол із хрестом; свічка, запалена від неба і землі.",
        "faith, temple", "hypocrisy",
        "Church is faith and tradition: spiritual matters, rites, community support, turning to the higher. The card advises leaning on what you believe and not forgetting norms. Reversed — hypocrisy: showy piety without purity of heart.",
        "A dome with a cross; a candle lit from sky and earth.",
        "вера, храм", "ханжество",
        "Церковь — вера и традиция: духовные вопросы, обряды, поддержка общины, обращение к высшему. Карта советует опереться на то, во что веришь, и не забывать нормы. Перевёрнутая — ханжество: показное благочестие без чистоты сердца.",
        "Купол с крестом; свеча, зажжённая от неба и земли.",
    ),
    "20": (
        "свято, гості", "скандал на святі",
        "Свято — гості й веселощі: застілля, зібрання, радісна зустріч, що зміцнює звʼязки. Карта радить приймати запрошення й радіти в компанії. Перевернута — свято, зіпсоване скандалом: хтось прийде зі сваркою, а не з миром.",
        "Накритий стіл і келихи; гілка зі стрічками й бубонцями.",
        "feast, guests", "scandal at the feast",
        "Feast is guests and merriment: a gathering, a joyful encounter that strengthens ties. The card advises accepting invitations and rejoicing in company. Reversed — a feast spoiled by a scandal: someone comes with a quarrel, not peace.",
        "A laid table and glasses; a branch with ribbons and bells.",
        "праздник, гости", "скандал на празднике",
        "Праздник — гости и веселье: застолье, собрание, радостная встреча, укрепляющая связи. Карта советует принимать приглашения и радоваться в компании. Перевёрнутая — праздник, испорченный скандалом: кто-то придёт со ссорой, а не с миром.",
        "Накрытый стол и бокалы; ветвь с лентами и бубенцами.",
    ),
    "21": (
        "сльози, очищення", "горе",
        "Сльози — плач, що очищає: смуток, розчарування, але й звільнення від болю, що ніс у собі. Карта радить не душити сльозу — виплакане відпускає. Перевернута — горе: глибша рана потребує часу й підтримки.",
        "Одна велика сльоза, що падає у воду на світанку.",
        "tears, cleansing", "grief",
        "Tears are a weeping that cleanses: sadness, disappointment, yet release from carried pain. The card advises not to suppress the tear — what is wept lets go. Reversed — grief: a deeper wound needs time and support.",
        "A single large tear falling into water at dawn.",
        "слёзы, очищение", "горе",
        "Слёзы — плач, очищающий: печаль, разочарование, но и освобождение от боли, которую нёс(ла). Карта советует не душить слезу — выплаканное отпускает. Перевёрнутая — горе: глубокая рана требует времени и поддержки.",
        "Одна большая слеза, падающая в воду на рассвете.",
    ),
    "22": (
        "радість, сміх", "коротка радість",
        "Радість — дзвінний сміх: гарний настрій, успіх, легкість, що оновлює. Карта кличє ділитися радістю, аби вона не зітліла наодинці. Перевернута — коротка радість: свято мине, а справу за ним розпочинай зранку.",
        "Бубонці та перламутрові ґудзики, що тремтять від сміху.",
        "joy, laughter", "short joy",
        "Joy is ringing laughter: good mood, success, lightness that renews. The card calls to share joy so it does not smolder alone. Reversed — a short joy: the feast passes, but the work after it begins in the morning.",
        "Bells and mother-of-pearl buttons trembling with laughter.",
        "радость, смех", "короткая радость",
        "Радость — звонкий смех: хорошее настроение, успех, лёгкость, обновляющая. Карта зовёт делиться радостью, чтобы она не тлела в одиночестве. Перевёрнутая — короткая радость: праздник пройдёт, а дело за ним начинай утром.",
        "Бубенцы и перламутровые пуговицы, дрожащие от смеха.",
    ),
    "23": (
        "вогонь, енергія", "пожежа",
        "Вогонь — енергія й пристрасть: запал, що зігріває справу, але може й обпалити. Карта радить грітися, не роздмухуючи зайвого. Перевернутий — пожежа: гнів чи пристрасть вийшли з-під контролю, гаси вчасно.",
        "Багаття з трьох полін; іскри, що піднімаються до зір.",
        "fire, energy", "blaze",
        "Fire is energy and passion: a zeal that warms the affair yet can burn. The card advises warming without fanning too much. Reversed — a blaze: anger or passion got out of control; quench in time.",
        "A fire of three logs; sparks rising to the stars.",
        "огонь, энергия", "пожар",
        "Огонь — энергия и страсть: запал, греющий дело, но способный и обжечь. Карта советует греться, не раздувая лишнего. Перевёрнутый — пожар: гнев или страсть вышли из-под контроля, гаси вовремя.",
        "Костер из трёх поленьев; искры, поднимающиеся к звёздам.",
    ),
    "24": (
        "вода, почуття", "повінь",
        "Вода — почуття й потік життя: емоції несуть, і з течією краще не боротися, а тримати курс. Карта радить гнучкості: там, де сухо — пролий турботу. Перевернута — повінь: почуття затоплюють береги, шукай високе місце.",
        "Річка з плавним бродом; ковш води з джерела у долонях.",
        "water, feelings", "flood",
        "Water is feeling and the flow of life: emotions carry and are better worked with than fought — keep a course. The card advises flexibility: where it is dry, pour care. Reversed — a flood: feelings overwhelm the banks; seek high ground.",
        "A river with a smooth ford; a ladle of spring water in cupped hands.",
        "вода, чувства", "наводнение",
        "Вода — чувства и поток жизни: эмоции несут, и с течением лучше не бороться, а держать курс. Карта советует гибкость: где сухо — пролей заботу. Перевёрнутая — наводнение: чувства заливают берега, ищи возвышенность.",
        "Река с плавным бродом; ковш родниковой воды в ладонях.",
    ),
    "25": (
        "хліб, достаток", "голод",
        "Хліб — достаток і турбота: на столі є що розділити, у домі — тепло. Карта радить радіти простому й ділитися з тими, хто поруч. Перевернутий — голод: брак або страх браку; не роби з турботи про хліб саму турботу.",
        "Паляниця з румʼяною скоринкою; рука, що ламає коровай надвоє.",
        "bread, abundance", "hunger",
        "Bread is abundance and care: there is something to share at the table, and warmth in the house. The card advises rejoicing in the simple and sharing with those near. Reversed — hunger: lack or fear of lack; do not make bread-care the only care.",
        "A round loaf with a ruddy crust; a hand breaking the bread in two.",
        "хлеб, достаток", "голод",
        "Хлеб — достаток и забота: на столе есть чем делиться, в доме тепло. Карта советует радоваться простому и делиться с теми, кто рядом. Перевёрнутый — голод: недостаток или страх недостатка; не делай заботу о хлебе единственной заботой.",
        "Каравай с румяной корочкой; рука, преломляющая хлеб пополам.",
    ),
    "26": (
        "вино, веселощі", "пияцтво",
        "Вино — веселощі в міру: радість, що розкриває серця, тепло розмови. Карта радить пити зі святом, а не від смутку. Перевернуте — пияцтво: втеча в келих; нагадай собі, що веселощі без дна — це не радість.",
        "Повний келих і гроно винограду; крапля, що переливається.",
        "wine, merriment", "drunkenness",
        "Wine is merriment in measure: joy that opens hearts, the warmth of talk. The card advises drinking with celebration, not from sadness. Reversed — drunkenness: escape into the cup; remember that bottomless revelry is not joy.",
        "A full glass and a bunch of grapes; a light-catching drop.",
        "вино, веселье", "пьянство",
        "Вино — веселье в меру: радость, раскрывающая сердца, тепло беседы. Карта советует пить со праздником, а не от печали. Перевёрнутое — пьянство: бегство в бокал; помни, что веселье без дна — не радость.",
        "Полный бокал и гроздь винограда; капля, переливающаяся на свету.",
    ),
    "27": (
        "кінь, швидкість", "втрата коня",
        "Кінь — швидкий рух і витривалість: справа поїде галопом, якщо вміло тримати поводи. Карта радить не збавляти темп, але триматися в сідлі. Перевернутий — втрата коня: швидкість обернеться втратою, якщо забути про управління.",
        "Гарцюючий кінь із гривою на вітрі; пил дороги за копитами.",
        "horse, speed", "loss of the horse",
        "The Horse is swift movement and endurance: the matter will gallop if you hold the reins well. The card advises not to slow the pace but stay seated. Reversed — loss of the horse: speed becomes loss if you forget control.",
        "A prancing horse with a mane in the wind; road dust behind the hooves.",
        "конь, скорость", "потеря коня",
        "Конь — быстрое движение и выносливость: дело пойдёт галопом, если умело держать поводья. Карта советует не сбавлять темп, но держаться в седле. Перевёрнутый — потеря коня: скорость обернётся потерей, если забыть об управлении.",
        "Гарцующий конь с гривой на ветру; дорожная пыль за копытами.",
    ),
    "28": (
        "пташка, звістка", "дурні плітки",
        "Пташка — швидка звістка: звістка, чутка, коротка подорож, легка зміна. Карта радить ловити новину на льоту, поки вона свіжа. Перевернута — дурні плітки: слова, що пурхають безплідно; не давай їм гніздитися.",
        "Сорока або горлиця на тину; пірʼя, кинуте вітром.",
        "bird, news", "idle gossip",
        "The Bird is swift news: a message, rumor, short trip, light change. The card advises catching the news on the wing while fresh. Reversed — idle gossip: words fluttering fruitlessly; do not let them nest.",
        "A magpie or dove on the fence; feathers thrown by the wind.",
        "птица, весть", "пустые сплетни",
        "Птица — быстрая весть: известие, слух, короткая поездка, лёгкая перемена. Карта советует ловить новость на лету, пока свежа. Перевёрнутая — пустые сплетни: слова, порхающие бесплодно; не давай им гнездиться.",
        "Сорока или горлица на плетне; перья, брошенные ветром.",
    ),
    "29": (
        "квітка, ніжність", "зівʼянення",
        "Квітка — ніжність і увага: красивий жест, нова симпатія, цвіт того, що доглядали. Карта радить дарувати турботу без жалю. Перевернута — зівʼянення: без уваги цвіте й чахне; поливай те, що хочеш утримати.",
        "Троянда або ромашка вранішньою росою; бутон і розквітла квітка.",
        "flower, tenderness", "wilting",
        "The Flower is tenderness and attention: a beautiful gesture, new sympathy, the bloom of what was tended. The card advises giving care without regret. Reversed — wilting: without attention it blooms and fades; water what you want to keep.",
        "A rose or daisy in morning dew; a bud and a bloomed flower.",
        "цветок, нежность", "увядание",
        "Цветок — нежность и внимание: красивый жест, новая симпатия, цветение того, что оберегали. Карта советует дарить заботу без сожаления. Перевёрнутый — увядание: без внимания цветёт и чахнет; поливай то, что хочешь удержать.",
        "Роза или ромашка в утренней росе; бутон и распустившийся цветок.",
    ),
    "30": (
        "дзеркало, правда", "самообман",
        "Дзеркало — правда без прикрас: момент чесно поглянути на себе, свій вік і свої справи. Карта радить не відвертатися від відображення. Перевернуте — самообман: дзеркало показує, але око хоче бачити інше.",
        "Половинчасте дзеркало з рукояткою; обличчя, що дивиться вглиб.",
        "mirror, truth", "self-deception",
        "The Mirror is truth without adornment: a moment to honestly view yourself, your age and your affairs. The card advises not to turn away from the reflection. Reversed — self-deception: the mirror shows, but the eye wants to see otherwise.",
        "A hand mirror with a handle; a face looking into the depth.",
        "зеркало, правда", "самообман",
        "Зеркало — правда без прикрас: момент честно посмотреть на себя, свой возраст и свои дела. Карта советует не отворачиваться от отражения. Перевёрнутое — самообман: зеркало показывает, но глаз хочет видеть иное.",
        "Ручное зеркало с рукояткой; лицо, глядящее вглубь.",
    ),
    "31": (
        "ключ, рішення", "замкнені двері",
        "Ключ — вихід знайдено: рішення, доступ, розгадка, що відкриває зачинені двері. Карта радить повернути ключ, а не чекати, що двері відчиняться самі. Перевернутий — замкнені двері: потрібен інший ключ або інший шлях.",
        "Кований ключ із різьбленим вухом; замок, що чекає повороту.",
        "key, solution", "locked doors",
        "The Key is a found exit: a solution, access, an answer opening closed doors. The card advises turning the key rather than waiting for the door to open itself. Reversed — locked doors: another key or another path is needed.",
        "A wrought key with a carved bow; a lock awaiting a turn.",
        "ключ, решение", "запертые двери",
        "Ключ — найден выход: решение, доступ, разгадка, открывающая закрытые двери. Карта советует повернуть ключ, а не ждать, что дверь откроется сама. Перевёрнутый — запертые двери: нужен другой ключ или другой путь.",
        "Кованый ключ с резным ушком; замок, ждущий поворота.",
    ),
    "32": (
        "замок, таємниця", "пастка",
        "Замок — таємниця під охороною: щось приховане навмисно, чиїсь справи за зачином. Карта радить не ламати захист чужого, а й свій берегти. Перевернутий — пастка: те, що зачинили, може зачинити й тебе.",
        "Важкий замок на дверях; тінь, що крадеться до щілини.",
        "lock, secret", "trap",
        "The Lock is a secret under protection: something deliberately hidden, someone's affairs behind a bolt. The card advises not to break another's protection — and to keep your own. Reversed — a trap: what was locked may lock you too.",
        "A heavy lock on the door; a shadow creeping toward the crack.",
        "замок, тайна", "ловушка",
        "Замок — тайна под охраной: что-то намеренно скрытое, чьи-то дела за засовом. Карта советует не ломать чужую защиту — и свою беречь. Перевёрнутый — ловушка: то, что заперли, может запереть и тебя.",
        "Тяжёлый замок на двери; тень, крадущаяся к щели.",
    ),
    "33": (
        "сонце, успіх", "спека",
        "Сонце — успіх і ясність: картина прояснюється, справи виходять на світло. Карта радить користуватися днем: сонячний час гріє всіх рівно, але встає для того, хто встав. Перевернуте — спека: надлишок вимагає тіні.",
        "Сонце в зеніті з променями-стрілами; підсмажене поле.",
        "sun, success", "heat",
        "The Sun is success and clarity: the picture clears, affairs come to light. The card advises using the day: sunshine warms everyone equally, but rises for the one who rose. Reversed — heat: excess calls for shade.",
        "The sun at zenith with darting rays; a sun-baked field.",
        "солнце, успех", "жара",
        "Солнце — успех и ясность: картина проясняется, дела выходят на свет. Карта советует пользоваться днём: солнце греет всех поровну, но встаёт для того, кто встал. Перевёрнутое — жара: избыток требует тени.",
        "Солнце в зените с лучами-стрелами; полдень над полем.",
    ),
    "34": (
        "місяць, сни", "безсоння",
        "Місяць — сни й приховане: нічні думки, віщі сни, зміна настроїв. Карта радить прислухатися до того, що приходить уночі, і запамʼятовувати. Перевернутий — безсоння: тривога не дає спати; випиши думки на папір.",
        "Місяць над дахом з повними віконницями; тінь місячної доріжки.",
        "moon, dreams", "sleeplessness",
        "The Moon is dreams and the hidden: night thoughts, prophetic dreams, changes of mood. The card advises listening to what comes at night and remembering it. Reversed — sleeplessness: anxiety keeps you awake; write thoughts on paper.",
        "The moon over a roof with shuttered windows; a shadow of the moon-path.",
        "луна, сны", "бессонница",
        "Луна — сны и скрытое: ночные мысли, вещие сны, перемена настроений. Карта советует прислушиваться к тому, что приходит ночью, и запоминать. Перевёрнутая — бессонница: тревога не даёт спать; выпиши мысли на бумагу.",
        "Луна над крышей с закрытыми ставнями; тень лунной дорожки.",
    ),
    "35": (
        "зірка, надія", "падіння зірки",
        "Зірка — надія, що не гасне: удача на шляху, здійсненне бажання, світло в темряві. Карта радить загадати бажання й не випускати мрію з поля зору. Перевернута — падіння зірки: надія згасла, але це не кінець неба.",
        "Велика зірка серед дрібних; дівчина з кухлем, що ловить світло.",
        "star, hope", "falling star",
        "The Star is an unfading hope: luck on the way, a fulfillable wish, light in the dark. The card advises making a wish and keeping the dream in sight. Reversed — a falling star: hope faded, but that is not the end of the sky.",
        "A large star among small ones; a girl with a jug catching light.",
        "звезда, надежда", "падение звезды",
        "Звезда — негаснущая надежда: удача в пути, исполнимое желание, свет во тьме. Карта советует загадать желание и не выпускать мечту из виду. Перевёрнутая — падение звезды: надежда угасла, но это не конец неба.",
        "Большая звезда среди малых; девушка с кувшином, ловящая свет.",
    ),
    "36": (
        "хрест, доля", "тяжкий хрест",
        "Хрест — випробування долі: ноша, яку не обирають, але яку можна нести по-своєму. Карта не пророчить краху — вона радить не скидати хрест, а знайти спосіб іти з ним рівно. Перевернутий — тяжкий хрест: час перерозподілити ношу й просити допомоги.",
        "Хрест на роздоріжжі; подорожній, що опирається на ціпок.",
        "cross, fate", "heavy cross",
        "The Cross is a trial of fate: a burden one does not choose, yet can carry one's own way. The card does not prophesy ruin — it advises not to throw off the cross but to find a level way with it. Reversed — a heavy cross: time to redistribute the load and ask for help.",
        "A cross at a crossroads; a traveler leaning on a staff.",
        "крест, судьба", "тяжкий крест",
        "Крест — испытание судьбы: ноша, которую не выбирают, но можно нести по-своему. Карта не пророчит краха — она советует не скидывать крест, а найти способ идти с ним ровно. Перевёрнутый — тяжкий крест: пора перераспределить груз и просить помощи.",
        "Крест на распутье; путник, опирающийся на посох.",
    ),
}


def main():
    p = CARDS_DIR / "gypsy36.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    missing = [c["number"] for c in data["cards"] if c["number"] not in GYPSY]
    assert not missing, f"Нема опису для: {missing}"
    for c in data["cards"]:
        e = GYPSY[c["number"]]
        c["keywords_upright"], c["keywords_reversed"] = e[0], e[1]
        c["meaning_general"], c["symbolism"] = e[2], e[3]
        t = c.get("translations", {})
        t["en"].update({"keywords_upright": e[4], "keywords_reversed": e[5],
                        "meaning_general": e[6], "symbolism": e[7]})
        t["ru"].update({"keywords_upright": e[8], "keywords_reversed": e[9],
                        "meaning_general": e[10], "symbolism": e[11]})
        c["translations"] = t
    p.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    print(f"[OK] gypsy36.json: {len(data['cards'])} карт збагачено")


if __name__ == "__main__":
    main()