# -*- coding: utf-8 -*-
"""enrich_playing.py — збагачення колоди «Гральні карти 36 (deck 12)».
Основна мова — українська; повні переклади en/ru. Традиційні словʼянські значення
у власному навчальному викладі. Формат кожної карти:
 (kw_u_uk, kw_r_uk, gen_uk, sym_uk, kw_u_en, kw_r_en, gen_en, sym_en, kw_u_ru, kw_r_ru, gen_ru, sym_ru)
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
CARDS_DIR = Path(__file__).resolve().parents[1] / "Database" / "cards"

PLAYING = {
    "H-A": (
        "дім, любов, звістка", "розбите серце",
        "Туз чирва — найсильніша карта сфери почуттів: дім, сердечні справи й добра звістка про кохання. Якщо випав — чекай знаку від близької людини або зміцнення домашнього вогнища. У розкладі про справи карта радить читати між рядків, а не буквально.",
        "Велике серце з краплями-сльозою або краплею крові; золоте тло дому.",
        "home, love, news", "broken heart",
        "The Ace of Hearts is the strongest card of the sphere of feelings: home, love affairs and good news about love. It promises a sign from a loved one or a stronger hearth. In matters, read between the lines, not literally.",
        "A large heart with a drop; golden background of the home.",
        "дом, любовь, весть", "разбитое сердце",
        "Туз червей — сильнейшая карта сферы чувств: дом, сердечные дела и добрая весть о любви. Жди знака от близкого человека или укрепления домашнего очага. В делах читай между строк, а не буквально.",
        "Большое сердце с каплей; золотой фон дома.",
    ),
    "D-A": (
        "гроші, лист", "втрата грошей",
        "Туз бубна — карта грошей і паперів: документи, квитанції, листи, що стосуються фінансів. Обіцяє прибуток, але закликає читати дрібний шрифт — підписуй угоди лише після перевірки. Часто вказує на несподіваний грошовий рух.",
        "Блискуча монета з карбованим знаком; конверт із печаткою.",
        "money, letter", "loss of money",
        "The Ace of Diamonds is the card of money and papers: documents, receipts, letters about finances. It promises profit but calls to read the fine print — sign agreements only after checking. Often points to an unexpected flow of money.",
        "A shiny coin with a stamped sign; a sealed envelope.",
        "деньги, письмо", "потеря денег",
        "Туз бубен — карта денег и бумаг: документы, квитанции, письма о финансах. Обещает прибыль, но велит читать мелкий шрифт — подписывай соглашения только после проверки. Часто указывает на неожиданное денежное движение.",
        "Блестящая монета со знаком; конверт с печатью.",
    ),
    "C-A": (
        "справа, казенний дім", "порожні клопоти",
        "Туз трефа — карта служби й офіційних справ: державні установи, робота, організації, що «штампують» рішення. Папери почнуть рухатися, але не поспішай — чиновницька машина повільна. Успіх залежить від терпіння й формальностей.",
        "Великий трилисник; друкована печатка (штамп) установи.",
        "business, official house", "empty chores",
        "The Ace of Clubs is the card of service and official affairs: state institutions, work, organizations 'stamping' decisions. Papers will move, but do not rush — the bureaucratic machine is slow. Success depends on patience and formalities.",
        "A large trefoil; an official seal of an institution.",
        "дело, казённый дом", "пустые хлопоты",
        "Туз треф — карта службы и официальных дел: госучреждения, работа, организации, «штампующие» решения. Бумаги начнут двигаться, но не спеши — бюрократическая машина медленна. Успех зависит от терпения и формальностей.",
        "Большой трилистник; официальная печать учреждения.",
    ),
    "S-A": (
        "удар, нічна звістка", "важкий удар",
        "Туз піка — карта удару та пізньої, часто неприємної звістки: гострі питання, раптові події, дізнавання правди. Напрям вістря має значення: вгору — несподіваність, вниз — значне веселощі або «відбій тривоги». Не панікуй: удар вирішує загострена ситуація.",
        "Вістря з чорним наконечником, спрямоване вгору або вниз; пікова масть.",
        "blow, night news", "heavy blow",
        "The Ace of Spades is the card of a blow and late, often unpleasant news: sharp questions, sudden events, learning the truth. The direction of the point matters: up — surprise, down — big celebration or 'all clear'. Do not panic: crisis heightens the situation.",
        "A point with a black tip aimed up or down; the spade suit.",
        "удар, ночная весть", "тяжёлый удар",
        "Туз пик — карта удара и поздней, часто неприятной вести: острые вопросы, внезапные события, узнавание правды. Направление острия важно: вверх — неожиданность, вниз — большое веселье. Не паникуй: обострение решает ситуацию.",
        "Остриё с чёрным наконечником вверх или вниз; пиковая масть.",
    ),
    "H-K": (
        "коханий, гість", "невірність",
        "Король чирва — дорослий щирий чоловік: коханий, чоловік, батько або приємний гість із добрими намірами. У розкладі про стосунки — сама людина, про яку запитують. Перевернутий — остережно: чоловік може бути нещирим.",
        "Червоний король у кроні; серце на грудях як знак щирості.",
        "beloved, guest", "infidelity",
        "The King of Hearts is a sincere grown man: a beloved, husband, father or a pleasant guest with good intentions. In love spreads it is the person asked about. Reversed — caution: the man may be insincere.",
        "Red king in a crown; a heart on the chest as a sign of sincerity.",
        "возлюбленный, гость", "неверность",
        "Король червей — искренний взрослый мужчина: возлюбленный, муж, отец или приятный гость. В раскладе о любви — сам человек, о котором спрашивают. Перевёрнутый — осторожно: мужчина может быть неискренним.",
        "Красный король в короне; сердце на груди как знак искренности.",
    ),
    "D-K": (
        "молодий чоловік, військовий", "шахрай",
        "Король бубна — молодий або безтурботний чоловік: неодружений, військовий, чиновник у «дрібних» справах. Справи з ним рухаються швидко, але без глибини. Перевернутий застерігає від шахрая — не позичай і не підписуй на сполох.",
        "Червоно-золотий король; монета замість серця — світськість.",
        "young man, military", "fraudster",
        "The King of Diamonds is a young or carefree man: unmarried, a military man, an official in 'small' matters. Affairs with him move fast but shallow. Reversed warns of a fraudster — do not lend money or sign in haste.",
        "Red-and-gold king; a coin instead of a heart — worldliness.",
        "молодой человек, военный", "мошенник",
        "Король бубен — молодой или беспечный мужчина: холост, военный, чиновник по «мелким» делам. Дела с ним идут быстро, но неглубоко. Перевёрнутый предостерегает от мошенника — не одолживай и не подписывай сгоряча.",
        "Красно-золотой король; монета вместо сердца — светскость.",
    ),
    "C-K": (
        "начальник, батько", "несправедливий начальник",
        "Король трефа — старший чоловік із владою: начальник, батько, керівник, людина в погонах. Уособлює правила й ієрархію: поважай статус, але захищай свої межі. Перевернутий — начальник, який зловживає повноваженнями.",
        "Чорний король із трилисником; знак влади над справою.",
        "boss, father", "unfair boss",
        "The King of Clubs is an elder man with authority: a boss, father, manager, a person in uniform. Embodies rules and hierarchy: respect status but protect your boundaries. Reversed — a boss abusing his power.",
        "Black king with a trefoil; sign of power over business.",
        "начальник, отец", "несправедливый начальник",
        "Король треф — старший мужчина с властью: начальник, отец, руководитель, человек в форме. Воплощает правила и иерархию: уважай статус, но защищай свои границы. Перевёрнутый — начальник, злоупотребляющий полномочиями.",
        "Чёрный король с трилистником; знак власти над делом.",
    ),
    "S-K": (
        "казенна людина, суперник", "ворог",
        "Король піка — поважний, але холодний чоловік: чиновник, суддя, суперник або ворог у шапці влади. Не обовʼязково злий — але такий, що керується інтересом, а не почуттям. Тримай дистанцію й документи в порядку: перевернутий — відвертий ворог.",
        "Чорний король із пікою-вістрям; суворий, неприступний погляд.",
        "official, rival", "enemy",
        "The King of Spades is a respectable but cold man: an official, judge, rival or enemy with authority. Not necessarily evil, but guided by interest rather than feeling. Keep distance and documents in order; reversed — an open enemy.",
        "Black king with a spade point; a stern, unapproachable look.",
        "казённый человек, соперник", "враг",
        "Король пик — солидный, но холодный мужчина: чиновник, судья, соперник или враг. Не обязательно злой, но руководствуется интересом, а не чувством. Держи дистанцию; перевёрнутый — открытый враг.",
        "Чёрный король с остриём; суровый, неприступный взгляд.",
    ),
    "H-Q": (
        "кохана, подруга", "суперниця",
        "Дама чирва — щира зріла жінка: кохана, дружина, подруга, мати з теплим серцем. У розкладах про кохання — саме та жінка, про яку запитують, або підтримка з жіночого боку. Перевернута — суперниця або ревнощі.",
        "Червона дама; серце в руці — щедрість почуттів.",
        "beloved, friend", "rival",
        "The Queen of Hearts is a sincere mature woman: a beloved, wife, friend, mother with a warm heart. In love spreads she is the woman asked about, or support from the feminine side. Reversed — a rival or jealousy.",
        "Red queen; a heart in hand — generosity of feeling.",
        "возлюбленная, подруга", "соперница",
        "Дама червей — искренняя зрелая женщина: возлюбленная, жена, подруга, мать с тёплым сердцем. В раскладах о любви — сама женщина, о которой спрашивают. Перевёрнутая — соперница или ревность.",
        "Красная дама; сердце в руке — щедрость чувств.",
    ),
    "D-Q": (
        "молода жінка, подруга", "пліткарка",
        "Дама бубна — молода, жвава жінка: подруга, сестра, колега, яка любить світське життя. Вона на боці запитувача, але легковажна у словах. Перевернута — пліткарка або жінка, що грає на інтерес, а не на почутті.",
        "Золота дама; брязкіт монет — товариськість і легкість.",
        "young woman, friend", "gossip",
        "The Queen of Diamonds is a young, lively woman: a friend, sister, colleague who loves social life. She is on the querent's side but careless in words. Reversed — a gossip or a woman playing on interest, not feeling.",
        "Golden queen; the clink of coins — sociability and lightness.",
        "молодая женщина, подруга", "сплетница",
        "Дама бубен — молодая, оживлённая женщина: подруга, сестра, коллега, любящая светскую жизнь. Она на стороне спрашивающего, но легкомысленна в словах. Перевёрнутая — сплетница или женщина, играющая на интересе.",
        "Золотая дама; звон монет — общительность и лёгкость.",
    ),
    "C-Q": (
        "мати, колега", "інтриганка",
        "Дама трефа — ділова або старша жінка: мати, наставниця, колега, яка знає ціну словам. Стоїть за справою, а не за емоцією — звертайся до неї за діловою порадою. Перевернута — інтриганка, що плете в організаціях.",
        "Чорна дама з трилисником; скромний, діловий убір.",
        "mother, colleague", "schemer",
        "The Queen of Clubs is a business or elder woman: a mother, mentor, colleague who knows the price of words. Stands behind business, not emotion — ask her for professional advice. Reversed — a schemer weaving intrigues in organizations.",
        "Black queen with a trefoil; modest, businesslike attire.",
        "мать, коллега", "интриганка",
        "Дама треф — деловая или старшая женщина: мать, наставница, коллега, знающая цену словам. Стоит за делом, а не за эмоцией. Перевёрнутая — интриганка, плетущая в организациях.",
        "Чёрная дама с трилистником; скромный деловой наряд.",
    ),
    "S-Q": (
        "вдова, зла жінка", "відьма",
        "Дама піка — жінка з досвідом втрат: вдова, самотня, сувора або та, що довго несе образу. Може бути найближчою помічницею, але її мова гостра. Перевернута — «відьма» в побутовому сенсі: людина злих слів; тримайся дистанції.",
        "Чорна дама; чорна серпанкова хустка — знак жалоби й досвіду.",
        "widow, harsh woman", "witch",
        "The Queen of Spades is a woman with experience of loss: a widow, solitary, stern, or one who long carries an offense. She can be a close helper, but her tongue is sharp. Reversed — a 'witch' in the everyday sense: keep distance.",
        "Black queen; a dark veil — a sign of mourning and experience.",
        "вдова, злая женщина", "ведьма",
        "Дама пик — женщина с опытом потерь: вдова, одинокая, строгая или долго несущая обиду. Может быть близкой помощницей, но язык у неё острый. Перевёрнутая — «ведьма» в бытовом смысле; держись на расстоянии.",
        "Чёрная дама; тёмная вуаль — знак траура и опыта.",
    ),
    "H-J": (
        "думки коханого", "порожні мрії",
        "Валет чирва — думки й наміри коханого, «гонець» почуттів: молода людина, яка зробить крок до зближення. Пряма карта про дружбу й відверті розмови. Перевернута — мрійник, що не переходить до слів.",
        "Червоний паж; серце на грудях, перо в руці — лист почуттів.",
        "thoughts of the beloved", "empty dreams",
        "The Jack of Hearts is the thoughts and intentions of the beloved, a 'messenger' of feelings: a young person who will make a step closer. Upright — friendship and open talk. Reversed — a dreamer who never speaks up.",
        "Red page; a heart on the chest, a pen in hand — a letter of feelings.",
        "мысли возлюбленного", "пустые мечты",
        "Валет червей — мысли и намерения возлюбленного, «гонец» чувств: молодой человек, который сделает шаг к сближению. Прямой — дружба и откровенные разговоры. Перевёрнутый — мечтатель, не переходящий к словам.",
        "Красный паж; сердце на груди, перо в руке — письмо чувств.",
    ),
    "D-J": (
        "гонець, клопоти", "поганий гонець",
        "Валет бубна — гонець із дорученням і дрібні клопоти: молода людина, яка принесе звістку або виконає службу. Справи тривожні, але неглибокі — швидко проходять. Перевернутий — ненадійний вісник: перевіряй інформацію.",
        "Паж із монетою в стислій долоні; швидкі кроки біля дверей.",
        "messenger, chores", "bad messenger",
        "The Jack of Diamonds is a messenger with an errand and small chores: a young person bringing news or performing a service. The matters are fussy but shallow — they pass quickly. Reversed — an unreliable bearer: verify information.",
        "A page with a coin in a closed palm; quick steps near the door.",
        "гонец, хлопоты", "плохой гонец",
        "Валет бубен — гонец с поручением и мелкие хлопоты: молодой человек с вестью или службой. Дела суетливы, но неглубоки. Перевёрнутый — ненадёжный вестник: проверяй информацию.",
        "Паж с монетой в сжатой ладони; быстрые шаги у двери.",
    ),
    "C-J": (
        "військовий, успіх", "невдача в справі",
        "Валет трефа — молодий службовець або військовий: людина у формі, курʼєр, помічник. У справах обіцяє успіх через працю й дисциплінованість. Перевернутий — невдача в казенній справі, марні зусилля.",
        "Паж у мундирі; трилисник і ремінь — службовий обовʼязок.",
        "military, success", "failure in business",
        "The Jack of Clubs is a young servant or a soldier: a person in uniform, courier, helper. In affairs promises success through work and discipline. Reversed — failure in official matters, wasted effort.",
        "A page in uniform; a trefoil and a belt — service duty.",
        "военный, успех", "неудача в деле",
        "Валет треф — молодой служащий или военный: человек в форме, курьер, помощник. В делах обещает успех через труд и дисциплину. Перевёрнутый — неудача в казённом деле, напрасные усилия.",
        "Паж в мундире; трилистник и ремень — служебный долг.",
    ),
    "S-J": (
        "порожні клопоти", "плітки, бійка",
        "Валет піка — порожні клопоти та плітки: молода людина, що «галасує» більше, ніж робить. Не кожному слову вір — за чутками стоїть дрібний інтерес. Перевернутий — сварка або бійка через язика.",
        "Паж із пікою; темна полуда обличчя — інтрига й тиск.",
        "empty chores", "gossip, fight",
        "The Jack of Spades is empty chores and gossip: a young person who 'noises' more than acts. Do not trust every word — petty interest stands behind rumors. Reversed — a quarrel or a fight caused by the tongue.",
        "A page with a spade; a dark shadow on the face — intrigue and pressure.",
        "пустые хлопоты", "сплетни, драка",
        "Валет пик — пустые хлопоты и сплетни: молодой человек, который «шумит» больше, чем делает. Не всякому слову верь. Перевёрнутый — ссора или драка из-за языка.",
        "Паж с пикой; тёмная тень на лице — интрига и давление.",
    ),
    "H-10": (
        "радість, весілля", "розчарування",
        "Десятка чирва — радість і повне серце: весілля, свято, здійснення бажання в сфері почуттів. Одна з найкращих карт для кохання. Перевернута — тимчасове розчарування, не давай йому стати вироком.",
        "Десять сердець, нанизаних на вінок квітів; хоровод радості.",
        "joy, wedding", "disappointment",
        "The Ten of Hearts is joy and a full heart: a wedding, celebration, fulfillment of wish in love. One of the best cards for love. Reversed — temporary disappointment, do not let it become a verdict.",
        "Ten hearts strung on a wreath of flowers; a round dance of joy.",
        "радость, свадьба", "разочарование",
        "Десятка червей — радость и полное сердце: свадьба, праздник, исполнение желания в любви. Одна из лучших карт для чувств. Перевёрнутая — временное разочарование, не делай из него приговор.",
        "Десять сердец на венке цветов; хоровод радости.",
    ),
    "D-10": (
        "гроші, поїздка", "втрата грошей",
        "Десятка бубна — грошовий успіх і недалека поїздка: отримання, вигідна угода, дорога заради справи. Деньги люблять рух — вкладай, а не ховай. Перевернута — ризик втрат через поспіх у фінансах.",
        "Десять монет розсипом; колісниця на шляху — близька дорога.",
        "money, trip", "loss of money",
        "The Ten of Diamonds is financial success and a short trip: a receipt, a profitable deal, a road for business. Money loves motion — invest rather than hide. Reversed — risk of loss through haste in finances.",
        "Ten coins scattered; a cart on the road — a near journey.",
        "деньги, поездка", "потеря денег",
        "Десятка бубен — денежный успех и недальняя поездка: получение, выгодная сделка, дорога ради дела. Деньги любят движение — вкладывай, не прячь. Перевёрнутая — риск потерь из-за спешки.",
        "Десять монет россыпью; повозка на пути — близкая дорога.",
    ),
    "C-10": (
        "гроші, справа", "борги",
        "Десятка трефа — великі гроші в діловій сфері: прибуток від справи, успіх у роботі, вигода в офіційних угодах. Добре для карʼєри, акуратно для позик. Перевернута — борги й обтяжливі зобовʼязання.",
        "Десять трилисників у колі; каса або стіл державної установи.",
        "money, business", "debts",
        "The Ten of Clubs is large money in the business sphere: profit from a venture, success at work, gain in official deals. Good for career, careful with loans. Reversed — debts and burdensome obligations.",
        "Ten trefoils in a circle; a cash-desk or office table.",
        "деньги, дело", "долги",
        "Десятка треф — большие деньги в деловой сфере: прибыль от дела, успех в работе, выгода в официальных сделках. Хороша для карьеры, осторожно с займами. Перевёрнутая — долги и обременительные обязательства.",
        "Десять трилистников в круге; касса или конторский стол.",
    ),
    "S-10": (
        "інтерес, ліжко", "хвороба",
        "Десятка піка — глибокий інтерес або хвороба: те, що «лягає» на людину — сильна пристрасть чи недуга. Пряма вказує на ніч, таємницю, зближення. Перевернута — застереження про здоровʼя: не відкладай візит до лікаря.",
        "Десять пік, нанизаних на вістря; темне ложе під пологом.",
        "interest, bed", "illness",
        "The Ten of Spades is deep interest or illness: what 'lies' on a person — strong passion or ailment. Upright it points to night, secrecy, closeness. Reversed — a warning about health: do not postpone the doctor.",
        "Ten spades strung on a point; a dark bed under a canopy.",
        "интерес, постель", "болезнь",
        "Десятка пик — глубокий интерес или болезнь: то, что «лягает» на человека — сильная страсть или недуг. Прямая указывает на ночь, тайну, сближение. Перевёрнутая — предупреждение о здоровье: не откладывай визит к врачу.",
        "Десять пик на острие; тёмное ложе под пологом.",
    ),
    "H-9": (
        "кохання, місто", "нерозділене кохання",
        "Девʼятка чирва — взаємне кохання та близькість: зустріч у місті, тепла розмова, радість від присутності коханої людини. Певна — у справах серця супутня удача. Перевернута — нерозділене почуття або самота вдвох.",
        "Девʼять сердець; вежі міста й фіранки — зустріч із близьким.",
        "love, city", "unrequited love",
        "The Nine of Hearts is mutual love and closeness: a meeting in the city, a warm talk, joy from the beloved's presence. Definite — favorable companion in heart matters. Reversed — unrequited feeling or loneliness together.",
        "Nine hearts; city towers and curtains — a meeting with a loved one.",
        "любовь, город", "неразделённая любовь",
        "Девятка червей — взаимная любовь и близость: встреча в городе, тёплый разговор, радость от присутствия любимого. Верная — спутница удачи в сердечных делах. Перевёрнутая — неразделённое чувство или одиночество вдвоём.",
        "Девять сердец; башни города и занавеси — встреча с близким.",
    ),
    "D-9": (
        "гроші, незалежність", "невдача",
        "Девʼятка бубна — гроші, зароблені власними руками: незалежність, смілива фінансова ініціатива, успіх у справах без чужої опіки. Час діяти самостійно. Перевернута — та сама воля, але без розрахунку: перевіряй цифри.",
        "Девʼять монет у руці; працьовита долоня без сторонньої руки.",
        "money, independence", "failure",
        "The Nine of Diamonds is money earned by one's own hands: independence, bold financial initiative, success without outside care. Time to act alone. Reversed — the same will but without calculation: check the figures.",
        "Nine coins in a hand; a laboring palm with no outside hand.",
        "деньги, независимость", "неудача",
        "Девятка бубен — деньги, заработанные своими руками: независимость, смелая финансовая инициатива, успех без чужой опеки. Время действовать самостоятельно. Перевёрнутая — та же воля, но без расчёта: проверяй цифры.",
        "Девять монет в руке; трудящаяся ладонь без чужой руки.",
    ),
    "C-9": (
        "спадок, несподіванка", "сумніви",
        "Девʼятка трефа — несподівана прибутковість: спадок, бонус, виграш, гроші «звідки не чекали». Однак радість вимагає обережності з документами. Перевернута — сумніви гальмують справу: перевір факти, а не нервую.",
        "Девʼять трилисників; скриня, відчинена зненацька.",
        "inheritance, surprise", "doubts",
        "The Nine of Clubs is unexpected gain: an inheritance, bonus, prize, money 'from nowhere'. Yet the joy demands caution with documents. Reversed — doubts stall the matter: check the facts rather than fret.",
        "Nine trefoils; a chest opened unexpectedly.",
        "наследство, неожиданность", "сомнения",
        "Девятка треф — неожиданная прибыль: наследство, бонус, выигрыш, деньги «откуда не ждали». Но радость требует осторожности с документами. Перевёрнутая — сомнения тормозят дело: проверь факты, а не нервничай.",
        "Девять трилистников; сундук, открытый внезапно.",
    ),
    "S-9": (
        "збори, компанія", "скандал",
        "Девʼятка піка — компанія, збори й гучна розмова: зустріч, де слова дійдуть до суті, можливо, з гострим присмаком. Пряма — плідна дискусія. Перевернута — скандал, від якого краще усунутися завчасно.",
        "Девʼять пік; круглий стіл і повні келихи.",
        "gathering, company", "scandal",
        "The Nine of Spades is a company and a loud conversation: a meeting where words reach the point, possibly with a sharp edge. Upright — fruitful discussion. Reversed — a scandal; better to step away in advance.",
        "Nine spades; a round table with full cups.",
        "сборы, компания", "скандал",
        "Девятка пик — компания и шумный разговор: встреча, где слова дойдут до сути, возможно с острым привкусом. Прямая — плодотворная дискуссия. Перевёрнутая — скандал, от которого лучше отойти заранее.",
        "Девять пик; круглый стол и полные бокалы.",
    ),
    "H-8": (
        "поїздка, сюрприз", "порожні мрії",
        "Вісімка чирва — приємна поїздка та несподіваний сюрприз у справах серця: запрошення, візит, розмова, що змінить настрій. Пряма — легкість і радість руху. Перевернута — бажання здійснити план, що «не їде» сам.",
        "Вісім сердець; дорожній валіз і лист-запрошення.",
        "trip, surprise", "empty dreams",
        "The Eight of Hearts is a pleasant trip and an unexpected surprise in heart matters: an invitation, visit, a talk that lifts the mood. Upright — ease and joy of movement. Reversed — a wish to fulfill a plan that 'does not move' by itself.",
        "Eight hearts; a travel bag and an invitation letter.",
        "поездка, сюрприз", "пустые мечты",
        "Восьмёрка червей — приятная поездка и неожиданный сюрприз в сердечных делах: приглашение, визит, разговор. Прямая — лёгкость и радость движения. Перевёрнутая — желание осуществить план, который «не едет» сам.",
        "Восемь сердец; дорожный саквояж и письмо-приглашение.",
    ),
    "D-8": (
        "звістка, дім", "запізніла звістка",
        "Вісімка бубна — звістка про гроші здалеку: лист, переказ, телефонна розмова, що стосується фінансів чи дому. Пряма — добра звістка в дорозі. Перевернута — запізніла новина, яка вже не змінить справ.",
        "Вісім монет; поштовий голуб із листом.",
        "news, home", "late news",
        "The Eight of Diamonds is news about money from afar: a letter, transfer, phone call about finances or home. Upright — good news on the way. Reversed — a belated update that will change little.",
        "Eight coins; a carrier pigeon with a letter.",
        "весть, дом", "запоздалая весть",
        "Восьмёрка бубен — весть о деньгах издалека: письмо, перевод, телефонный разговор о финансах или доме. Прямая — добрая весть в пути. Перевёрнутая — запоздалая новость, которая уже мало что изменит.",
        "Восемь монет; почтовый голубь с письмом.",
    ),
    "C-8": (
        "море, дім", "невдача",
        "Вісімка трефа — далека справа або «казенний дім»: поїздка офіційного штибу, приватна розмова в установі, переїзд. Пряма — клопіт, що закінчиться добром. Перевернута — «море сліз»: розчарування в офіційній справі.",
        "Вісім трилисників; хвилі й дім із прапором установи.",
        "sea, home", "failure",
        "The Eight of Clubs is a distant matter or an 'official house': an official trip, a private talk in an institution, a move. Upright — a fuss that ends well. Reversed — 'a sea of tears': disappointment in an official affair.",
        "Eight trefoils; waves and a house with an institution's flag.",
        "море, дом", "неудача",
        "Восьмёрка треф — дальнее дело или «казённый дом»: официальная поездка, разговор в учреждении, переезд. Прямая — хлопоты, что закончатся добром. Перевёрнутая — «море слёз»: разочарование в официальном деле.",
        "Восемь трилистников; волны и дом с флагом учреждения.",
    ),
    "S-8": (
        "розмова, компанія", "плітки",
        "Вісімка піка — несподівана розмова в компанії: звістка в багатолюдді, гостра бесіда, що несподівано зближує. Пряма — розмова, яку варто завершити добром. Перевернута — плітки про тебе ходять колом.",
        "Вісім пік; крісло в кулуарах і двоє за розмовою.",
        "talk, company", "gossip",
        "The Eight of Spades is an unexpected conversation in a company: news in a crowd, a sharp talk that unexpectedly brings together. Upright — a talk to end on good terms. Reversed — rumors about you are going around.",
        "Eight spades; an armchair in the lobby and two people talking.",
        "разговор, компания", "сплетни",
        "Восьмёрка пик — неожиданный разговор в компании: весть в многолюдье, острый разговор. Прямая — беседа, которую стоит завершить добром. Перевёрнутая — о тебе ходят слухи.",
        "Восемь пик; кресло в кулуарах и двое беседующих.",
    ),
    "H-7": (
        "побачення", "зрада",
        "Сімка чирва — побачення й ніжність: зустріч віч-на-віч, сватання, розмова, від якої тепліє серце. Пряма — гарні наміри, які варто закріпити дією. Перевернута — слова, за якими не стоїть щирість: перевір, хто кого обманює.",
        "Сім сердець; побачення під ліхтарем при місяці.",
        "date", "betrayal",
        "The Seven of Hearts is a date and tenderness: a face-to-face meeting, courtship, a talk that warms the heart. Upright — good intentions worth fixing by action. Reversed — words without sincerity behind them: check who deceives whom.",
        "Seven hearts; a rendezvous under a lamp in the moonlight.",
        "свидание", "измена",
        "Семёрка червей — свидание и нежность: встреча с глазу на глаз, ухаживание, разговор, от которого теплеет сердце. Прямая — намерения, которые стоит закрепить делом. Перевёрнутая — слова без искренности: проверь, кто кого обманывает.",
        "Семь сердец; свидание под фонарём при луне.",
    ),
    "D-7": (
        "подарунок", "обман",
        "Сімка бубна — подарунок, вигода та приємна дрібниця: несподівана приємність, успіх у легкій справі, маленький, але чесний зиск. Пряма — доля підкидає приємний знак. Перевернута — обман заради вигоди: не довіряй словам, довіряй цифрам.",
        "Сім монет; дарунок у стрічці та монета-вудка.",
        "gift", "deception",
        "The Seven of Diamonds is a gift, gain and a pleasant trifle: an unexpected nicety, success in a light matter, a small but honest profit. Upright — fate throws a pleasant sign. Reversed — deception for advantage: trust figures, not words.",
        "Seven coins; a gift in a ribbon and a coin on a fishing line.",
        "подарок", "обман",
        "Семёрка бубен — подарок, выгода и приятная мелочь: неожиданная приятность, успех в лёгком деле, маленький, но честный барыш. Прямая — судьба даёт приятный знак. Перевёрнутая — обман ради выгоды: доверяй цифрам, а не словам.",
        "Семь монет; подарок в ленте и монета на удочке.",
    ),
    "C-7": (
        "гроші, звістка", "збитки",
        "Сімка трефа — звістка про гроші в діловому руслі: невеликий успіх, переговори, проміжний результат. Пряма — хороший знак для угоди на етапі «майже». Перевернута — збитки через недоглянуте зобовʼязання.",
        "Сім трилисників; діловий стіл із рапортом і монетою.",
        "money, news", "losses",
        "The Seven of Clubs is news about money in a business vein: a small success, talks, an interim result. Upright — a good sign for a deal at the 'almost' stage. Reversed — losses from an overlooked obligation.",
        "Seven trefoils; a business table with a report and a coin.",
        "деньги, весть", "убытки",
        "Семёрка треф — весть о деньгах в деловом русле: небольшой успех, переговоры, промежуточный результат. Прямая — хороший знак для сделки на этапе «почти». Перевёрнутая — убытки из-за прогляденного обязательства.",
        "Семь трилистников; деловой стол с рапортом и монетой.",
    ),
    "S-7": (
        "диво, компанія", "сварка",
        "Сімка піка — диво й компанія: несподівана звістка, зустріч, що все перевертає, можливість, яку «не чекали». Пряма — не бійся того, що дивує. Перевернута — сварка в компанії: слово стає гострим клинком.",
        "Сім пік; зорі, що падають над столом компанії.",
        "wonder, company", "quarrel",
        "The Seven of Spades is a wonder and a company: an unexpected news, a meeting that turns everything around, an opportunity 'not awaited'. Upright — do not fear what surprises. Reversed — a quarrel in the company: the word becomes a sharp blade.",
        "Seven spades; falling stars above the company's table.",
        "чудо, компания", "ссора",
        "Семёрка пик — чудо и компания: неожиданная весть, встреча, переворачивающая всё, возможность, «которую не ждали». Прямая — не бойся того, что удивляет. Перевёрнутая — ссора в компании: слово становится острым клинком.",
        "Семь пик; падающие звёзды над столом компании.",
    ),
    "H-6": (
        "дорога, розмова", "розлука",
        "Шістка чирва — дорога і приємна розмова: поїздка до близької людини, прогулянка, що зближує. Чим коротша дорога до серця, тим кращі новини. Перевернута — розлука на час або думки про людину, якої нема поруч.",
        "Шість сердець; стежка та карета, що їде до дому коханої.",
        "road, talk", "separation",
        "The Six of Hearts is a road and a pleasant talk: a trip to a loved one, a walk that brings closer. The shorter the road to the heart, the better the news. Reversed — a temporary parting or thoughts of someone far away.",
        "Six hearts; a path and a carriage heading to the beloved's home.",
        "дорога, разговор", "разлука",
        "Шестёрка червей — дорога и приятный разговор: поездка к близкому, прогулка, что сближает. Перевёрнутая — разлука на время или мысли о человеке, которого нет рядом.",
        "Шесть сердец; тропа и карета, едущая к дому любимой.",
    ),
    "D-6": (
        "дорога, виконання", "погана дорога",
        "Шістка бубна — рання дорога й виконання бажання: поїздка з корисною метою, виконання дрібного, але приємного зобовʼязання. Пряма — бажання збувається через рух. Перевернута — «погана дорога»: відклади поїздку.",
        "Шість монет; ранкова зоря над дорогою та мішком.",
        "road, fulfillment", "bad road",
        "The Six of Diamonds is an early road and the fulfillment of a wish: a trip with a useful purpose, fulfilling a small but pleasant duty. Upright — the wish comes true through movement. Reversed — a 'bad road': postpone the trip.",
        "Six coins; the morning star over a road and a bag.",
        "дорога, исполнение", "плохая дорога",
        "Шестёрка бубен — ранняя дорога и исполнение желания: поездка с полезной целью, выполнение мелкого приятного обязательства. Прямая — желание сбывается через движение. Перевёрнутая — отложи поездку.",
        "Шесть монет; утренняя звезда над дорогой и мешком.",
    ),
    "C-6": (
        "дорога ввечері", "порожня дорога",
        "Шістка трефа — вечірня дорога: поїздка наприкінці дня, повернення, ділова зустріч після роботи. Пряма — дорога «недалека, але потрібна». Перевернута — порожня дорога: зусилля без результату.",
        "Шість трилисників; вечірній шлях із ліхтарем і клунком.",
        "evening road", "empty road",
        "The Six of Clubs is an evening road: a trip at the end of the day, a return, a business meeting after work. Upright — a road 'short but needed'. Reversed — an empty road: effort without result.",
        "Six trefoils; an evening path with a lantern and a bundle.",
        "вечерняя дорога", "пустая дорога",
        "Шестёрка треф — вечерняя дорога: поездка в конце дня, возвращение, деловая встреча после работы. Прямая — дорога «недальняя, но нужная». Перевёрнутая — пустая дорога: усилия без результата.",
        "Шесть трилистников; вечерний путь с фонарём и котомкой.",
    ),
    "S-6": (
        "пізня дорога", "невдача",
        "Шістка піка — пізня, нічна дорога: поїздка в темряві, далекий шлях, що вимагає обачності. Пряма — дорога, яку варто пройти, але з обережністю. Перевернута — невдача в дорозі: зваж двічі, чи їхати.",
        "Шість пік; молодь під місяцем, що йдуть чорним шляхом.",
        "late road", "failure",
        "The Six of Spades is a late, night road: a trip in the dark, a long path that calls for caution. Upright — a road worth taking, but carefully. Reversed — failure on the way: weigh twice whether to go.",
        "Six spades; youths under the moon walking a dark path.",
        "поздняя дорога", "неудача",
        "Шестёрка пик — поздняя, ночная дорога: поездка в темноте, дальний путь, требующий осторожности. Прямая — путь, который стоит пройти, но с опаской. Перевёрнутая — неудача в дороге: взвесь дважды, стоит ли ехать.",
        "Шесть пик; люди под луной, идущие чёрным путём.",
    ),
}


def main():
    p = CARDS_DIR / "playing36.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    missing = [c["number"] for c in data["cards"] if c["number"] not in PLAYING]
    assert not missing, f"Нема опису для: {missing}"
    for c in data["cards"]:
        e = PLAYING[c["number"]]
        c["keywords_upright"], c["keywords_reversed"] = e[0], e[1]
        c["meaning_general"], c["symbolism"] = e[2], e[3]
        t = c.get("translations", {})
        t["en"].update({"keywords_upright": e[4], "keywords_reversed": e[5],
                        "meaning_general": e[6], "symbolism": e[7]})
        t["ru"].update({"keywords_upright": e[8], "keywords_reversed": e[9],
                        "meaning_general": e[10], "symbolism": e[11]})
        c["translations"] = t
    p.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    print(f"[OK] playing36.json: {len(data['cards'])} карт збагачено")


if __name__ == "__main__":
    main()