# -*- coding: utf-8 -*-
"""7 навчальних таро-колод (4-та і 5-та хвилі) — власний переказ + тема.

Кожна колода — навчальний аналог комерційної (структура 78 карт RWS),
значення — власні формулювання поверх базових значень base_texts.BASE,
глибокі тексти (love/career/health/spirituality/reversed) беруться з
першої колоди (deck 1) у момент імпорту. Cards are built here.
"""

from .base_texts import BASE
from .common import MAJOR_NAMES, MAJOR_ROMAN, SUITS


# Стандартні назви рангів (укр основа / en / ru)
RANKS = {
    1:  ("Туз", "Ace", "Туз"),
    2:  ("Двійка", "Two", "Двойка"),
    3:  ("Трійка", "Three", "Тройка"),
    4:  ("Четвірка", "Four", "Четвёрка"),
    5:  ("П'ятірка", "Five", "Пятёрка"),
    6:  ("Шістка", "Six", "Шестёрка"),
    7:  ("Сімка", "Seven", "Семёрка"),
    8:  ("Вісімка", "Eight", "Восьмёрка"),
    9:  ("Дев'ятка", "Nine", "Девятка"),
    10: ("Десятка", "Ten", "Десятка"),
    11: ("Паж", "Page", "Паж"),
    12: ("Лицар", "Knight", "Рыцарь"),
    13: ("Королева", "Queen", "Королева"),
    14: ("Король", "King", "Король"),
}

# Іменникові форми мастей для назв карт: (укр, en, ru)
SUIT_PARTS = {
    "wands":     ("жезлів", "Wands", "жезлов"),
    "cups":      ("кубків", "Cups", "кубков"),
    "swords":    ("мечів", "Swords", "мечей"),
    "pentacles": ("пентаклів", "Pentacles", "пентаклей"),
}


def minor_name(suit_code, rank, suit_parts=None):
    """Стандартна назва молодшої карты: rank + масть."""
    ru, en, uk = RANKS[rank]
    s_uk, s_en, s_ru = (suit_parts or SUIT_PARTS)[suit_code]
    uk_name = f"{ru} {s_uk}"
    en_name = f"{en} of {s_en}"
    return uk_name, en_name, f"{uk} {s_ru}"


def build(kind):
    th = DECKS[kind]
    rows = []
    # мажори 0..21
    for i in range(22):
        k = str(i)
        maj_name = MAJOR_NAMES[k]
        kw = th["majors"].get(k, BASE[k][:3])
        rows.append(_row(th, k, "major", None, maj_name, kw, BASE[k][3:]))
    # молодші 4 x 14
    for suit in ("wands", "cups", "swords", "pentacles"):
        s_uk, s_el, s_el_en = SUITS[suit]
        suit_parts = th.get("suit_parts")
        for r in range(1, 15):
            key = f"{suit.capitalize()}-{r:02d}"
            n_uk, n_en, n_ru = minor_name(suit, r, suit_parts)
            sf = th.get("suit_flavor", {}).get(suit)
            kw = BASE[key][:3]
            if sf:
                kw = tuple(f"{sf[i]}, {kw[i]}" for i in range(3))
            rows.append(_row(th, key, "minor", suit,
                             (n_uk, n_en, n_ru), kw, BASE[key][3:],
                             s_uk, s_el, s_el_en))
    return rows


def _row(th, number, arcana, suit_code, name3, kw3, gen3,
         suit_uk=None, element_uk=None, element_en=None):
    """Збирає поля картки-словника. Глибокі значення доливаються в імпортері."""
    arc_t = "Старший аркан" if arcana == "major" else "Молодший аркан"
    if suit_code:
        suit_uk_ = th.get("suits", {}).get(suit_code, suit_uk)
        el = th.get("elements", {}).get(suit_code, element_uk)
        el_code = {"wands": "fire", "cups": "water",
                   "swords": "air", "pentacles": "earth"}.get(suit_code)
    else:
        suit_uk_, el, el_code = None, None, None
    return {
        "number": MAJOR_ROMAN.get(number, number) if arcana == "major" else number,
        "arcana_type": arc_t,
        "suit": suit_uk_,
        "element": el,
        "suit_code": suit_code,
        "element_code": el_code,
        "name": name3[0],
        "keywords_upright": kw3[0],
        "meaning_general": gen3[0],
        "translations": {
            "uk": {"name": name3[0], "keywords_upright": kw3[0],
                   "meaning_general": gen3[0]},
            "en": {"name": name3[1], "keywords_upright": kw3[1],
                   "meaning_general": gen3[1]},
            "ru": {"name": name3[2], "keywords_upright": kw3[2],
                   "meaning_general": gen3[2]},
        },
    }


DECKS = {
    "angel": {
        "name_uk": "Таро Ангелів (навчальне)",
        "name_en": "Angel Tarot (learning)",
        "name_ru": "Таро Ангелов (обучающая)",
        "author": "AI-Arcanum (навчальна колода)",
        "publisher": None, "year": None,
        "source": "https://www.rockpoolpublishing.com.au/angel-tarot",
        "description": ("Навчальний аналог колоди «Angel Tarot» (Travis McHenry, "
                        "Rockpool Publishing): 78 карт класичного Райдера–Вейта, "
                        "але в образах ангелів-охоронців духовної традиції. "
                        "Значення — власний переказ; ілюстрації процедурні."),
        "composition": ("78 карт: 22 Старших + 56 Молодших арканів (4 масті × 14). "
                        "Тема — ангельський захист і натхнення. Розклад «Покров»: "
                        "карта дня / перешкода / ангел-порадник."),
        "majors": {  # тематичні keywords для Старших (укр, en, ru)
            "0": ("ангельська безтурботність, новий шлях, довіра крилам",
                  "angelic ease, a new path, trusting the wings",
                  "ангельская беззаботность, новый путь, доверие крыльям"),
            "1": ("ангел-творець, сила волі, виявлення дару",
                  "angel-creator, willpower, manifesting a gift",
                  "ангел-творец, сила воли, проявление дара"),
            "2": ("ангел тиші, інтуїція, таємне знання небес",
                  "angel of silence, intuition, hidden heavenly knowledge",
                  "ангел тишины, интуиция, тайное небесное знание"),
            "3": ("ангел достатку, турбота, цвітіння життя",
                  "angel of abundance, care, blooming of life",
                  "ангел изобилия, забота, расцвет жизни"),
            "4": ("ангел-хранитель порядку, опора, захист",
                  "guardian angel of order, foundation, protection",
                  "ангел-хранитель порядка, опора, защита"),
            "5": ("ангел-наставник, мудрість традиції, порада",
                  "angel-mentor, wisdom of tradition, counsel",
                  "ангел-наставник, мудрость традиции, совет"),
            "6": ("ангел єднання, любов, благословенний вибір",
                  "angel of union, love, a blessed choice",
                  "ангел единения, любовь, благословенный выбор"),
            "7": ("ангел перемоги, колісниця волі, перемога над сумнівом",
                  "angel of victory, chariot of will, triumph over doubt",
                  "ангел победы, колесница воли, победа над сомнением"),
            "8": ("лагідна сила, ангельська мудрість, упокорення",
                  "gentle strength, angelic wisdom, temperance",
                  "нежная сила, ангельская мудрость, кротость"),
            "9": ("ангел самотності, внутрішній світ, ясність у тиші",
                  "angel of solitude, inner light, clarity in silence",
                  "ангел одиночества, внутренний свет, ясность в тишине"),
            "10": ("ангел долі, поворот, благодать обставин",
                   "angel of fate, a turn, grace of circumstances",
                   "ангел судьбы, поворот, благодать обстоятельств"),
            "11": ("ангел справедливості, істина, рівновага",
                   "angel of justice, truth, balance",
                   "ангел справедливости, истина, равновесие"),
            "12": ("ангел відпускання, пауза, новий погляд згори",
                   "angel of letting go, a pause, a new view from above",
                   "ангел отпускания, пауза, новый взгляд свыше"),
            "13": ("ангел переходу, трансформація, відродження",
                   "angel of transition, transformation, rebirth",
                   "ангел перехода, трансформация, возрождение"),
            "14": ("ангел міри, терпіння, зцілення протиріч",
                   "angel of measure, patience, healing of opposites",
                   "ангел меры, терпение, исцеление противоречий"),
            "15": ("ангел тіні, спокуса, пробудження до свободи",
                   "angel of shadow, temptation, awakening to freedom",
                   "ангел тени, искушение, пробуждение к свободе"),
            "16": ("ангел струсу, руйнація оман, вивільнення",
                   "angel of upheaval, breaking illusions, liberation",
                   "ангел потрясения, крушение иллюзий, освобождение"),
            "17": ("зірка-ангел-орієнтир, надія, зцілення",
                   "star-angel guide, hope, healing",
                   "звезда-ангел-путеводитель, надежда, исцеление"),
            "18": ("ангел сновидінь, таємниці, просвітлення тіні",
                   "angel of dreams, mysteries, illuminating the shadow",
                   "ангел сновидений, тайны, просветление тени"),
            "19": ("ангел світла, радість, повне сяйво",
                   "angel of light, joy, full radiance",
                   "ангел света, радость, полное сияние"),
            "20": ("поклик ангелів, відродження, духовний підсумок",
                   "call of angels, rebirth, spiritual reckoning",
                   "призыв ангелов, возрождение, духовный итог"),
            "21": ("ангел цілісності, завершення, небесна гармонія",
                   "angel of wholeness, completion, heavenly harmony",
                   "ангел целостности, завершение, небесная гармония"),
        },
        "suit_flavor": {  # тематична грань мастей (додається до базових keywords)
            "wands": ("ангельський вогонь", "angelic fire", "ангельский огонь"),
            "cups": ("чаша благодаті", "cup of grace", "чаша благодати"),
            "swords": ("меч істини", "sword of truth", "меч истины"),
            "pentacles": ("дар неба", "heavenly gift", "небесный дар"),
        },
    },
    "neocolonial": {
        "name_uk": "Неоколоніальне таро Америк (навчальне)",
        "name_en": "Tarot Neocolonial de las Americas (learning)",
        "name_ru": "Неоколониальное таро Америк (обучающая)",
        "author": "AI-Arcanum (навчальна колода)",
        "publisher": None, "year": None,
        "source": "https://www.usgamesinc.com/tarot-neocolonial-de-las-americas",
        "description": ("Навчальний аналог колоди «Tarot Neocolonial de las Americas» "
                        "(Patrick McGrath Muniz, U.S. Games, 2022): класичний Райдер–"
                        "Вейт, але у вирі колоніальної історії обох Америк — шлях, "
                        "здобутий через бурі. Значення — власний переказ."),
        "composition": ("78 карт: 22 Старших + 56 Молодших (4 масті × 14). "
                        "Тема — історія, рух уперед, сплетіння культур. "
                        "Розклад «Шлях колонізатора»: минуле / нині / спадщина."),
        "majors": {
            "0": ("новатор-мандрівник, перший крок на новій землі, свобода",
                  "trailblazer, first step on new land, freedom",
                  "первопроходец, первый шаг на новой земле, свобода"),
            "1": ("мастак справи, кузня волі, творення з нуля",
                  "craftsman of deeds, forge of will, creating from scratch",
                  "мастер дела, кузня воли, созидание с нуля"),
            "2": ("хранителька знання, тиха мудрість, таємні хроніки",
                  "keeper of knowledge, quiet wisdom, secret chronicles",
                  "хранительница знания, тихая мудрость, тайные хроники"),
            "3": ("господиня землі, достаток, дозрівання врожаю",
                  "mistress of the land, abundance, ripening harvest",
                  "хозяйка земли, изобилие, созревание урожая"),
            "4": ("управитель фортеці, порядок, закон межі",
                  "governor of the fortress, order, law of the border",
                  "управитель крепости, порядок, закон границы"),
            "5": ("наставник-летописець, традиція, духовна хартія",
                  "chronicler-mentor, tradition, spiritual charter",
                  "наставник-летописец, традиция, духовная хартия"),
            "6": ("союз двох культур, вибір серця, благословенний шлюб шляхів",
                  "union of two cultures, heart's choice, blessed joining of paths",
                  "союз двух культур, выбор сердца, благословенный союз путей"),
            "7": ("тріумф упертюха, колісниця мрії, перемога над пусткою",
                  "triumph of the determined, chariot of a dream, victory over the wild",
                  "триумф упрямца, колесница мечты, победа над пустошью"),
            "8": ("сила народу, лагідна стійкість, терпіння проти буревію",
                  "strength of the people, gentle resilience, patience against the storm",
                  "сила народа, нежная стойкость, терпение против бури"),
            "9": ("самітник-дослідник, внутрішній компас, вогонь вогнища",
                  "hermit-explorer, inner compass, fire of the hearth",
                  "отшельник-исследователь, внутренний компас, огонь очага"),
            "10": ("колесо слави, змінна фортуна, епоха повороту",
                   "wheel of fame, shifting fortune, age of turn",
                   "колесо славы, переменная фортуна, эпоха поворота"),
            "11": ("магістрат істини, закон, чесна міра",
                   "magistrate of truth, law, an honest measure",
                   "магистрат истины, закон, честная мера"),
            "12": ("той, хто зупинився подумати, жертва заради істини",
                   "the one who paused to think, sacrifice for truth",
                   "остановившийся подумать, жертва ради истины"),
            "13": ("кінець епохи, зміна влади, новий континент долі",
                   "end of an era, shift of power, new continent of fate",
                   "конец эпохи, смена власти, новый континент судьбы"),
            "14": ("міра обміну, терпелива мандрівка, золота середина",
                   "measure of exchange, patient journey, golden mean",
                   "мера обмена, терпеливое путешествие, золотая середина"),
            "15": ("спокуса багатства, кайдани жадоби, пробудження",
                   "temptation of riches, chains of greed, awakening",
                   "искушение богатства, кандалы жадности, пробуждение"),
            "16": ("зруйнована цитадель, струс порядку, свобода з-під руїн",
                   "fallen citadel, upheaval of order, freedom from the ruins",
                   "разрушенная цитадель, потрясение порядка, свобода из-под руин"),
            "17": ("зірка-орієнтир над океаном, надія поселенця, зцілення",
                   "guiding star over the ocean, settler's hope, healing",
                   "звезда-ориентир над океаном, надежда поселенца, исцеление"),
            "18": ("туманні води, страхи невідомості, приховані береги",
                   "foggy waters, fears of the unknown, hidden shores",
                   "туманные воды, страхи неизвестности, скрытые берега"),
            "19": ("ясний день Нового Світу, тріумф, світло над обрієм",
                   "bright day of the New World, triumph, light on the horizon",
                   "ясный день Нового Света, триумф, свет на горизонте"),
            "20": ("поклик нащадків, підсумок спадщини, відродження пам'яті",
                   "call of descendants, reckoning of legacy, rebirth of memory",
                   "призыв потомков, итог наследия, возрождение памяти"),
            "21": ("зшита із шляхів карта, цілісність світу, тріумф мандрівки",
                   "map sewn from paths, wholeness of the world, triumph of the journey",
                   "сшитая из путей карта, целостность мира, триумф путешествия"),
        },
        "suit_flavor": {
            "wands": ("смолоскип мандрівника", "traveler's torch", "факел странника"),
            "cups": ("злива долі", "rain of fate", "ливень судьбы"),
            "swords": ("шпага закону", "sword of law", "шпага закона"),
            "pentacles": ("карбована монета", "minted coin", "чеканная монета"),
        },
    },
    "fablemaker": {
        "name_uk": "Анімоване таро Байкаря (навчальне)",
        "name_en": "The Fablemaker's Animated Tarot (learning)",
        "name_ru": "Анимированное таро Баснописца (обучающая)",
        "author": "AI-Arcanum (навчальна колода)",
        "publisher": None, "year": None,
        "source": "https://www.usgamesinc.com/the-fablemakers-animated-tarot",
        "description": ("Навчальний аналог колоди «The Fablemaker's Animated Tarot» "
                        "(Misty Bourne, US Games, 2022): класичний Райдер–Вейт, "
                        "поданий як серія казкових кадрів-мульт фільму. Значення — "
                        "власний переказ у світлі образів байок і казок."),
        "composition": ("78 карт: 22 Старших + 56 Молодших (4 масті × 14). "
                        "Тема — казка, анімація, оживаючі персонажі. "
                        "Розклад «Казка дня»: герой / перепона / фея-помічниця."),
        "majors": {
            "0": ("необачний герой казки, пригода з відкритим серцем",
                  "rash story hero, adventure with an open heart",
                  "опрометчивый герой сказки, приключение с открытым сердцем"),
            "1": ("чарівник-майстер, фокус волі, чарівна паличка таланту",
                  "sorcerer-craftsman, trick of will, magic wand of talent",
                  "волшебник-мастер, фокус воли, волшебная палочка таланта"),
            "2": ("мудра няня-чарівниця, секрет, тихе закляття",
                  "wise fairy-nanny, a secret, a quiet charm",
                  "мудрая няня-волшебница, секрет, тихое заклятие"),
            "3": ("чародійка-господиня, повне квіття, дар природи",
                  "enchantress-hostess, full bloom, gift of nature",
                  "чародейка-хозяйка, полное цветение, дар природы"),
            "4": ("король-чарівник, закони казкового королівства, лад",
                  "sorcerer-king, laws of the fairy kingdom, order",
                  "король-волшебник, законы сказочного королевства, лад"),
            "5": ("сказитель-мудрець, перекази, урок казки",
                  "storyteller-sage, lore, lesson of the tale",
                  "сказитель-мудрец, предания, урок сказки"),
            "6": ("принц і принцеса казки, обіцянка серця, союз",
                  "storybook prince and princess, promise of heart, union",
                  "принц и принцесса сказки, обещание сердца, союз"),
            "7": ("витязь у кареті, шлях до мети, подолання чар",
                  "knight in a carriage, road to a goal, breaking spells",
                  "витязь в карете, путь к цели, преодоление чар"),
            "8": ("терплячий звір-помічник, лагідна сила, порозуміння",
                  "patient animal-helper, gentle strength, understanding",
                  "терпеливый зверь-помощник, нежная сила, понимание"),
            "9": ("мудрий відлюдник із ліхтарем, таємниця лісу, пошук",
                  "wise hermit with a lantern, secret of the forest, search",
                  "мудрый отшельник с фонарём, тайна леса, поиск"),
            "10": ("чарівне колесо, поворот сюжету, щасливий поворот",
                   "magic wheel, plot twist, lucky turn",
                   "волшебное колесо, поворот сюжета, счастливый поворот"),
            "11": ("ваги казкової справедливості, чесність, зважене рішення",
                   "scales of fairy justice, honesty, a weighed decision",
                   "весы сказочной справедливости, честность, взвешенное решение"),
            "12": ("сплячий герой, пауза перед чудом, інший погляд",
                   "sleeping hero, pause before a wonder, another view",
                   "спящий герой, пауза перед чудом, иной взгляд"),
            "13": ("перетворення казки, кінець старого акту, нова глава",
                   "transformation of the tale, end of an act, new chapter",
                   "превращение сказки, конец старого акта, новая глава"),
            "14": ("знахар-алхімік, змішування чар, міра терпіння",
                   "healer-alchemist, blending charms, measure of patience",
                   "знахарь-алхимик, смешивание чар, мера терпения"),
            "15": ("каверзний геній-спокусник, пастка бажань, випробування",
                   "tricky genie-tempter, trap of wishes, a test",
                   "каверзный гений-искуситель, ловушка желаний, испытание"),
            "16": ("зламаний замок, крах чарів, світло правди",
                   "broken castle, collapse of charms, light of truth",
                   "разрушенный замок, крах чар, свет правды"),
            "17": ("фея надії, зцілення, зірка-бажання",
                   "fairy of hope, healing, a wishing star",
                   "фея надежды, исцеление, звезда-желание"),
            "18": ("нічні тіні казки, сновидіння, таємниця місяця",
                   "night shadows of the tale, dreams, secret of the moon",
                   "ночные тени сказки, сновидения, тайна луны"),
            "19": ("свято в королівстві, яскраве світло, щасливий кінець",
                   "kingdom feast, bright light, happy ending",
                   "праздник в королевстве, яркий свет, счастливый конец"),
            "20": ("поклик горну, пробудження, підсумок казки",
                   "call of the horn, awakening, summing up the tale",
                   "зов горна, пробуждение, итог сказки"),
            "21": ("вальс усіх персонажів, завершення фільму, завіса",
                   "dance of all characters, film finale, the curtain",
                   "вальс всех персонажей, финал фильма, занавес"),
        },
        "suit_flavor": {
            "wands": ("чарівна паличка", "magic wand", "волшебная палочка"),
            "cups": ("напій чарівника", "potion of the wizard", "напиток волшебника"),
            "swords": ("меч-сказка", "fabled sword", "меч-сказка"),
            "pentacles": ("лисиця з монетою", "fox with a coin", "лиса с монетой"),
        },
    },
    "alice": {
        "name_uk": "Таро Аліси в Країні Чудес (навчальне)",
        "name_en": "Alice in Wonderland Tarot (learning)",
        "name_ru": "Таро Алисы в Стране Чудес (обучающая)",
        "author": "AI-Arcanum (навчальна колода)",
        "publisher": None, "year": None,
        "source": "https://www.insighteditions.com/products/alice-in-wonderland-tarot-deck",
        "description": ("Навчальний аналог колоди «Alice in Wonderland Tarot» "
                        "(Lisa Vannini, Insight Editions, 2022): класичний Райдер–"
                        "Вейт у світі дива Льюїса Керрола. Значення — власний "
                        "переказ; образи й тексти оригінальні, без копіювання."),
        "composition": ("78 карт: 22 Старших + 56 Молодших (4 масті × 14). "
                        "Тема — Країна Чудес, дива, перевернута логіка. "
                        "Розклад «Дзеркало»: як є / як здається / що за ширмою."),
        "majors": {
            "0": ("стрибок у нору, новий світ, довіра диву",
                  "jump into the hole, a new world, trust in wonder",
                  "прыжок в нору, новый мир, доверие чуду"),
            "1": ("фокусник дива, чари слова, вміння міняти розміри",
                  "wonder conjurer, magic of words, power to change size",
                  "фокусник чуда, магия слова, умение менять размер"),
            "2": ("таємна кімната, інтуїція, знання за дверима",
                  "secret room, intuition, knowledge behind the door",
                  "тайная комната, интуиция, знание за дверью"),
            "3": ("сад, що розцвів, диво зростання, турбота про казку",
                  "garden in bloom, miracle of growth, care for the tale",
                  "расцветший сад, чудо роста, забота о сказке"),
            "4": ("король карт-лагоду, правила чаювання, лад дива",
                  "king of card-order, rules of the tea party, order of wonder",
                  "король карточного лада, правила чаепития, порядок чуда"),
            "5": ("ворін-мудрець, уроки див, дива мови",
                  "crow-sage, lessons of wonder, marvels of language",
                  "ворон-мудрец, уроки чудес, чудеса языка"),
            "6": ("дзеркальна пара, вибір серця, казковий союз",
                  "mirror pair, heart's choice, fabled union",
                  "зеркальная пара, выбор сердца, сказочный союз"),
            "7": ("колісниця зі штор у вирі див, перемога над плутаниною",
                  "chariot of playing-cards in the swirl, victory over chaos",
                  "колесница карт в круговерти, победа над неразберихой"),
            "8": ("лагідна сила Кота, спокій у дивному світі, увага",
                  "gentle strength of the Cat, calm in the strange world, attention",
                  "нежная сила Кота, спокойствие в чудном мире, внимание"),
            "9": ("безумний чайний майстер, пошук часу, тиша дива",
                  "mad tea master, hunt for time, silence of wonder",
                  "безумный чайный мастер, поиск времени, тишина чуда"),
            "10": ("картярське колесо, перетасування долі, гра випадку",
                   "card wheel, reshuffling of fate, game of chance",
                   "карточное колесо, перетасовка судьбы, игра случая"),
            "11": ("королева правосуддя, вінценосний вирок, чесність дива",
                   "queen of justice, crowned verdict, honesty of wonder",
                   "королева правосудия, весенний приговор, честность чуда"),
            "12": ("підвішений капелюшник, інший бік часу, новий зір",
                   "hanging hatter, other side of time, new sight",
                   "подвешенный шляпник, другая сторона времени, новое зрение"),
            "13": ("перетворення героїні, кінець однієї гри, нова глава",
                   "transformation of the heroine, end of one game, new chapter",
                   "превращение героини, конец одной игры, новая глава"),
            "14": ("чаївник міри, змішаний чай, рівновага дива",
                   "tea master of measure, blended tea, balance of wonder",
                   "чайник меры, смешанный чай, равновесие чуда"),
            "15": ("спокуса часу, казковий гість, дивна бентега",
                   "temptation of time, fabled guest, strange allure",
                   "искушение времени, сказочный гость, чудная смута"),
            "16": ("королівський накат, руйнація білої фортеці, правда гри",
                   "royal march, fall of the white fortress, truth of the game",
                   "королевский натиск, крушение белой крепости, правда игры"),
            "17": ("зірка-мрія, надія крізь диво, зцілення дива",
                   "wish star, hope through wonder, healing of the wonder",
                   "звезда-мечта, надежда сквозь чудо, исцеление чуда"),
            "18": ("місячний сад, сновидіння країни, межа сну і яви",
                   "moonlight garden, dreams of the land, border of dream and waking",
                   "лунный сад, сновидения страны, граница сна и яви"),
            "19": ("сонячний бал, ясність дива, сміх перемоги",
                   "sunny ball, clarity of wonder, laughter of victory",
                   "солнечный бал, ясность чуда, смех победы"),
            "20": ("поклик дзеркала, пробудження дівчинки, підсумок мандрівки",
                   "call of the mirror, awakening of the girl, summing up the journey",
                   "зов зеркала, пробуждение девочки, итог путешествия"),
            "21": ("гармонія дивного балу, завершення казки, цілісність світу",
                   "harmony of the wonder ball, end of the tale, wholeness of the world",
                   "гармония чудного бала, завершение сказки, целостность мира"),
        },
        "suit_flavor": {
            "wands": ("дача кроля", "rabbit's carrot", "морковка кролика"),
            "cups": ("чашка дивного чаю", "cup of strange tea", "чашка дивного чая"),
            "swords": ("віяло королеви", "queen's fan", "веер королевы"),
            "pentacles": ("троянда Аліси", "Alice's rose", "роза Алисы"),
        },
    },
    "visionquest": {
        "name_uk": "Таро Пошуку Видіння (навчальне)",
        "name_en": "Vision Quest Tarot (learning)",
        "name_ru": "Таро Поиска Видения (обучающая)",
        "author": "AI-Arcanum (навчальна колода)",
        "publisher": None, "year": None,
        "source": "https://www.agmuller.net/vision-quest-tarot",
        "description": ("Навчальний аналог колоди «Vision Quest Tarot» (Gayana "
                        "Sylwia Winter, AGMuller, 1998/2016): традиція Кроулі (Тота), "
                        "77 карт у шаманському ключі пошуку видіння. Значення — "
                        "власний переказ; оригінальні ілюстрації відсутні."),
        "composition": ("78 карт за структурою Тота: 22 Старших (стандартна "
                        "послідовність) + 56 Молодших. У цій навчальній версії масті "
                        "названі по-нашому: Стріли (вогонь), Чаші (вода), Пера (повітря), "
                        "Плоди (земля); двори — Донька, Син, Мати, Батько."),
        "suits": {
            "wands": "Стріли", "cups": "Чаші",
            "swords": "Пера", "pentacles": "Плоди",
        },
        "suit_parts": {
            "wands": ("стріл", "Arrows", "стрел"),
            "cups": ("чаш", "Chalices", "чаш"),
            "swords": ("пер", "Feathers", "перьев"),
            "pentacles": ("плодів", "Fruits", "плодов"),
        },
        "elements": {
            "wands": "Вогонь", "cups": "Вода",
            "swords": "Повітря", "pentacles": "Земля",
        },
        "majors": {
            "0": ("перший крок у видіння, шаман-початківець, довіра духові",
                  "first step into vision, novice shaman, trusting the spirit",
                  "первый шаг в видение, шаман-новичок, доверие духу"),
            "1": ("шаман-творець, сила бачення, спрямування волі",
                  "shaman-creator, power of vision, directing the will",
                  "шаман-творец, сила видения, направление воли"),
            "2": ("Мати-Дух, тихе знання, печера мудрості",
                  "Mother-Spirit, quiet knowledge, cave of wisdom",
                  "Мать-Дух, тихое знание, пещера мудрости"),
            "3": ("Мати-Земля, родючість, процвітання племені",
                  "Mother-Earth, fertility, thriving of the tribe",
                  "Мать-Земля, плодородие, процветание племени"),
            "4": ("Вождь, закон звичаю, міць табу",
                  "Chief, law of custom, might of taboo",
                  "Вождь, закон обычая, мощь табу"),
            "5": ("Старець-Мудрець, обряди, передача знання",
                  "Elder-Wise One, rites, passing on knowledge",
                  "Старец-Мудрец, обряды, передача знания"),
            "6": ("обмін дарами, союз душ, священний вибір",
                  "exchange of gifts, union of spirits, sacred choice",
                  "обмен дарами, союз душ, священный выбор"),
            "7": ("дух-провідник, керування душею, шлях крізь світи",
                  "spirit-guide, guiding the soul, journey through worlds",
                  "дух-проводник, ведение души, путь сквозь миры"),
            "8": ("сила тотема, лагідна міць, порозуміння зі звіром",
                  "totem power, gentle might, understanding the animal",
                  "сила тотема, нежная мощь, понимание зверя"),
            "9": ("самітник-візіонер, пошук істини, вогонь вогнища",
                  "hermit-visionary, quest for truth, fire of the hearth",
                  "отшельник-визионер, поиск истины, огонь очага"),
            "10": ("колесо року, поворот долі, цикли неба",
                   "wheel of the year, turn of fate, cycles of the sky",
                   "колесо года, поворот судьбы, циклы неба"),
            "11": ("ваги істини, рівновага духу, чесний суд",
                   "scales of truth, spirit balance, honest judgment",
                   "весы истины, равновесие духа, честный суд"),
            "12": ("підвішений в небі, жертва духам, інший зір",
                   "suspended in the sky, sacrifice to spirits, another sight",
                   "подвешенный в небе, жертва духам, иное зрение"),
            "13": ("танок переходу, смерть старої шкури, переродження",
                   "dance of transition, death of the old skin, rebirth",
                   "танец перехода, смерть старой шкуры, перерождение"),
            "14": ("змішування стихій, зберігач міри, потік часу",
                   "blending of elements, keeper of measure, flow of time",
                   "смешение стихий, хранитель меры, поток времени"),
            "15": ("спокуса духу, кайдани страху, випробування бачення",
                   "temptation of spirit, chains of fear, testing the vision",
                   "искушение духа, кандалы страха, испытание видения"),
            "16": ("розкол маятника, струс стійбища, вихід правди",
                   "crack in the world-pole, upheaval of the camp, truth emerging",
                   "разлом мировой оси, потрясение стойбища, выход правды"),
            "17": ("зірка-дух-надія, зцілення, провідна зірка",
                   "star-spirit of hope, healing, guiding star",
                   "звезда-дух-надежда, исцеление, путеводная звезда"),
            "18": ("нічна країна духів, сни, поріг сну і яви",
                   "night land of spirits, dreams, threshold of sleep and waking",
                   "ночная страна духов, сны, порог сна и яви"),
            "19": ("сонце-тотем, тепло роду, ясність дня",
                   "sun-totem, warmth of the clan, clarity of day",
                   "солнце-тотем, тепло рода, ясность дня"),
            "20": ("поклик предків, оновлення, підсумок обряду",
                   "call of ancestors, renewal, summing up the rite",
                   "зов предков, обновление, итог обряда"),
            "21": ("сяюче коло світу, завершення видіння, єдність усього",
                   "radiant world circle, completion of the vision, unity of all",
                   "сияющий круг мира, завершение видения, единство всего"),
        },
        "suit_flavor": {
            "wands": ("жива стріла", "living arrow", "живая стрела"),
            "cups": ("чаша роси", "cup of dew", "чаша росы"),
            "swords": ("перо орла", "eagle feather", "перо орла"),
            "pentacles": ("плід землі", "fruit of the earth", "плод земли"),
        },
    },
    "goldencat": {
        "name_uk": "Таро Золотого Чорного Кота (навчальне)",
        "name_en": "Golden Black Cat Tarot (learning)",
        "name_ru": "Таро Золотого Черного Кота (обучающая)",
        "author": "AI-Arcanum (навчальна колода)",
        "publisher": "Königsfurt-Urania", "year": 2022,
        "source": "https://www.usgamesinc.com/golden-black-cat-tarot",
        "description": ("Навчальний аналог колоди «Golden Black Cat Tarot» "
                        "(Helena de Almeida, Königsfurt-Urania, 2022): 78 карт "
                        "класичного Райдера–Вейта, де персонажів заступають "
                        "граційні чорні коти з золотим акцентом. Значення — "
                        "власний переказ; ілюстрації процедурні."),
        "composition": ("78 карт: 22 Старших + 56 Молодших (4 масті × 14). "
                        "Тема — котяча грація, інтуїція й незалежність. "
                        "Розклад «Котяча лапка»: настрій / обережність / крок."),
        "majors": {
            "0": ("котеня-безтурботник, стрибок у нове, довіра інстинкту",
                  "carefree kitten, a leap into the new, trusting instinct",
                  "котенок-беззаботник, прыжок в новое, доверие инстинкту"),
            "1": ("кіт-чаклун, спритність лап, виявлення волі",
                  "cat-magician, dexterity of paws, manifesting will",
                  "кот-волшебник, ловкость лап, проявление воли"),
            "2": ("кішка-містик, нічна інтуїція, приховане знання",
                  "cat-mystic, nocturnal intuition, hidden knowledge",
                  "кошка-мистик, ночная интуиция, сокровенное знание"),
            "3": ("кішка-мати, тепло, достаток дому",
                  "mother cat, warmth, abundance of home",
                  "кошка-мать, тепло, изобилие дома"),
            "4": ("кіт-господар території, межа, надійна опора",
                  "cat-lord of the territory, boundary, steady foundation",
                  "кот-хозяин территории, граница, надежная опора"),
            "5": ("кіт-наставник, котяча мудрість, звичаї",
                  "cat-mentor, feline wisdom, old ways",
                  "кот-наставник, кошачья мудрость, обычаи"),
            "6": ("два коти, вибір серця, єднання поглядів",
                  "two cats, choice of the heart, gazes united",
                  "два кота, выбор сердца, единение взглядов"),
            "7": ("кіт-переможець, колісниця волі, подолання плутанини",
                  "victorious cat, chariot of will, overcoming confusion",
                  "кот-победитель, колесница воли, преодоление сумятицы"),
            "8": ("оксамитова сила, тиха впевненість, терпіння",
                  "velvet strength, quiet confidence, patience",
                  "бархатная сила, тихая уверенность, терпение"),
            "9": ("кіт-самітник, тиша даху, внутрішній світ",
                  "hermit-cat, silence of the roof, inner world",
                  "кот-отшельник, тишина крыши, внутренний мир"),
            "10": ("колесо котячої долі, поворот, дев'ять життів",
                   "wheel of feline fate, a turn, nine lives",
                   "колесо кошачьей судьбы, поворот, девять жизней"),
            "11": ("ваги котячої справедливості, чесність, рівновага",
                   "scales of feline justice, honesty, balance",
                   "весы кошачьей справедливости, честность, равновесие"),
            "12": ("кіт, що завмер, пауза інстинкту, інший погляд",
                   "the cat poised still, pause of instinct, another view",
                   "замерший кот, пауза инстинкта, иной взгляд"),
            "13": ("линяння старого, зміна хутра, оновлення",
                   "shedding the old, change of coat, renewal",
                   "линька старого, смена шерсти, обновление"),
            "14": ("кіт-міря, рівновага ласощів, терпляче біля дверей",
                   "cat of measure, balance of treats, patient at the door",
                   "кот-мера, равновесие лакомств, терпеливо у дверей"),
            "15": ("кіт-спокусник, гра пристрасті, залежність",
                   "cat-tempter, play of passion, attachment",
                   "кот-искуситель, игра страсти, привязанность"),
            "16": ("перегорнута миска, струс дому, вивільнення",
                   "upset bowl, upheaval of home, release",
                   "опрокинутая миска, потрясение дома, освобождение"),
            "17": ("кіт біля вікна зірок, надія, ясність ночі",
                   "cat at the starry window, hope, clarity of night",
                   "кот у окна со звёздами, надежда, ясность ночи"),
            "18": ("місячна кішка, сни, таємниці покрівель",
                   "moon cat, dreams, secrets of rooftops",
                   "лунная кошка, сны, тайны крыш"),
            "19": ("сонячний кіт, тепло, явна радість",
                   "sunny cat, warmth, open joy",
                   "солнечный кот, тепло, явная радость"),
            "20": ("поклик кішки, пробудження, підсумок досвіду",
                   "call of the cat, awakening, summing up experience",
                   "зов кошки, пробуждение, итог опыта"),
            "21": ("кіт, що осягнув свій хвіст, цілісність, довершеність",
                   "cat grasping its tail, wholeness, completion",
                   "кот, постигший свой хвост, целостность, завершённость"),
        },
        "suit_flavor": {
            "wands": ("іскра грайливості", "spark of playfulness", "искра игривости"),
            "cups": ("чаша молока", "bowl of milk", "чаша молока"),
            "swords": ("кіготь-меч", "claw-sword", "коготь-меч"),
            "pentacles": ("золота подушечка", "golden paw pad", "золотая подушечка"),
        },
    },
    "folklore": {
        "name_uk": "Фольклорне таро (навчальне)",
        "name_en": "Folklore Tarot (learning)",
        "name_ru": "Фольклорное таро (обучающая)",
        "author": "AI-Arcanum (навчальна колода)",
        "publisher": "U.S. Games", "year": 2023,
        "source": "https://www.usgamesinc.com/folklore-tarot",
        "description": ("Навчальний аналог колоди «Folklore Tarot» (Rowan "
                        "Ortins, U.S. Games, 2023): 78 карт класичного Райдера–"
                        "Вейта у світі світової міфології; персонажі Старших і "
                        "двору — герої легенд, молодші оздоблені квітами. "
                        "Значення — власний переказ; ілюстрації процедурні."),
        "composition": ("78 карт: 22 Старших + 56 Молодших (4 масті × 14). "
                        "Тема — міфи і легенди народів світу, спільні архетипи. "
                        "Розклад «Стежка легенд»: покликання / випробування / дар."),
        "majors": {
            "0": ("мандрівець легенд, перший крок на стежці, довіра казці",
                  "legend-wanderer, first step on the path, trusting the tale",
                  "странник легенд, первый шаг на тропе, доверие сказке"),
            "1": ("майстер-трикстер, мистецтво знаку, творення",
                  "master-trickster, art of the sign, creation",
                  "мастер-трикстер, искусство знака, творение"),
            "2": ("жриця-оракул, таємне знання, голос віщого",
                  "priestess-oracle, hidden knowledge, voice of the seer",
                  "жрица-оракул, тайное знание, голос вещей"),
            "3": ("богиня-мати, родючість, дари землі",
                  "mother goddess, fertility, gifts of the earth",
                  "богиня-мать, плодородие, дары земли"),
            "4": ("цар-законодавець, порядок, міць домів",
                  "king-lawgiver, order, might of thrones",
                  "царь-законодатель, порядок, мощь престолов"),
            "5": ("жрець-сказитель, традиція, переданий міф",
                  "priest-storyteller, tradition, inherited myth",
                  "жрец-сказитель, традиция, переданный миф"),
            "6": ("герой і героїня, союз доль, вибір серця",
                  "hero and heroine, joining of fates, heart's choice",
                  "герой и героиня, союз судеб, выбор сердца"),
            "7": ("герой на колісниці, перемога, шлях крізь дива",
                  "hero on a chariot, victory, road through wonders",
                  "герой на колеснице, победа, путь сквозь чудеса"),
            "8": ("укротитель звіра, лагідна міць, відвага",
                  "tamer of the beast, gentle might, courage",
                  "укротитель зверя, нежная мощь, отвага"),
            "9": ("самітник-мудрець, ліхтар знання, пошук істини",
                  "hermit-sage, lantern of knowledge, search for truth",
                  "отшельник-мудрец, светильник знания, поиск истины"),
            "10": ("колесо доль, нитки Мойр, поворот часу",
                   "wheel of destinies, threads of the Fates, turn of time",
                   "колесо судеб, нити Мойр, поворот времени"),
            "11": ("ваги Феміди, чесний суд, рівновага",
                   "scales of Themis, honest judgment, balance",
                   "весы Фемиды, честный суд, равновесие"),
            "12": ("повішений мудрець, жертва заради зору, інший бік",
                   "hanged sage, sacrifice for sight, the other side",
                   "повешенный мудрец, жертва ради зрения, иная сторона"),
            "13": ("змія, що линяє, кінець однієї байки, новий початок",
                   "shedding serpent, end of one tale, a new beginning",
                   "линяющая змея, конец одной басни, новое начало"),
            "14": ("алхімік-міря, сплав стихій, терпеливе злиття",
                   "alchemist of measure, blending of elements, patient fusion",
                   "алхимик-мера, сплав стихий, терпеливое слияние"),
            "15": ("лукавий дух, пастка бажань, випробування",
                   "tricky spirit, trap of desires, a test",
                   "лукавый дух, ловушка желаний, испытание"),
            "16": ("упала вежа казки, крах ілюзій, правда з-під руїн",
                   "fallen tower of the tale, collapse of illusions, truth from ruins",
                   "упавшая башня сказки, крушение иллюзий, правда из-под руин"),
            "17": ("зоря-путеводка, надія мандрівця, зцілення міфом",
                   "guiding star, wanderer's hope, healing through myth",
                   "звезда-путеводительница, надежда странника, исцеление мифом"),
            "18": ("місячні води, сновидіння, межа світів",
                   "moonlit waters, dreams, border of worlds",
                   "лунные воды, сновидения, граница миров"),
            "19": ("сонячний герой, слава, явна правда",
                   "solar hero, glory, plain truth",
                   "солнечный герой, слава, явная правда"),
            "20": ("поклик рога, пробудження, підсумок легенди",
                   "call of the horn, awakening, summing up the legend",
                   "зов рога, пробуждение, итог легенды"),
            "21": ("весленський вузол світів, завершення, єдність міфів",
                   "universal knot of worlds, completion, unity of myths",
                   "вселенский узел миров, завершение, единство мифов"),
        },
        "suit_flavor": {
            "wands": ("жезл сказителя", "bard's staff", "жезл сказителя"),
            "cups": ("чаша легенд", "cup of legends", "чаша легенд"),
            "swords": ("меч героя", "hero's blade", "меч героя"),
            "pentacles": ("карбована казка", "minted tale", "чеканная сказка"),
        },
    },
}