# -*- coding: utf-8 -*-
"""Значения младших арканов Кубков (Cups, стихия Воды)."""
CUPS = {
    "Cups-01": {
        "ru": {
            "reversed": "Заблокированные чувства, творческая сухость, закрытое сердце.",
            "love": "Прямо — изобилие чувства, новая любовь, эмоциональный расцвет. Перевёрнуто — подавленные эмоции, эмоциональная холодность.",
            "career": "Прямо — вдохновение, творческий поток, радость работы. Перевёрнуто — выгорание, творческий вакуум.",
            "health": "Прямо — эмоциональное восстановление, наполненность. Перевёрнуто — эмоциональный спад, зажим в теле.",
            "spirituality": "Прямо — полнота сердца, благодать, открытый поток. Перевёрнуто — сухое сердце, отрезанная интуиция.",
        },
        "uk": {
            "reversed": "Заблоковані почуття, творча сухість, закрите серце.",
            "love": "Прямо — достаток почуття, нове кохання, емоційний розквіт. Перевернуто — пригнічені емоції, емоційна холодність.",
            "career": "Прямо — натхнення, творчий потік, радість роботи. Перевернуто — вигорання, творчий вакуум.",
            "health": "Прямо — емоційне відновлення, наповненість. Перевернуто — емоційний спад, затиск у тілі.",
            "spirituality": "Прямо — повнота серця, благодать, відкритий потік. Перевернуто — сухе серце, відрізана інтуїція.",
        },
        "en": {
            "reversed": "Blocked feelings, creative drought, a closed heart.",
            "love": "Upright — an abundance of love, new romance, emotional blossoming. Reversed — suppressed emotions, emotional coldness.",
            "career": "Upright — inspiration, creative flow, joy in work. Reversed — burnout, a creative vacuum.",
            "health": "Upright — emotional recovery, fullness. Reversed — emotional dip, tension held in the body.",
            "spirituality": "Upright — fullness of heart, grace, an open stream. Reversed — a dry heart, intuition cut off.",
        },
    },
    "Cups-02": {
        "ru": {
            "reversed": "Разлад, взаимное недопонимание, разрыв связи.",
            "love": "Прямо — взаимность, союз на равных, влюблённость. Перевёрнуто — разлад, один тянет, другой отстраняется.",
            "career": "Прямо — партнёрство, соглашение, взаимовыгодный союз. Перевёрнуто — разногласия в партнёрстве, работа по принуждению.",
            "health": "Прямо — гармония, покой, баланс систем. Перевёрнуто — разбалансировка, напряжение в теле.",
            "spirituality": "Прямо — союз души и разума, примирение противоположностей. Перевернуто — раздвоенность, отказ от союза с собой.",
        },
        "uk": {
            "reversed": "Розлад, взаємне нерозуміння, розрив зв'язку.",
            "love": "Прямо — взаємність, союз на рівних, закоханість. Перевернуто — розлад, один тягне, інший відсторонюється.",
            "career": "Прямо — партнерство, згода, взаємовигідний союз. Перевернуто — розбіжності в партнерстві, робота з примусу.",
            "health": "Прямо — гармонія, спокій, баланс систем. Перевернуто — розбалансування, напруга в тілі.",
            "spirituality": "Прямо — союз душі й розуму, примирення протилежностей. Перевернуто — роздвоєність, відмова від союзу із собою.",
        },
        "en": {
            "reversed": "Discord, mutual misunderstanding, a severed connection.",
            "love": "Upright — mutuality, an equal union, falling in love. Reversed — discord, one pulling, the other withdrawing.",
            "career": "Upright — partnership, agreement, a mutually beneficial union. Reversed — disagreements in partnership, work under duress.",
            "health": "Upright — harmony, calm, balanced systems. Reversed — imbalance, tension in the body.",
            "spirituality": "Upright — union of soul and mind, reconciling opposites. Reversed — being torn, refusal to unite with yourself.",
        },
    },
    "Cups-03": {
        "ru": {
            "reversed": "Дружба под вопросом, увлечение бокалом, избыточность.",
            "love": "Прямо — радость в компании, романтика в кругу друзей. Перевёрнуто — вечеринка вместо чувств, избыток.",
            "career": "Прямо — командный успех, празднование результата. Перевёрнуто — кумовство, праздность, сплетни.",
            "health": "Прямо — восстановление в компании, радость жизни. Перевёрнуто — аппетит сверх меры, злоупотребления.",
            "spirituality": "Прямо — общность, праздник души, благодарение. Перевёрнуто — поверхностная духовность «за компанию».",
        },
        "uk": {
            "reversed": "Дружба під питанням, захоплення чаркою, надмірність.",
            "love": "Прямо — радість у компанії, романтика в колі друзів. Перевернуто — вечірка замість почуттів, надмір.",
            "career": "Прямо — командний успіх, святкування результату. Перевернуто — кумівство, ледарство, плітки.",
            "health": "Прямо — відновлення в компанії, радість життя. Перевернуто — апетит понад міру, зловживання.",
            "spirituality": "Прямо — спільність, свято душі, вдячність. Перевернуто — поверхнева духовність «за компанію».",
        },
        "en": {
            "reversed": "Friendship in question, overindulgence, excess.",
            "love": "Upright — joy with friends, romance within a circle. Reversed — a party instead of feelings, excess.",
            "career": "Upright — team success, celebrating the result. Reversed — cronyism, idleness, gossip.",
            "health": "Upright — recovery in company, joy of life. Reversed — excess appetite, overindulgence.",
            "spirituality": "Upright — community, a feast of the soul, gratitude. Reversed — shallow spirituality, going along with the crowd.",
        },
    },
    "Cups-04": {
        "ru": {
            "reversed": "Пробуждение от апатии, новые возможности, рассеянность уходит.",
            "love": "Прямо — неудовлетворённость имеющимся, мечты вместо действий. Перевёрнуто — выход из хандры, замечание подарка судьбы.",
            "career": "Прямо — скука, рутина, упускаемые предложения. Перевёрнуто — новый интерес, принятие предложения.",
            "health": "Прямо — апатия, застой, «мне всё равно». Перевёрнуто — возврат мотивации, движение.",
            "spirituality": "Прямо — духовная скука, созерцание без действия. Перевёрнуто — стыд за неоценённое чудо, пробуждение.",
        },
        "uk": {
            "reversed": "Пробудження від апатії, нові можливості, розсіяність минає.",
            "love": "Прямо — незадоволеність наявним, мрії замість дій. Перевернуто — вихід із хандри, помічання подарунка долі.",
            "career": "Прямо — нудьга, рутина, пропущені пропозиції. Перевернуто — новий інтерес, прийняття пропозиції.",
            "health": "Прямо — апатія, застій, «мені байдуже». Перевернуто — повернення мотивації, рух.",
            "spirituality": "Прямо — духовна нудьга, споглядання без дії. Перевернуто — сором за неоцінене диво, пробудження.",
        },
        "en": {
            "reversed": "Waking from apathy, new opportunities, distraction fading.",
            "love": "Upright — dissatisfaction with what's there, dreaming instead of acting. Reversed — coming out of a slump, noticing a gift of fate.",
            "career": "Upright — boredom, routine, missed offers. Reversed — new interest, taking an offer.",
            "health": "Upright — apathy, stagnation, 'I don't care'. Reversed — motivation returns, movement.",
            "spirituality": "Upright — spiritual boredom, contemplation without action. Reversed — regret over an unvalued miracle, awakening.",
        },
    },
    "Cups-05": {
        "ru": {
            "reversed": "Примирение, выход из траура, замечание двух кубков, что остались.",
            "love": "Прямо — сожаление о потерянном, хождение по своим же ранам. Перевёрнуто — отпускание прошлого, готовность любить снова.",
            "career": "Прямо — разочарование, провал «части плана». Перевёрнуто — пересборка, учёт ошибок, движение дальше.",
            "health": "Прямо — эмоциональная боль, печаль в теле. Перевёрнуто — выход из печали, восстановление.",
            "spirituality": "Прямо — оплакивание утрат, глубина чувства. Перевёрнуто — просветление горя, жизнь после утраты.",
        },
        "uk": {
            "reversed": "Примирення, вихід із трауру, помічання двох кубків, що лишилися.",
            "love": "Прямо — жаль про втрачене, ходіння по власних ранах. Перевернуто — відпускання минулого, готовність кохати знову.",
            "career": "Прямо — розчарування, провал «частини плану». Перевернуто — перезбірка, врахування помилок, рух далі.",
            "health": "Прямо — емоційний біль, печаль у тілі. Перевернуто — вихід із печалі, відновлення.",
            "spirituality": "Прямо — оплакування втрат, глибина почуття. Перевернуто — просвітлення горя, життя після втрати.",
        },
        "en": {
            "reversed": "Reconciliation, coming out of mourning, noticing the two cups left.",
            "love": "Upright — regret over loss, picking at old wounds. Reversed — letting go of the past, ready to love again.",
            "career": "Upright — disappointment, part of the plan failing. Reversed — reassembling, learning from mistakes, moving on.",
            "health": "Upright — emotional pain, sorrow in the body. Reversed — leaving sorrow behind, recovery.",
            "spirituality": "Upright — mourning losses, depth of feeling. Reversed — grief turning to light, life after loss.",
        },
    },
    "Cups-06": {
        "ru": {
            "reversed": "Жизнь воспоминаниями, ностальгия-ловушка, застревание в детстве.",
            "love": "Прямо — нежные воспоминания, чистая привязанность, возвращение. Перевёрнуто — жить прошлым, идеализация бывшего.",
            "career": "Прямо — приятное сотрудничество, помощь по-дружески. Перевёрнуто — держаться за старые модели, страх нового.",
            "health": "Прямо — детское здоровье, тепло, опора на корни. Перевёрнуто — регрессия, «детские» болезни из прошлого.",
            "spirituality": "Прямо — связь с детством духа, чистота, корни. Перевёрнуто — побег в детство, отказ расти.",
        },
        "uk": {
            "reversed": "Життя спогадами, ностальгія-пастка, застрягання в дитинстві.",
            "love": "Прямо — ніжні спогади, чиста прив'язаність, повернення. Перевернуто — жити минулим, ідеалізація колишнього.",
            "career": "Прямо — приємна співпраця, дружня допомога. Перевернуто — триматися старих моделей, страх нового.",
            "health": "Прямо — дитяче здоров'я, тепло, опора на коріння. Перевернуто — регресія, «дитячі» хвороби з минулого.",
            "spirituality": "Прямо — зв'язок із дитинством духу, чистота, коріння. Перевернуто — втеча в дитинство, відмова зростати.",
        },
        "en": {
            "reversed": "Living in memories, nostalgia as a trap, stuck in childhood.",
            "love": "Upright — tender memories, pure attachment, a return. Reversed — living in the past, idealising an ex.",
            "career": "Upright — pleasant cooperation, friendly help. Reversed — clinging to old models, fear of the new.",
            "health": "Upright — childhood health, warmth, roots as a foundation. Reversed — regression, 'childhood' ailments from the past.",
            "spirituality": "Upright — the soul's childhood, purity, roots. Reversed — escape into childhood, refusing to grow.",
        },
    },
    "Cups-07": {
        "ru": {
            "reversed": "Прозрение, выбор реальности, отказ от миражей.",
            "love": "Прямо — множество вариантов, мечтания о «принце», идеалы. Перевёрнуто — выбор реального партнёра, отказ от фантазий.",
            "career": "Прямо — много идей, выбор направления, амбиции-облака. Перевёрнуто — реализация одного, отрезвление планов.",
            "health": "Прямо — поиск чудо-средства, много режимов сразу. Перевёрнуто — выбор реальной терапии, отказ от иллюзий о здоровье.",
            "spirituality": "Прямо — богатство духовных образов, видения. Перевёрнуто — концентрация, отсев миражей.",
        },
        "uk": {
            "reversed": "Прозріння, вибір реальності, відмова від міражів.",
            "love": "Прямо — безліч варіантів, мрії про «принца», ідеали. Перевернуто — вибір реального партнера, відмова від фантазій.",
            "career": "Прямо — багато ідей, вибір напряму, амбіції-хмари. Перевернуто — реалізація одного, протверезіння планів.",
            "health": "Прямо — пошук чудо-засобу, багато режимів одразу. Перевернуто — вибір реальної терапії, відмова від ілюзій про здоров'я.",
            "spirituality": "Прямо — багатство духовних образів, видіння. Перевернуто — концентрація, відсів міражів.",
        },
        "en": {
            "reversed": "Insight, choosing reality, refusing mirages.",
            "love": "Upright — many options, dreaming of a prince, ideals. Reversed — choosing a real partner, dropping fantasies.",
            "career": "Upright — many ideas, choosing a direction, cloud ambitions. Reversed — realising one, plans sobering up.",
            "health": "Upright — hunting for a miracle cure, many regimes at once. Reversed — choosing real therapy, dropping health illusions.",
            "spirituality": "Upright — rich spiritual imagery, visions. Reversed — concentration, filtering out mirages.",
        },
    },
    "Cups-08": {
        "ru": {
            "reversed": "Боязнь бросить, возвращение к знакомому, тело-привычка.",
            "love": "Прямо — уход из неудовлетворяющих отношений, поиск большего. Перевёрнуто — страх уйти, возврат к прежнему.",
            "career": "Прямо — оставить место ради мечты, движения вперёд. Перевёрнуто — нерешительность в смене работы, «а вдруг».",
            "health": "Прямо — смена образа жизни, новый режим. Перевёрнуто — откат к старым привычкам, страх экспериментов.",
            "spirituality": "Прямо — духовный поиск через перемены, оставить насиженное. Перевёрнуто — страх духовного путешествия, держаться за знакомое.",
        },
        "uk": {
            "reversed": "Боязнь покинути, повернення до знайомого, звичка-тіло.",
            "love": "Прямо — вихід із незадовільних стосунків, пошук більшого. Перевернуто — страх піти, повернення до колишнього.",
            "career": "Прямо — залишити місце заради мрії, рух уперед. Перевернуто — нерішучість у зміні роботи, «а раптом».",
            "health": "Прямо — зміна способу життя, новий режим. Перевернуто — відкат до старих звичок, страх експериментів.",
            "spirituality": "Прямо — духовний пошук через зміни, лишити насиджене. Перевернуто — страх духовної подорожі, триматися за знайоме.",
        },
        "en": {
            "reversed": "Fear of leaving, return to the familiar, habit-bound body.",
            "love": "Upright — leaving unsatisfying relationships, seeking more. Reversed — fear of leaving, returning to the past.",
            "career": "Upright — leaving a place for a dream, moving forward. Reversed — hesitating to change jobs, 'what if'.",
            "health": "Upright — changing lifestyle, a new routine. Reversed — falling back into old habits, fear of experiments.",
            "spirituality": "Upright — spiritual search through change, leaving the settled. Reversed — fear of the spiritual journey, clinging to the familiar.",
        },
    },
    "Cups-09": {
        "ru": {
            "reversed": "Показное счастье, внутренняя пустота, чрезмерность желаний.",
            "love": "Прямо — довольство любовью, материальное удобство в паре. Перевёрнуто — роскошь вместо чувств, жалоба под вуалью довольства.",
            "career": "Прямо — успех, комфорт, исполнение желаний. Перевёрнуто — пресыщение, «много, но не то».",
            "health": "Прямо — хорошее самочувствие, комфорт. Перевёрнуто — здоровье по шаблону, игнор глубинных потребностей.",
            "spirituality": "Прямо — благодарность за достаток, изобилие духа. Перевёрнуто — духовная жадность, счастье напоказ.",
        },
        "uk": {
            "reversed": "Показне щастя, внутрішня порожнеча, надмірність бажань.",
            "love": "Прямо — задоволення любов'ю, матеріальний комфорт у парі. Перевернуто — розкіш замість почуттів, скарга під вуаллю задоволення.",
            "career": "Прямо — успіх, комфорт, здійснення бажань. Перевернуто — пересичення, «багато, але не те».",
            "health": "Прямо — добре самопочуття, комфорт. Перевернуто — здоров'я за шаблоном, ігнорування глибинних потреб.",
            "spirituality": "Прямо — вдячність за достаток, достаток духу. Перевернуто — духовна жадібність, щастя напоказ.",
        },
        "en": {
            "reversed": "Ostentatious happiness, inner emptiness, excessive wishes.",
            "love": "Upright — contentment in love, material comfort in the couple. Reversed — luxury instead of feeling, complaint under a veil of satisfaction.",
            "career": "Upright — success, comfort, wishes fulfilled. Reversed — satiety, 'much, but not the right thing'.",
            "health": "Upright — good wellbeing, comfort. Reversed — health by template, ignoring deep needs.",
            "spirituality": "Upright — gratitude for sufficiency, abundance of spirit. Reversed — spiritual greed, happiness on display.",
        },
    },
    "Cups-10": {
        "ru": {
            "reversed": "Разлад в семье, обязанности вместо нежности, «бесконечное счастье» фальшиво.",
            "love": "Прямо — полнота семейной любви, гармония, дом как единое целое. Перевёрнуто — внешняя идиллия, внутренний холод.",
            "career": "Прямо — командная семья, корпоративная гармония. Перевёрнуто — показательный коллектив, невысказанные обиды.",
            "health": "Прямо — стабильное благополучие, эмоциональная опора. Перевёрнуто — напряжение «на виду», скрытый стресс.",
            "spirituality": "Прямо — полнота, радуга, единство. Перевёрнуто — картина-фасад, разорванные связи души.",
        },
        "uk": {
            "reversed": "Розлад у сім'ї, обов'язки замість ніжності, «нескінченне щастя» фальшиве.",
            "love": "Прямо — повнота сімейної любові, гармонія, дім як єдине ціле. Перевернуто — зовнішня ідилія, внутрішній холод.",
            "career": "Прямо — командна сім'я, корпоративна гармонія. Перевернуто — показовий колектив, невисловлені образи.",
            "health": "Прямо — стабільне благополуччя, емоційна опора. Перевернуто — напруга «на виду», прихований стрес.",
            "spirituality": "Прямо — повнота, веселка, єдність. Перевернуто — картина-фасад, розірвані зв'язки душі.",
        },
        "en": {
            "reversed": "Family discord, duty instead of tenderness, 'endless happiness' ring false.",
            "love": "Upright — fullness of family love, harmony, home as one whole. Reversed — an outer idyll, inner cold.",
            "career": "Upright — a team family, corporate harmony. Reversed — an ostentatious team, unspoken grievances.",
            "health": "Upright — steady wellbeing, emotional support. Reversed — visible tension, hidden stress.",
            "spirituality": "Upright — fullness, a rainbow, unity. Reversed — a facade, the soul's bonds torn.",
        },
    },
    "Cups-11": {
        "ru": {
            "reversed": "Эмоциональная незрелость, малыш в чувствах, каприз.",
            "love": "Прямо — свежесть чувств, романтические вести, наивное сердце. Перевёрнуто — инфантильность в паре, обиды по-детски.",
            "career": "Прямо — learning by feeling, предложение/новость в творчестве. Перевёрнуто — непрофессиональная подача, детские обиды на работе.",
            "health": "Прямо — свежесть, лёгкость эмоций, открытость. Перевёрнуто — эмоциональная хрупкость, чувствительность тела.",
            "spirituality": "Прямо — чистота намерения, открытость чуду. Перевёрнуто — наивность вместо веры, ребячливость духа.",
        },
        "uk": {
            "reversed": "Емоційна незрілість, малюк у почуттях, каприз.",
            "love": "Прямо — свіжість почуттів, романтичні вісті, наївне серце. Перевернуто — інфантильність у парі, образи по-дитячому.",
            "career": "Прямо — навчання через відчуття, пропозиція/новина у творчості. Перевернуто — непрофесійна подача, дитячі образи на роботі.",
            "health": "Прямо — свіжість, легкість емоцій, відкритість. Перевернуто — емоційна крихкість, чутливість тіла.",
            "spirituality": "Прямо — чистота наміру, відкритість диву. Перевернуто — наївність замість віри, дитинність духу.",
        },
        "en": {
            "reversed": "Emotional immaturity, a child in matters of feeling, a tantrum.",
            "love": "Upright — freshness of feeling, romantic news, a naive heart. Reversed — infantilism in the couple, childish grudges.",
            "career": "Upright — learning through feeling, news or an offer in creativity. Reversed — unprofessional delivery, childish grievances at work.",
            "health": "Upright — freshness, ease of emotion, openness. Reversed — emotional fragility, bodily sensitivity.",
            "spirituality": "Upright — purity of intention, openness to wonder. Reversed — naivety instead of faith, childishness of spirit.",
        },
    },
    "Cups-12": {
        "ru": {
            "reversed": "Эмоциональные качели, нестабильные чувства, переигранная романтика.",
            "love": "Прямо — предложение руки и сердца, пылкое признание. Перевёрнуто — обещания всерьёз не приняты, каприз страсти.",
            "career": "Прямо — творческое предложение, шанс, романтика идеи. Перевёрнуто — обещания без ресурсов, эмоций больше, чем плана.",
            "health": "Прямо — поток, воодушевление, гармония. Перевёрнуто — перепады настроения, «сердце бьётся не в такт».",
            "spirituality": "Прямо — зов сердца, служение чувству. Перевёрнуто — эмоциональный хаос, страсть, затмевающая дух.",
        },
        "uk": {
            "reversed": "Емоційні гойдалки, нестабільні почуття, переграна романтика.",
            "love": "Прямо — освідчення, палке зізнання. Перевернуто — обіцянки не сприйняті серйозно, каприз пристрасті.",
            "career": "Прямо — творча пропозиція, шанс, романтика ідеї. Перевернуто — обіцянки без ресурсів, емоцій більше, ніж плану.",
            "health": "Прямо — потік, піднесення, гармонія. Перевернуто — перепади настрою, «серце б'ється не в такт».",
            "spirituality": "Прямо — поклик серця, служіння почуттю. Перевернуто — емоційний хаос, пристрасть, що затьмарює дух.",
        },
        "en": {
            "reversed": "Emotional swings, unstable feelings, overplayed romance.",
            "love": "Upright — a proposal, a fiery declaration. Reversed — promises not taken seriously, a whim of passion.",
            "career": "Upright — a creative offer, a chance, the romance of an idea. Reversed — promises without resources, more emotion than plan.",
            "health": "Upright — flow, enthusiasm, harmony. Reversed — mood swings, the heart out of time.",
            "spirituality": "Upright — the heart's call, service to feeling. Reversed — emotional chaos, passion eclipsing the spirit.",
        },
    },
    "Cups-13": {
        "ru": {
            "reversed": "Эмоциональная зависимость, идеализация, поглощение чужими чувствами.",
            "love": "Прямо — глубокая сочувствующая любовь, психологическая близость. Перевёрнуто — слияние до потери себя, слёзы как валюта.",
            "career": "Прямо — работа с людьми, эмпатия, психология/забота. Перевёрнуто — эмоциональный перенос, «спасатель», выгорание от чувств других.",
            "health": "Прямо — чувствительность как дар, интуиция тела. Перевёрнуто — эмоциональная дестабилизация, склонность к тревогам.",
            "spirituality": "Прямо — внутреннее видение, глубина интуиции, служение. Перевёрнуто — растворение в чужих переживаниях, потеря себя.",
        },
        "uk": {
            "reversed": "Емоційна залежність, ідеалізація, поглинання чужими почуттями.",
            "love": "Прямо — глибока співчутлива любов, психологічна близькість. Перевернуто — злиття до втрати себе, сльози як валюта.",
            "career": "Прямо — робота з людьми, емпатія, психологія/турбота. Перевернуто — емоційний перенос, «рятівник», вигорання від чужих почуттів.",
            "health": "Прямо — чутливість як дар, інтуїція тіла. Перевернуто — емоційна дестабілізація, схильність до тривог.",
            "spirituality": "Прямо — внутрішнє бачення, глибина інтуїції, служіння. Перевернуто — розчинення в чужих переживаннях, втрата себе.",
        },
        "en": {
            "reversed": "Emotional dependence, idealisation, absorbed by others' feelings.",
            "love": "Upright — deep, compassionate love, psychological intimacy. Reversed — merging until you lose yourself, tears as currency.",
            "career": "Upright — work with people, empathy, psychology/care work. Reversed — emotional transference, the rescuer, burnout from others' feelings.",
            "health": "Upright — sensitivity as a gift, bodily intuition. Reversed — emotional instability, tendency to anxiety.",
            "spirituality": "Upright — inner vision, depth of intuition, service. Reversed — dissolving into others' experiences, losing yourself.",
        },
    },
    "Cups-14": {
        "ru": {
            "reversed": "Эмоциональная отстранённость, манипуляция чувствами, холодный дипломат.",
            "love": "Прямо — зрелая сострадательная любовь, стабильная нежность. Перевёрнуто — эмоциональная недоступность, чувства «по графику».",
            "career": "Прямо — дипломатия, урегулирование, мудрое ведение. Перевёрнуто — холодный расчёт, манипуляции, подавление чувств.",
            "health": "Прямо — эмоциональная стабильность, уравновешенность. Перевёрнуто — подавление эмоций, «замороженное» тело.",
            "spirituality": "Прямо — мудрость сердца, сострадание, глубокие воды. Перевёрнуто — духовная высокомерность, сердце в броне.",
        },
        "uk": {
            "reversed": "Емоційна відстороненість, маніпуляція почуттями, холодний дипломат.",
            "love": "Прямо — зріле співчутливе кохання, стабільна ніжність. Перевернуто — емоційна недоступність, почуття «за графіком».",
            "career": "Прямо — дипломатія, врегулювання, мудре ведення. Перевернуто — холодний розрахунок, маніпуляції, придушення почуттів.",
            "health": "Прямо — емоційна стабільність, урівноваженість. Перевернуто — придушення емоцій, «заморожене» тіло.",
            "spirituality": "Прямо — мудрість серця, співчуття, глибокі води. Перевернуто — духовна зарозумілість, серце в броні.",
        },
        "en": {
            "reversed": "Emotional detachment, manipulating feelings, a cold diplomat.",
            "love": "Upright — mature, compassionate love, steady tenderness. Reversed — emotional unavailability, feelings on schedule.",
            "career": "Upright — diplomacy, mediation, wise leadership. Reversed — cold calculation, manipulation, suppressed feeling.",
            "health": "Upright — emotional stability, balance. Reversed — repressed emotions, a frozen body.",
            "spirituality": "Upright — wisdom of the heart, compassion, deep waters. Reversed — spiritual arrogance, a heart in armour.",
        },
    },
}