# -*- coding: utf-8 -*-
"""Глубокая проработка значений всех 78 карт RWS.

Структура: {"0": {"ru": {...}, "uk": {...}, "en": {...}}, ...}
Внутренний словарь: {"reversed": str, "love": str, "career": str,
                     "health": str, "spirituality": str}
Прямое значение остаётся в existing meaning_general; здесь — перевёрнутое
и четыре сферы (любовь / карьера / здоровье / духовность). Тексты — собственные
учебные формулировки по мотивам общепринятых RWS-трактовок.
"""
MAJORS = {
    "0": {
        "ru": {
            "reversed": "Безрассудность, задержки, наивность, страх перед прыжком в неизвестность.",
            "love": "Прямо — лёгкое флиртование, новое начало без обязательств. Перевёрнуто — страх близости, несерьёзность партнёра.",
            "career": "Прямо — старт проекта, творческий риск, «прыжок в омут». Перевёрнуто — необдуманные решения, хаос, недоведение дел до конца.",
            "health": "Прямо — заряд жизненной энергии, лёгкость, движение к здоровью. Перевёрнуто — безалаберность к своему телу, скачки формы.",
            "spirituality": "Прямо — доверие пути, открытость неизведанному, вера в подсказки мира. Перевёрнуто — потеря ориентира, иллюзии свободы.",
        },
        "uk": {
            "reversed": "Безрозсудність, затримки, наївність, страх перед стрибком у невідоме.",
            "love": "Прямо — легкий флірт, новий початок без зобов’язань. Перевернуто — страх близькості, несерйозність партнера.",
            "career": "Прямо — старт проєкту, творчий ризик, «стрибок у вир». Перевернуто — необдумані рішення, хаос, незавершені справи.",
            "health": "Прямо — заряд життєвої енергії, легкість, рух до здоров’я. Перевернуто — недбалість до свого тіла, коливання форми.",
            "spirituality": "Прямо — довіра шляху, відкритість незвіданому, віра в підказки світу. Перевернуто — втрата орієнтиру, ілюзії свободи.",
        },
        "en": {
            "reversed": "Recklessness, delays, naivety, fear of leaping into the unknown.",
            "love": "Upright — light flirting, a fresh start without commitments. Reversed — fear of intimacy, a partner's frivolity.",
            "career": "Upright — launching a project, creative risk, jumping in head first. Reversed — rash decisions, chaos, unfinished tasks.",
            "health": "Upright — a surge of vitality, lightness, moving toward health. Reversed — carelessness about your body, fluctuating form.",
            "spirituality": "Upright — trusting the path, openness to the unknown, believing in the world's signs. Reversed — losing direction, illusions of freedom.",
        },
    },
    "I": {
        "ru": {
            "reversed": "Манипуляция, хитрость, нечестная игра, распыление талантов.",
            "love": "Прямо — обаяние, активное привлечение партнёра, страсть. Перевёрнуто — игра, обман чувств, желание управлять.",
            "career": "Прямо — гениальное исполнение, владение инструментами, инициатива. Перевёрнуто — спекуляция, махинации, обещания без результата.",
            "health": "Прямо — осознанный контроль, восстановление через навык (массаж, спорт). Перевёрнуто — самолечение вслепую, игнорирование симптомов.",
            "spirituality": "Прямо — сила намерения, превращение мысли в действие. Перевёрнуто — эго вместо воли, обман самого себя.",
        },
        "uk": {
            "reversed": "Маніпуляція, хитрість, нечесна гра, розпорошення талантів.",
            "love": "Прямо — чарівність, активне залучення партнера, пристрасть. Перевернуто — гра, обман почуттів, бажання керувати.",
            "career": "Прямо — геніальне виконання, володіння інструментами, ініціатива. Перевернуто — спекуляція, махінації, обіцянки без результату.",
            "health": "Прямо — усвідомлений контроль, відновлення через навички (масаж, спорт). Перевернуто — самолікування наосліп, ігнорування симптомів.",
            "spirituality": "Прямо — сила наміру, перетворення думки на дію. Перевернуто — его замість волі, обман самого себе.",
        },
        "en": {
            "reversed": "Manipulation, cunning, foul play, squandering talents.",
            "love": "Upright — charm, actively attracting a partner, passion. Reversed — game-playing, deceitful feelings, wanting to control.",
            "career": "Upright — brilliant execution, mastery of tools, initiative. Reversed — speculation, scheming, promises without results.",
            "health": "Upright — conscious control, recovery through skill (massage, sport). Reversed — blind self-treatment, ignoring symptoms.",
            "spirituality": "Upright — the power of intention, turning thought into action. Reversed — ego instead of will, deceiving yourself.",
        },
    },
    "II": {
        "ru": {
            "reversed": "Скрытые мотивы, вытесненные чувства, поверхностные суждения.",
            "love": "Прямо — глубокая интуитивная связь, тайная симпатия. Перевёрнуто — недоговорённость, охлаждение, секреты в паре.",
            "career": "Прямо — работа с данными, инсайты, конфиденциальность. Перевёрнуто — скрытые конкурентные действия, интуиция подводит.",
            "health": "Прямо — прислушивание к телу, тонкая чувствительность. Перевёрнуто — пренебрежение сигналами тела, тревожность.",
            "spirituality": "Прямо — внутреннее знание, молчаливая медитация, тайны. Перевёрнуто — отрезанность от голоса души, самообман.",
        },
        "uk": {
            "reversed": "Приховані мотиви, витіснені почуття, поверхневі судження.",
            "love": "Прямо — глибокий інтуїтивний зв’язок, таємна симпатія. Перевернуто — недомовленість, охолодження, секрети в парі.",
            "career": "Прямо — робота з даними, інсайти, конфіденційність. Перевернуто — приховані конкурентні дії, інтуїція підводить.",
            "health": "Прямо — прислухання до тіла, тонка чутливість. Перевернуто — нехтування сигналами тіла, тривожність.",
            "spirituality": "Прямо — внутрішнє знання, мовчазна медитація, таємниці. Перевернуто — відірваність від голосу душі, самообман.",
        },
        "en": {
            "reversed": "Hidden motives, repressed feelings, shallow judgements.",
            "love": "Upright — a deep intuitive bond, a secret attraction. Reversed — unspoken tension, cooling off, secrets in the couple.",
            "career": "Upright — working with data, insights, confidentiality. Reversed — hidden competitive moves, intuition misleading you.",
            "health": "Upright — listening to the body, fine sensitivity. Reversed — ignoring the body's signals, anxiety.",
            "spirituality": "Upright — inner knowledge, silent meditation, mysteries. Reversed — cut off from the soul's voice, self-deception.",
        },
    },
    "III": {
        "ru": {
            "reversed": "Зависимость, творческий блок, чрезмерная опека, застой.",
            "love": "Прямо — забота, тепло, рост отношений через нежность. Перевёрнуто — опёка до удушения, ревность, зависимость.",
            "career": "Прямо — плодородие идей, рост проекта, работа с людьми. Перевёрнуто — проект «растёт не туда», перфекционизм.",
            "health": "Прямо — чувствительное восстановление, забота о теле, беременность. Перевёрнуто — переедание, апатия, игнор потребностей тела.",
            "spirituality": "Прямо — связь с природой, материнский принцип, принятие. Перевёрнуто — застревание в эмоциях, потеря связи с землёй.",
        },
        "uk": {
            "reversed": "Залежність, творчий блок, надмірна опіка, застій.",
            "love": "Прямо — турбота, тепло, зростання стосунків через ніжність. Перевернуто — опіка до задухи, ревнощі, залежність.",
            "career": "Прямо — родючість ідей, зростання проєкту, робота з людьми. Перевернуто — проєкт «росте не туди», перфекціонізм.",
            "health": "Прямо — чутливе відновлення, турбота про тіло, вагітність. Перевернуто — переїдання, апатія, ігнорування потреб тіла.",
            "spirituality": "Прямо — зв’язок із природою, материнський принцип, прийняття. Перевернуто — застрягання в емоціях, втрата зв’язку із землею.",
        },
        "en": {
            "reversed": "Dependence, creative block, smothering care, stagnation.",
            "love": "Upright — care, warmth, relationships growing through tenderness. Reversed — suffocating care, jealousy, dependence.",
            "career": "Upright — fertility of ideas, project growth, working with people. Reversed — the project grows the wrong way, perfectionism.",
            "health": "Upright — sensitive recovery, caring for the body, pregnancy. Reversed — overeating, apathy, ignoring the body's needs.",
            "spirituality": "Upright — connection with nature, the maternal principle, acceptance. Reversed — stuck in emotions, losing grounding.",
        },
    },
    "IV": {
        "ru": {
            "reversed": "Тиранство, упрямство, злоупотребление властью, развал структуры.",
            "love": "Прямо — надёжность, защита, стабильный союз. Перевёрнуто — контроль, доминирование, холодность.",
            "career": "Прямо — управление, дисциплина, порядок и лидерство. Перевёрнуто — бюрократия, деспотичный начальник, кризис правил.",
            "health": "Прямо — крепкая структура тела, режим, дисциплина. Перевёрнуто — ригидность, хроническое перенапряжение, давление.",
            "spirituality": "Прямо — порядок как опора, авторитет традиции. Перевёрнуто — закон ради закона, жёсткость вместо мудрости.",
        },
        "uk": {
            "reversed": "Тиранія, впертість, зловживання владою, розвал структури.",
            "love": "Прямо — надійність, захист, стабільний союз. Перевернуто — контроль, домінування, холодність.",
            "career": "Прямо — управління, дисципліна, лад і лідерство. Перевернуто — бюрократія, деспотичний начальник, криза правил.",
            "health": "Прямо — міцна структура тіла, режим, дисципліна. Перевернуто — ригідність, хронічна перенапруга, тиск.",
            "spirituality": "Прямо — порядок як опора, авторитет традиції. Перевернуто — закон заради закону, жорсткість замість мудрості.",
        },
        "en": {
            "reversed": "Tyranny, stubbornness, abuse of power, crumbling structure.",
            "love": "Upright — reliability, protection, a stable union. Reversed — control, dominance, coldness.",
            "career": "Upright — management, discipline, order and leadership. Reversed — bureaucracy, a despotic boss, a crisis of rules.",
            "health": "Upright — a strong body structure, routine, discipline. Reversed — rigidity, chronic strain, pressure.",
            "spirituality": "Upright — order as a foundation, the authority of tradition. Reversed — law for law's sake, rigidness instead of wisdom.",
        },
    },
    "V": {
        "ru": {
            "reversed": "Догматизм, бунт против правил, ложный авторитет.",
            "love": "Прямо — серьёзный союз по традиции, семья, обязательства. Перевёрнуто — свадьба «по накатанной», отношения как обязанность.",
            "career": "Прямо — обучение, наставничество, корпоративная культура. Перевёрнуто — консерватизм, «священная корова», офисная догма.",
            "health": "Прямо — профилактика, проверенные методы, дисциплина. Перевёрнуто — слепое следование непроверенным догмам здоровья.",
            "spirituality": "Прямо — традиция, передача знания, духовный учитель. Перевёрнуто — сектантство, догматизм, страх свободной мысли.",
        },
        "uk": {
            "reversed": "Догматизм, бунт проти правил, хибний авторитет.",
            "love": "Прямо — серйозний союз за традицією, сім’я, зобов’язання. Перевернуто — весілля «за накатаною», стосунки як обов’язок.",
            "career": "Прямо — навчання, наставництво, корпоративна культура. Перевернуто — консерватизм, «священна корова», офісна догма.",
            "health": "Прямо — профілактика, перевірені методи, дисципліна. Перевернуто — сліпа віра в неперевірені догми здоров’я.",
            "spirituality": "Прямо — традиція, передача знання, духовний учитель. Перевернуто — сектантство, догматизм, страх вільної думки.",
        },
        "en": {
            "reversed": "Dogmatism, rebellion against rules, false authority.",
            "love": "Upright — a serious traditional union, family, commitments. Reversed — marriage on autopilot, relationship as duty.",
            "career": "Upright — learning, mentorship, corporate culture. Reversed — conservatism, sacred cows, office dogma.",
            "health": "Upright — prevention, proven methods, discipline. Reversed — blindly following unverified health dogmas.",
            "spirituality": "Upright — tradition, passing on knowledge, a spiritual teacher. Reversed — sectarianism, dogmatism, fear of free thought.",
        },
    },
    "VI": {
        "ru": {
            "reversed": "Дисгармония, хибный выбор, разлад ценностей.",
            "love": "Прямо — настоящая связь, выбор сердца, союз на равных. Перевёрнуто — сомнения, третий лишний, выбор «головой против сердца».",
            "career": "Прямо — союз, синергия, партнёрство с общими ценностями. Перевёрнуто — конфликт интересов, неверные альянсы.",
            "health": "Прямо — гармония тела и духа, баланс нагрузок. Перевёрнуто — рассогласованность ритмов, «разрыв между желанием и делом».",
            "spirituality": "Прямо — выбор по совести, целостность души. Перевёрнуто — внутренний конфликт, раздвоенность.",
        },
        "uk": {
            "reversed": "Дисгармонія, хибний вибір, розлад цінностей.",
            "love": "Прямо — справжній зв’язок, вибір серця, союз на рівних. Перевернуто — сумніви, третій зайвий, вибір «головою проти серця».",
            "career": "Прямо — союз, синергія, партнерство зі спільними цінностями. Перевернуто — конфлікт інтересів, невірні альянси.",
            "health": "Прямо — гармонія тіла й духу, баланс навантажень. Перевернуто — розузгодженість ритмів, «розрив між бажанням і ділом».",
            "spirituality": "Прямо — вибір за совістю, цілісність душі. Перевернуто — внутрішній конфлікт, роздвоєність.",
        },
        "en": {
            "reversed": "Disharmony, a wrong choice, clash of values.",
            "love": "Upright — a real connection, the heart's choice, an equal union. Reversed — doubt, a third wheel, choosing head over heart.",
            "career": "Upright — union, synergy, partnership with shared values. Reversed — conflict of interest, misguided alliances.",
            "health": "Upright — harmony of body and spirit, balanced stress. Reversed — misaligned rhythms, divided between desire and deed.",
            "spirituality": "Upright — choosing by conscience, wholeness of the soul. Reversed — inner conflict, being torn.",
        },
    },
    "VII": {
        "ru": {
            "reversed": "Потеря направления, хаос, неуправляемая спешка.",
            "love": "Прямо — движение к цели, неистовство, совместный рывок. Перевёрнуто — резкие повороты, борьба за контроль в паре.",
            "career": "Прямо — решительный прорыв, победа, умение вести. Перевёрнуто — потеря курса, аварии планов, гонка без руля.",
            "health": "Прямо — высокая работоспособность, движение, спорт. Перевёрнуто — перегрузки, травмы от спешки, энергослив.",
            "spirituality": "Прямо — воля и самоконтроль, править своей колесницей. Перевёрнуто — эго рвёт поводья, жизнь на автопилоте.",
        },
        "uk": {
            "reversed": "Втрата напряму, хаос, некерований поспіх.",
            "love": "Прямо — рух до мети, нестримність, спільний ривок. Перевернуто — різкі повороти, боротьба за контроль у парі.",
            "career": "Прямо — рішучий прорив, перемога, уміння вести. Перевернуто — втрата курсу, аварії планів, гонка без керма.",
            "health": "Прямо — висока працездатність, рух, спорт. Перевернуто — перевантаження, травми від поспіху, злив енергії.",
            "spirituality": "Прямо — воля й самоконтроль, правити своєю колісницею. Перевернуто — его рве повіддя, життя на автопілоті.",
        },
        "en": {
            "reversed": "Losing direction, chaos, ungovernable hurry.",
            "love": "Upright — moving toward a goal, drive, a shared push. Reversed — sharp turns, a struggle for control in the couple.",
            "career": "Upright — a decisive breakthrough, victory, leadership skill. Reversed — losing course, plans crashing, driving without a wheel.",
            "health": "Upright — high performance, movement, sport. Reversed — overload, rush injuries, draining energy.",
            "spirituality": "Upright — will and self-mastery, steering your own chariot. Reversed — ego pulling at the reins, life on autopilot.",
        },
    },
    "VIII": {
        "ru": {
            "reversed": "Самосомнение, выгорание, подавленные эмоции.",
            "love": "Прямо — терпение и нежность, укрощение страстей во имя любви. Перевёрнуто — ревность, усталость, борьба за контроль.",
            "career": "Прямо — выдержка, дипломатия, мягкая сила. Перевёрнуто — неуверенность, поддакивание, выгорание.",
            "health": "Прямо — мягкое восстановление, работа с внутренним напряжением. Перевёрнуто — стресс, нервное истощение, ярость в теле.",
            "spirituality": "Прямо — кротость, обуздание эго силой любви. Перевёрнуто — подавление чувств, сила, обращённая против себя.",
        },
        "uk": {
            "reversed": "Самосумнів, вигорання, пригнічені емоції.",
            "love": "Прямо — терпіння й ніжність, приборкання пристрастей в ім’я любові. Перевернуто — ревнощі, втома, боротьба за контроль.",
            "career": "Прямо — витримка, дипломатія, м’яка сила. Перевернуто — невпевненість, підтакування, вигорання.",
            "health": "Прямо — м’яке відновлення, робота з внутрішнім напруженням. Перевернуто — стрес, нервове виснаження, лють у тілі.",
            "spirituality": "Прямо — лагідність, приборкання его силою любові. Перевернуто — придушення почуттів, сила, спрямована проти себе.",
        },
        "en": {
            "reversed": "Self-doubt, burnout, suppressed emotions.",
            "love": "Upright — patience and tenderness, taming passions for love's sake. Reversed — jealousy, fatigue, a struggle for control.",
            "career": "Upright — endurance, diplomacy, gentle power. Reversed — insecurity, yesmanship, burnout.",
            "health": "Upright — gentle recovery, working with inner tension. Reversed — stress, nervous exhaustion, rage held in the body.",
            "spirituality": "Upright — meekness, taming the ego with love's strength. Reversed — suppressing feelings, strength turned against yourself.",
        },
    },
    "IX": {
        "ru": {
            "reversed": "Изоляция, отчуждение, застревание в одиночестве.",
            "love": "Прямо — осмысленная пауза, зрелость, одиночество как свобода. Перевёрнуто — эмоциональная отстранённость, страх близости.",
            "career": "Прямо — глубинная проработка, экспертиза, работа в тишине. Перевёрнуто — изоляция от команды, выгорание в одиночку.",
            "health": "Прямо — восстановление через покой, сон, рефлексию. Перевёрнуто — одиночество, апатия, пренебрежение здоровьем.",
            "spirituality": "Прямо — внутренний поиск, светчник, ведущий вглубь себя. Перевёрнуто — уход от мира из страха, духовная пустыня.",
        },
        "uk": {
            "reversed": "Ізоляція, відчуження, застрягання в самотності.",
            "love": "Прямо — осмислена пауза, зрілість, самотність як свобода. Перевернуто — емоційна відстороненість, страх близькості.",
            "career": "Прямо — глибинне опрацювання, експертиза, робота в тиші. Перевернуто — ізоляція від команди, вигорання наодинці.",
            "health": "Прямо — відновлення через спокій, сон, рефлексію. Перевернуто — самотність, апатія, нехтування здоров’ям.",
            "spirituality": "Прямо — внутрішній пошук, ліхтар, що веде вглиб себе. Перевернуто — втеча від світу зі страху, духовна пустка.",
        },
        "en": {
            "reversed": "Isolation, alienation, getting stuck in solitude.",
            "love": "Upright — a meaningful pause, maturity, solitude as freedom. Reversed — emotional detachment, fear of intimacy.",
            "career": "Upright — deep work, expertise, working in silence. Reversed — isolation from the team, burning out alone.",
            "health": "Upright — recovery through rest, sleep, reflection. Reversed — loneliness, apathy, neglecting your health.",
            "spirituality": "Upright — inner search, a lantern leading inward. Reversed — running from the world out of fear, a spiritual wasteland.",
        },
    },
    "X": {
        "ru": {
            "reversed": "Неудачный поворот цикла, сопротивление переменам, зависть судьбе.",
            "love": "Прямо — кармическая встреча, судьбоносные обстоятельства. Перевёрнуто — переменчивость чувств, цикл разочарований.",
            "career": "Прямо — удачный поворот, взлёт, везение в timing. Перевёрнуто — застой, упущенный момент, «стук судьбы».",
            "health": "Прямо — циклы восстановления, благоприятный период. Перевёрнуто — сбой биоритмов, новые витки хронической проблемы.",
            "spirituality": "Прямо — принятие циклов судьбы, доверие колесу. Перевёрнуто — жалоба на судьбу, цепляние за прошлое.",
        },
        "uk": {
            "reversed": "Невдалий поворот циклу, опір змінам, заздрість долі.",
            "love": "Прямо — кармічна зустріч, доленосні обставини. Перевернуто — мінливість почуттів, цикл розчарувань.",
            "career": "Прямо — вдалий поворот, зліт, везіння в таймінгу. Перевернуто — застій, втрачений момент, «стукіт долі».",
            "health": "Прямо — цикли відновлення, сприятливий період. Перевернуто — збій біоритмів, нові витки хронічної проблеми.",
            "spirituality": "Прямо — прийняття циклів долі, довіра колесу. Перевернуто — скарга на долю, чіпляння за минуле.",
        },
        "en": {
            "reversed": "A rough turn of the cycle, resisting change, begrudging fate.",
            "love": "Upright — a karmic meeting, fateful circumstances. Reversed — fickle feelings, a cycle of disappointments.",
            "career": "Upright — a fortunate turn, ascent, lucky timing. Reversed — stagnation, a missed moment, fate knocking.",
            "health": "Upright — recovery cycles, a favourable period. Reversed — disrupted biorhythms, new rounds of a chronic issue.",
            "spirituality": "Upright — accepting the cycles of fate, trusting the wheel. Reversed — blaming fate, clinging to the past.",
        },
    },
    "XI": {
        "ru": {
            "reversed": "Несправедливость, предвзятость, уход от ответственности.",
            "love": "Прямо — честный баланс в паре, договорённости, равный вклад. Перевёрнуто — несправедливость, обвинения, односторонние условия.",
            "career": "Прямо — справедливая оценка, право, справедливость в сделках. Перевёрнуто — волокита, ложные обвинения, коррупция.",
            "health": "Прямо — баланс в образе жизни, работа над причинами. Перевёрнуто — недооценка симптомов, «палач собственного здоровья».",
            "spirituality": "Прямо — кармическая справедливость, честность с собой. Перевёрнуто — самооправдание, двойные стандарты.",
        },
        "uk": {
            "reversed": "Несправедливість, упередженість, ухилення від відповідальності.",
            "love": "Прямо — чесний баланс у парі, домовленості, рівний внесок. Перевернуто — несправедливість, звинувачення, односторонні умови.",
            "career": "Прямо — справедлива оцінка, право, справедливість в угодах. Перевернуто — тяганина, хибні звинувачення, корупція.",
            "health": "Прямо — баланс у способі життя, робота над причинами. Перевернуто — недооцінка симптомів, «кат власного здоров’я».",
            "spirituality": "Прямо — кармічна справедливість, чесність із собою. Перевернуто — самовиправдання, подвійні стандарти.",
        },
        "en": {
            "reversed": "Injustice, bias, dodging responsibility.",
            "love": "Upright — an honest balance in the couple, agreements, equal contribution. Reversed — unfairness, accusations, one-sided terms.",
            "career": "Upright — a fair assessment, law, fair dealings. Reversed — delays, false accusations, corruption.",
            "health": "Upright — balance in lifestyle, working on causes. Reversed — underestimating symptoms, being your own health's executioner.",
            "spirituality": "Upright — karmic justice, honesty with yourself. Reversed — self-justification, double standards.",
        },
    },
    "XII": {
        "ru": {
            "reversed": "Бесплодная жертва, затянувшаяся пауза, сопротивление необходимому.",
            "love": "Прямо — любовь-служение, готовность жертвовать ради пары. Перевёрнуто — жертва без смысла, токсичная зависимость.",
            "career": "Прямо — смена угла зрения, пауза для переоценки. Перевёрнуто — стоп, «подвешенный» проект, чувство ловушки.",
            "health": "Прямо — отпускание контроля, восстановление в неподвижности. Перевёрнуто — застой, апатия, ощущение тупика.",
            "spirituality": "Прямо — добровольное посвящение, мудрость жертвы. Перевёрнуто — жертвенность из привычки, нежелание отпускать.",
        },
        "uk": {
            "reversed": "Безплідна жертва, затягнута пауза, опір необхідному.",
            "love": "Прямо — любов-служіння, готовність жертвувати заради пари. Перевернуто — жертва без сенсу, токсична залежність.",
            "career": "Прямо — зміна кута зору, пауза для переоцінки. Перевернуто — стоп, «підвішений» проєкт, відчуття пастки.",
            "health": "Прямо — відпускання контролю, відновлення в нерухомості. Перевернуто — застій, апатія, відчуття глухого кута.",
            "spirituality": "Прямо — добровільне посвячення, мудрість жертви. Перевернуто — жертовність за звичкою, небажання відпускати.",
        },
        "en": {
            "reversed": "Fruitless sacrifice, an overlong pause, resisting the necessary.",
            "love": "Upright — love as service, willing to sacrifice for the couple. Reversed — meaningless sacrifice, toxic attachment.",
            "career": "Upright — a shift of perspective, a pause for reassessment. Reversed — stop, a suspended project, feeling trapped.",
            "health": "Upright — releasing control, recovery in stillness. Reversed — stagnation, apathy, feeling stuck.",
            "spirituality": "Upright — voluntary devotion, the wisdom of sacrifice. Reversed — sacrifice out of habit, refusal to let go.",
        },
    },
    "XIII": {
        "ru": {
            "reversed": "Сопротивление переменам, затяжной кризис, цепляние за отжившее.",
            "love": "Прямо — конец одного этапа и рождение нового в паре. Перевёрнуто — страх расставания, затяжные «похороны» отношений.",
            "career": "Прямо — реорганизация, смена направления, освобождение от лишнего. Перевёрнуто — застой из страха перемен, нежелание закрывать.",
            "health": "Прямо — очищение, необходимый перелом в лечении, обновление. Перевёрнуто — тревога о смерти, хроническое оттягивание проверок.",
            "spirituality": "Прямо — трансформация души, смерть старой личности. Перевёрнуто — духовный застой, страх обновления.",
        },
        "uk": {
            "reversed": "Опір змінам, затяжна криза, чіпляння за віджите.",
            "love": "Прямо — кінець одного етапу й народження нового в парі. Перевернуто — страх розставання, затяжні «похорони» стосунків.",
            "career": "Прямо — реорганізація, зміна напряму, звільнення від зайвого. Перевернуто — застій зі страху змін, небажання закривати.",
            "health": "Прямо — очищення, необхідний перелом у лікуванні, оновлення. Перевернуто — тривога про смерть, хронічне відтягування перевірок.",
            "spirituality": "Прямо — трансформація душі, смерть старої особистості. Перевернуто — духовний застій, страх оновлення.",
        },
        "en": {
            "reversed": "Resisting change, a lingering crisis, clinging to what's outdated.",
            "love": "Upright — the end of one stage and the birth of another in the couple. Reversed — fear of parting, prolonged mourning of a relationship.",
            "career": "Upright — reorganisation, a change of direction, shedding the excess. Reversed — stagnation from fear of change, refusing to close things.",
            "health": "Upright — cleansing, a necessary turning point in treatment, renewal. Reversed — fear of death, chronically putting off check-ups.",
            "spirituality": "Upright — transformation of the soul, death of the old self. Reversed — spiritual stagnation, fear of renewal.",
        },
    },
    "XIV": {
        "ru": {
            "reversed": "Дисбаланс, перегибы, конфликт «разум и сердце».",
            "love": "Прямо — терпение, союз, выздоровление чувств, гармония. Перевёрнуто — нестабильность, перепады настроения, разнобой.",
            "career": "Прямо — умеренность, стратегия, плавное развитие. Перевёрнуто — распыление ресурсов, суета, переработки.",
            "health": "Прямо — выздоровление, сбалансированное питание, режим. Перевёрнуто — срыв диеты, хроническая усталость, крайности.",
            "spirituality": "Прямо — золотая середина, алхимия души, примирение противоположностей. Перевёрнуто — экстремизм, потеря внутреннего компаса.",
        },
        "uk": {
            "reversed": "Дисбаланс, перегини, конфлікт «розум і серце».",
            "love": "Прямо — терпіння, союз, одужання почуттів, гармонія. Перевернуто — нестабільність, перепади настрою, розлад.",
            "career": "Прямо — помірність, стратегія, плавний розвиток. Перевернуто — розпорошення ресурсів, метушня, переробки.",
            "health": "Прямо — одужання, збалансоване харчування, режим. Перевернуто — зрив дієти, хронічна втома, крайнощі.",
            "spirituality": "Прямо — золота середина, алхімія душі, примирення протилежностей. Перевернуто — екстремізм, втрата внутрішнього компаса.",
        },
        "en": {
            "reversed": "Imbalance, overdoing things, a head-vs-heart conflict.",
            "love": "Upright — patience, union, healing of feelings, harmony. Reversed — instability, mood swings, discord.",
            "career": "Upright — moderation, strategy, steady growth. Reversed — scattering resources, fussing, overwork.",
            "health": "Upright — recovery, balanced eating, routine. Reversed — breaking a diet, chronic fatigue, extremes.",
            "spirituality": "Upright — the golden mean, alchemy of the soul, reconciling opposites. Reversed — extremism, losing your inner compass.",
        },
    },
    "XV": {
        "ru": {
            "reversed": "Разрыв цепей, исцеление зависимостей, начало свободы.",
            "love": "Прямо — магнетическая страсть, зависимость, искушение. Перевёрнуто — освобождение от токсичной связи, отрезвление.",
            "career": "Прямо — погоня за властью и деньгами, риск быть «продавшимся». Перевёрнуто — выход из плена корпоративных правил.",
            "health": "Прямо — зависимости (еда, алкоголь, табак), страсти подтачивают. Перевёрнуто — начало выхода из зависимости, работа с тягой.",
            "spirituality": "Прямо — тень, эго, испытание материей. Перевёрнуто — освобождение духа, снятие оков.",
        },
        "uk": {
            "reversed": "Розрив ланцюгів, зцілення залежностей, початок свободи.",
            "love": "Прямо — магнетична пристрасть, залежність, спокуса. Перевернуто — звільнення від токсичного зв’язку, протверезіння.",
            "career": "Прямо — гонитва за владою й грошима, ризик «продатися». Перевернуто — вихід із полону корпоративних правил.",
            "health": "Прямо — залежності (їжа, алкоголь, тютюн), пристрасті підточують. Перевернуто — початок виходу із залежності, робота з потягом.",
            "spirituality": "Прямо — тінь, его, випробування матерією. Перевернуто — звільнення духа, зняття пут.",
        },
        "en": {
            "reversed": "Breaking chains, healing addictions, the start of freedom.",
            "love": "Upright — magnetic passion, attachment, temptation. Reversed — freeing yourself from a toxic bond, sobering up.",
            "career": "Upright — chasing power and money, risking selling out. Reversed — escaping the prison of corporate rules.",
            "health": "Upright — addictions (food, alcohol, tobacco), passions eroding you. Reversed — beginning to leave addiction, working on cravings.",
            "spirituality": "Upright — the shadow, the ego, the test of matter. Reversed — liberation of the spirit, shedding shackles.",
        },
    },
    "XVI": {
        "ru": {
            "reversed": "Страх катастрофы, отсроченное разрушение, урок не усвоен.",
            "love": "Прямо — внезапный крах иллюзий, разрыв, освобождающий обоих. Перевёрнуто — подавленный кризис, «всё висит на волоске».",
            "career": "Прямо — увольнение, крах плана, внезапная реорганизация. Перевёрнуто — затянувшийся кризис, страх новых перемен.",
            "health": "Прямо — резкий сбой, травма, настоятельный сигнал тела. Перевёрнуто — затяжная болезнь, игнор «звоночков».",
            "spirituality": "Прямо — прорыв ложных конструкций, очистительный гром. Перевёрнуто — страх прозрения, удержание руин.",
        },
        "uk": {
            "reversed": "Страх катастрофи, відстрочене руйнування, урок не засвоєно.",
            "love": "Прямо — раптовий крах ілюзій, розрив, що визволяє обох. Перевернуто — пригнічена криза, «все висить на волосині».",
            "career": "Прямо — звільнення, крах плану, раптова реорганізація. Перевернуто — затяжна криза, страх нових змін.",
            "health": "Прямо — різкий збій, травма, наполегливий сигнал тіла. Перевернуто — затяжна хвороба, ігнорування «дзвіночків».",
            "spirituality": "Прямо — прорив хибних конструкцій, очищувальний грім. Перевернуто — страх прозріння, утримання руїн.",
        },
        "en": {
            "reversed": "Fear of catastrophe, delayed destruction, lesson not learned.",
            "love": "Upright — a sudden collapse of illusions, a break that frees both. Reversed — a suppressed crisis, everything hanging by a thread.",
            "career": "Upright — layoff, a plan collapsing, sudden reorganisation. Reversed — a lingering crisis, fear of further change.",
            "health": "Upright — a sharp breakdown, injury, a insistent signal from the body. Reversed — a prolonged illness, ignoring warning signs.",
            "spirituality": "Upright — bursting false structures, a cleansing thunderclap. Reversed — fear of insight, clinging to ruins.",
        },
    },
    "XVII": {
        "ru": {
            "reversed": "Разочарование, утрата веры, отложенные надежды.",
            "love": "Прямо — надежда, исцеление после разлуки, свет в конце туннеля. Перевёрнуто — неверие в любовь, затянувшееся разочарование.",
            "career": "Прямо — вдохновение, признание, выход из тени. Перевёрнуто — творческий кризис, нереалистичные планы.",
            "health": "Прямо — восстановление, надежда как лекарство, ресурс. Перевёрнуто — апатия, потеря веры в выздоровление.",
            "spirituality": "Прямо — надежда, вера, путеводная звезда души. Перевёрнуто — потерянность, отказ видеть свет.",
        },
        "uk": {
            "reversed": "Розчарування, втрата віри, відкладені надії.",
            "love": "Прямо — надія, зцілення після розлуки, світло в кінці тунелю. Перевернуто — невіра в любов, затяжне розчарування.",
            "career": "Прямо — натхнення, визнання, вихід із тіні. Перевернуто — творча криза, нереалістичні плани.",
            "health": "Прямо — відновлення, надія як ліки, ресурс. Перевернуто — апатія, втрата віри в одужання.",
            "spirituality": "Прямо — надія, віра, путеводна зірка душі. Перевернуто — розгубленість, відмова бачити світло.",
        },
        "en": {
            "reversed": "Disappointment, loss of faith, deferred hopes.",
            "love": "Upright — hope, healing after a parting, light at the end of the tunnel. Reversed — disbelief in love, lingering disappointment.",
            "career": "Upright — inspiration, recognition, stepping out of the shadows. Reversed — a creative crisis, unrealistic plans.",
            "health": "Upright — recovery, hope as medicine, resources. Reversed — apathy, losing faith in recovery.",
            "spirituality": "Upright — hope, faith, the soul's guiding star. Reversed — feeling lost, refusing to see the light.",
        },
    },
    "XVIII": {
        "ru": {
            "reversed": "Тревоги расходуются, туман рассеивается, страх уходит.",
            "love": "Прямо — романтика-мираж, недоговорённость, обаяние тайны. Перевёрнуто — выход из иллюзий, прояснение чувств.",
            "career": "Прямо — неясность, скрытые обстоятельства, опора на интуицию. Перевёрнуто — прояснение ситуации, снятие наваждения.",
            "health": "Прямо — тревожность, бессонница, пси-фактор симптомов. Перевёрнуто — стабилизация нервов, выход из тревожного цикла.",
            "spirituality": "Прямо — интуиция, сны, встреча с тенью, глубины. Перевёрнуто — уход страхов, интеграция тени.",
        },
        "uk": {
            "reversed": "Тривоги вичерпуються, туман розсіюється, страх минає.",
            "love": "Прямо — романтика-міраж, недомовленість, чарівність таємниці. Перевернуто — вихід з ілюзій, прояснення почуттів.",
            "career": "Прямо — неясність, приховані обставини, опора на інтуїцію. Перевернуто — прояснення ситуації, зняття навіювання.",
            "health": "Прямо — тривожність, безсоння, пси-фактор симптомів. Перевернуто — стабілізація нервів, вихід із тривожного циклу.",
            "spirituality": "Прямо — інтуїція, сни, зустріч із тінню, глибини. Перевернуто — відхід страхів, інтеграція тіні.",
        },
        "en": {
            "reversed": "Anxieties fading, the fog clearing, fear receding.",
            "love": "Upright — mirage-like romance, unspoken things, the charm of mystery. Reversed — leaving illusions, feelings becoming clear.",
            "career": "Upright — obscurity, hidden circumstances, trusting intuition. Reversed — the picture clearing, the spell lifting.",
            "health": "Upright — anxiety, insomnia, psychosomatic symptoms. Reversed — nerves steadying, leaving an anxious loop.",
            "spirituality": "Upright — intuition, dreams, meeting the shadow, the depths. Reversed — fears receding, integrating the shadow.",
        },
    },
    "XIX": {
        "ru": {
            "reversed": "Струшенный успех, забота о внутреннем свете, временные облака.",
            "love": "Прямо — ясность чувств, радость, тёплый союз. Перевёрнуто — эгоизм, охлаждение, «солнце за облаками».",
            "career": "Прямо — успех, признание, расцвет, блестящий результат. Перевёрнуто — временный спад, мелочь в тени триумфа.",
            "health": "Прямо — vitalitas, энергия, бодрость, хороший сезон. Перевёрнуто — лёгкий упадок сил, «зима» здоровья.",
            "spirituality": "Прямо — просветление, детская радость, свет души. Перевёрнуто — временное затмение внутреннего света.",
        },
        "uk": {
            "reversed": "Дещо притьмарений успіх, турбота про внутрішнє світло, тимчасові хмари.",
            "love": "Прямо — ясність почуттів, радість, теплий союз. Перевернуто — егоїзм, охолодження, «сонце за хмарами».",
            "career": "Прямо — успіх, визнання, розквіт, блискучий результат. Перевернуто — тимчасовий спад, дрібниця в тіні тріумфу.",
            "health": "Прямо — vitalitas, енергія, бадьорість, добрий сезон. Перевернуто — легкий занепад сил, «зима» здоров’я.",
            "spirituality": "Прямо — просвітлення, дитяча радість, світло душі. Перевернуто — тимчасове затемнення внутрішнього світла.",
        },
        "en": {
            "reversed": "Slightly dimmed success, caring for inner light, passing clouds.",
            "love": "Upright — clarity of feeling, joy, a warm union. Reversed — selfishness, cooling off, sun behind clouds.",
            "career": "Upright — success, recognition, flourishing, a brilliant result. Reversed — a temporary dip, a spoiler in the triumph's shadow.",
            "health": "Upright — vitality, energy, cheerfulness, a good season. Reversed — a mild dip in energy, a health winter.",
            "spirituality": "Upright — illumination, childish joy, the soul's light. Reversed — a temporary eclipse of inner light.",
        },
    },
    "XX": {
        "ru": {
            "reversed": "Отказ от зова, самокритика, откладывание воскресения.",
            "love": "Прямо — возрождение чувств, примирение, большая любовь. Перевёрнуто — страх новых отношений, затянутое переживание.",
            "career": "Прямо — призвание, новый виток, признание и оценка. Перевёрнуто — сомнения в своём пути, упущенные возможности.",
            "health": "Прямо — выздоровление, второе дыхание, выход из кризиса. Перевёрнуто — затяжной восстановительный этап, самобичевание.",
            "spirituality": "Прямо — пробуждение души, зов, воскресение духа. Перевёрнуто — глухота к призванию, страх перемен.",
        },
        "uk": {
            "reversed": "Відмова від поклику, самокритика, відкладання воскресіння.",
            "love": "Прямо — відродження почуттів, примирення, велике кохання. Перевернуто — страх нових стосунків, затягнуте переживання.",
            "career": "Прямо — покликання, новий виток, визнання й оцінка. Перевернуто — сумніви у своєму шляху, втрачені можливості.",
            "health": "Прямо — одужання, друге дихання, вихід із кризи. Перевернуто — затяжний відновлювальний етап, самобичування.",
            "spirituality": "Прямо — пробудження душі, поклик, воскресіння духа. Перевернуто — глухота до покликання, страх змін.",
        },
        "en": {
            "reversed": "Refusing the call, self-criticism, postponing resurrection.",
            "love": "Upright — rebirth of feelings, reconciliation, great love. Reversed — fear of new relationships, prolonged grieving.",
            "career": "Upright — calling, a new cycle, recognition and reckoning. Reversed — doubt in your path, missed opportunities.",
            "health": "Upright — recovery, second wind, leaving a crisis. Reversed — a slow healing stage, self-flagellation.",
            "spirituality": "Upright — awakening of the soul, the call, resurrection of the spirit. Reversed — deafness to the calling, fear of change.",
        },
    },
    "XXI": {
        "ru": {
            "reversed": "Незавершённость, сопротивление целостности, «почти готово».",
            "love": "Прямо — союз, полнота, гармония, свадьба. Перевёрнуто — чувство, что чего-то не хватает, незакрытый вопрос.",
            "career": "Прямо — вершина, завершение большого цикла, интеграция. Перевёрнуто — незакрытый проект, недосказанность.",
            "health": "Прямо — полное восстановление, целостность, равновесие. Перевёрнуто — «почти здоров», остаточные хвосты.",
            "spirituality": "Прямо — просветление, единство, космическая гармония. Перевёрнуто — ощущение разорванности, незавершённый поиск.",
        },
        "uk": {
            "reversed": "Незавершеність, опір цілісності, «майже готово».",
            "love": "Прямо — союз, повнота, гармонія, весілля. Перевернуто — відчуття, що чогось бракує, незакрите питання.",
            "career": "Прямо — вершина, завершення великого циклу, інтеграція. Перевернуто — незакритий проєкт, недомовленість.",
            "health": "Прямо — повне відновлення, цілісність, рівновага. Перевернуто — «майже здоровий», залишкові хвости.",
            "spirituality": "Прямо — просвітлення, єдність, космічна гармонія. Перевернуто — відчуття розірваності, незавершений пошук.",
        },
        "en": {
            "reversed": "Incompleteness, resisting wholeness, almost there.",
            "love": "Upright — union, fullness, harmony, marriage. Reversed — a sense that something is missing, an unresolved question.",
            "career": "Upright — the summit, closing a big cycle, integration. Reversed — an unclosed project, things left unsaid.",
            "health": "Upright — full recovery, wholeness, balance. Reversed — almost healthy, lingering ends.",
            "spirituality": "Upright — enlightenment, oneness, cosmic harmony. Reversed — a feeling of fragmentation, an unfinished search.",
        },
    },
}