# -*- coding: utf-8 -*-
"""Значения младших арканов Пентаклей (Pentacles, стихия Земли)."""
PENTACLES = {
    "Pentacles-01": {
        "ru": {
            "reversed": "Упущенная возможность, финансовая невнимательность, страх изобилия.",
            "love": "Прямо — надёжное, материально устойчивое чувство. Перевёрнуто — чувства через деньги, страх вложений в любовь.",
            "career": "Прямо — новая возможность, работа, зарождение дела. Перевёрнуто — упущенный шанс, неверное вложение.",
            "health": "Прямо — крепкое здоровье, фундамент, ресурс. Перевёрнуто — игнор базы, «зарастание» забот.",
            "spirituality": "Прямо — благословение материи, воплощение духа. Перевёрнуто — привязанность к деньгам, потеря корня.",
        },
        "uk": {
            "reversed": "Втрачена можливість, фінансова неуважність, страх достатку.",
            "love": "Прямо — надійне, матеріально стійке почуття. Перевернуто — почуття через гроші, страх вкладень у любов.",
            "career": "Прямо — нова можливість, робота, зародження справи. Перевернуто — втрачений шанс, невірне вкладення.",
            "health": "Прямо — міцне здоров'я, фундамент, ресурс. Перевернуто — ігнорування бази, «заростання» турбот.",
            "spirituality": "Прямо — благословення матерії, втілення духу. Перевернуто — прив'язаність до грошей, втрата кореня.",
        },
        "en": {
            "reversed": "A missed opportunity, financial carelessness, fear of abundance.",
            "love": "Upright — a reliable, financially stable feeling. Reversed — feelings through money, fear of investing in love.",
            "career": "Upright — a new opportunity, work, the seed of an enterprise. Reversed — a missed chance, wrong investment.",
            "health": "Upright — strong health, a foundation, resources. Reversed — ignoring the basics, letting cares overgrow.",
            "spirituality": "Upright — blessing of matter, spirit made manifest. Reversed — attachment to money, losing your root.",
        },
    },
    "Pentacles-02": {
        "ru": {
            "reversed": "Потеря равновесия, задолженности, растрата на ветер.",
            "love": "Прямо — лавирование между семьёй и работой, гибкость. Перевёрнуто — разбалансировка, нехватка времени друг на друга.",
            "career": "Прямо — мультизадачность, гибкие схемы, juggling у проектов. Перевёрнуто — перегруз, финансовые качели.",
            "health": "Прямо — поддержание формы в меняющемся ритме. Перевёрнуто — сбитый ритм, хаос питания-сна.",
            "spirituality": "Прямо — ловкость духа, игра с балансом. Перевёрнуто — рассеянность, двойственность.",
        },
        "uk": {
            "reversed": "Втрата рівноваги, заборгованості, розтрата на вітер.",
            "love": "Прямо — лавіювання між сім'єю й роботою, гнучкість. Перевернуто — розбалансування, брак часу одне на одного.",
            "career": "Прямо — мультизадачність, гнучкі схеми, жонглювання проєктами. Перевернуто — перевантаження, фінансові гойдалки.",
            "health": "Прямо — підтримання форми в мінливому ритмі. Перевернуто — збитий ритм, хаос харчування-сну.",
            "spirituality": "Прямо — спритність духу, гра з балансом. Перевернуто — розсіяність, двоїстість.",
        },
        "en": {
            "reversed": "Loss of balance, debts, money thrown to the wind.",
            "love": "Upright — juggling family and work, flexibility. Reversed — imbalance, no time for each other.",
            "career": "Upright — multitasking, flexible schemes, juggling projects. Reversed — overload, financial swings.",
            "health": "Upright — staying in shape amid a changing rhythm. Reversed — broken rhythm, chaos of food and sleep.",
            "spirituality": "Upright — agility of spirit, playing with balance. Reversed — distractibility, duality.",
        },
    },
    "Pentacles-03": {
        "ru": {
            "reversed": "Недооценка труда, разлад в команде, «лепка наспех».",
            "love": "Прямо — строительство общего дома, труд о любовь. Перевёрнуто — кто-то тянет, кто-то наблюдает.",
            "career": "Прямо — мастерство, признание, командная работа. Перевёрнуто — некачественный результат, разногласия.",
            "health": "Прямо — планомерное восстановление, ремесло заботы. Перевёрнуто — прерывистая терапия, «эскиз» лечения.",
            "spirituality": "Прямо — труд духа, терпеливое строительство себя. Перевёрнуто — черновик пути, поспешные практики.",
        },
        "uk": {
            "reversed": "Недооцінка праці, розлад у команді, «ліплення наспіх».",
            "love": "Прямо — будівництво спільного дому, праця заради любові. Перевернуто — хтось тягне, хтось спостерігає.",
            "career": "Прямо — майстерність, визнання, командна робота. Перевернуто — неякісний результат, розбіжності.",
            "health": "Прямо — планомірне відновлення, ремесло турботи. Перевернуто — переривчаста терапія, «ескіз» лікування.",
            "spirituality": "Прямо — праця духу, терпляче будування себе. Перевернуто — чернетка шляху, поспішні практики.",
        },
        "en": {
            "reversed": "Underappreciated work, discord in the team, slapdash building.",
            "love": "Upright — building a shared home, working for love. Reversed — one pulls, the other watches.",
            "career": "Upright — craftsmanship, recognition, teamwork. Reversed — poor results, disagreements.",
            "health": "Upright — systematic recovery, the craft of care. Reversed — intermittent therapy, a sketch of treatment.",
            "spirituality": "Upright — labour of the spirit, patiently building yourself. Reversed — a rough draft of the path, hasty practice.",
        },
    },
    "Pentacles-04": {
        "ru": {
            "reversed": "Щедрость после удержания, разжатые кулаки, трата на себя.",
            "love": "Прямо — стабильность чувств, контроль ресурсов. Перевёрнуто — скряга чувств, страх «отдать» любовь.",
            "career": "Прямо — безопасность, накопление, контроль. Перевёрнуто — жадность до позиции, синдром «только моё».",
            "health": "Прямо — экономия сил, устойчивая форма. Перевёрнуто — зажатость, скованность, «замороженная» энергия.",
            "spirituality": "Прямо — твёрдость духа, охрана границ. Перевёрнуто — цепляние за вещи, идол стабильности.",
        },
        "uk": {
            "reversed": "Щедрість після утримання, розтиснуті кулаки, витрата на себе.",
            "love": "Прямо — стабільність почуттів, контроль ресурсів. Перевернуто — скнара почуттів, страх «віддати» любов.",
            "career": "Прямо — безпека, накопичення, контроль. Перевернуто — жадібність до позиції, синдром «тільки моє».",
            "health": "Прямо — економія сил, стійка форма. Перевернуто — затисненість, скутість, «заморожена» енергія.",
            "spirituality": "Прямо — твердість духу, охорона меж. Перевернуто — чіпляння за речі, ідол стабільності.",
        },
        "en": {
            "reversed": "Generosity after holding back, unclenched fists, spending on yourself.",
            "love": "Upright — stability of feeling, control of resources. Reversed — miserly with feelings, afraid to give love.",
            "career": "Upright — security, saving, control. Reversed — greedy for position, the 'only mine' syndrome.",
            "health": "Upright — conserving strength, a steady form. Reversed — holding tight, stiffness, frozen energy.",
            "spirituality": "Upright — firmness of spirit, guarding boundaries. Reversed — clinging to things, an idol of stability.",
        },
    },
    "Pentacles-05": {
        "ru": {
            "reversed": "Помощь приходит, первые лучи, выход из нищеты.",
            "love": "Прямо — чувство «на холоде», нужда в поддержке. Перевёрнуто — принятие помощи, восстановление тепла.",
            "career": "Прямо — дефицит ресурсов, трудные времена. Перевёрнуто — поиск поддержки, выход из дефицита.",
            "health": "Прямо — истощение, простудный сезон, нехватка ухода. Перевёрнуто — забота о себе, начало восстановления.",
            "spirituality": "Прямо — духовная зима, испытание веры. Перевернуто — обретение опоры, свет среди снегов.",
        },
        "uk": {
            "reversed": "Допомога приходить, перші промені, вихід із злиднів.",
            "love": "Прямо — відчуття «на холоді», потреба в підтримці. Перевернуто — прийняття допомоги, відновлення тепла.",
            "career": "Прямо — дефіцит ресурсів, скрутні часи. Перевернуто — пошук підтримки, вихід із дефіциту.",
            "health": "Прямо — виснаження, застудний сезон, брак турботи. Перевернуто — турбота про себе, початок відновлення.",
            "spirituality": "Прямо — духовна зима, випробування віри. Перевернуто — здобуття опори, світло серед снігів.",
        },
        "en": {
            "reversed": "Help arriving, first rays, leaving poverty behind.",
            "love": "Upright — feeling left out in the cold, needing support. Reversed — accepting help, warmth returning.",
            "career": "Upright — scarce resources, hard times. Reversed — seeking support, leaving the deficit.",
            "health": "Upright — exhaustion, cold season, lack of care. Reversed — caring for yourself, recovery beginning.",
            "spirituality": "Upright — spiritual winter, the test of faith. Reversed — finding support, light amid the snow.",
        },
    },
    "Pentacles-06": {
        "ru": {
            "reversed": "Несправедливость в обмене, цепи долга, скрытая жадность.",
            "love": "Прямо — щедрая забота, взаимный дар в отношениях. Перевёрнуто — обмен с условиями, «ты мне, я тебе».",
            "career": "Прямо — справедливая оплата, наставничество, помощь. Перевёрнуто — скрёж на оплате, помощь с процентом.",
            "health": "Прямо — баланс заботы, хорошая опека. Перевёрнуто — здоровье «в долг», пренебрежение к себе.",
            "spirituality": "Прямо — щедрость духа, дар без жадности. Перевёрнуто — духовная услуга за плату, милостыня с гордостью.",
        },
        "uk": {
            "reversed": "Несправедливість в обміні, ланцюги боргу, прихована жадібність.",
            "love": "Прямо — щедра турбота, взаємний дар у стосунках. Перевернуто — обмін із умовами, «ти мені, я тобі».",
            "career": "Прямо — справедлива оплата, наставництво, допомога. Перевернуто — скнарість на оплаті, допомога з відсотком.",
            "health": "Прямо — баланс турботи, добра опіка. Перевернуто — здоров'я «в борг», нехтування собою.",
            "spirituality": "Прямо — щедрість духу, дар без жадібності. Перевернуто — духовна послуга за плату, милостиня з гордістю.",
        },
        "en": {
            "reversed": "Unfair exchange, chains of debt, hidden greed.",
            "love": "Upright — generous care, mutual giving in the relationship. Reversed — conditional exchange, tit for tat.",
            "career": "Upright — fair pay, mentoring, help. Reversed — stingy pay, help with an interest charge.",
            "health": "Upright — balanced care, good support. Reversed — health on credit, neglecting yourself.",
            "spirituality": "Upright — generosity of spirit, giving without greed. Reversed — spiritual service for a fee, alms with pride.",
        },
    },
    "Pentacles-07": {
        "ru": {
            "reversed": "Перфекционизм-недоверие, нетерпение плодов, постоянная проверка.",
            "love": "Прямо — терпение в выращивании чувств, ожидание урожая. Перевёрнуто — тревога, что «не вырастет», проверки.",
            "career": "Прямо — вложения ждут созревания, оценка результатов. Перевёрнуто — малопродуктивное выжидание, мелочный контроль.",
            "health": "Прямо — режим, вложения в здоровье дают плоды. Перевёрнуто — нетерпеливость в лечении, «почему ещё не видно».",
            "spirituality": "Прямо — терпение духа, время созревания. Перевёрнуто — сомнение в своих духовных всходах.",
        },
        "uk": {
            "reversed": "Перфекціонізм-недовіра, нетерпіння плодів, постійна перевірка.",
            "love": "Прямо — терпіння у вирощуванні почуттів, очікування врожаю. Перевернуто — тривога, що «не виросте», перевірки.",
            "career": "Прямо — вкладення чекають дозрівання, оцінка результатів. Перевернуто — малопродуктивне вичікування, дріб'язковий контроль.",
            "health": "Прямо — режим, вкладення в здоров'я дають плоди. Перевернуто — нетерплячість у лікуванні, «чому ще не видно».",
            "spirituality": "Прямо — терпіння духу, час дозрівання. Перевернуто — сумнів у власних духовних сходах.",
        },
        "en": {
            "reversed": "Perfectionist distrust, impatience for fruit, constant checking.",
            "love": "Upright — patience in growing feelings, awaiting the harvest. Reversed — anxiety it won't grow, checking up.",
            "career": "Upright — investments maturing, evaluating results. Reversed — unproductive waiting, petty control.",
            "health": "Upright — routine, investments in health bearing fruit. Reversed — impatience in treatment, why can't I see it yet.",
            "spirituality": "Upright — patience of the spirit, time to ripen. Reversed — doubting your own spiritual shoots.",
        },
    },
    "Pentacles-08": {
        "ru": {
            "reversed": "Однообразие-в-чрезмерности, потеря интереса к ремеслу, недоработка.",
            "love": "Прямо — построение отношений постепенно, кропотливая забота. Перевёрнуто — рутина вместо чувств, «мастер без вдохновения».",
            "career": "Прямо — усердие, мастерство, обучение ремеслу. Перевёрнуто — монотонность, выгорание от задач.",
            "health": "Прямо — упражнения, дисциплина, мелкая кропотливая забота. Перевёрнуто — автоматические привычки без осознания.",
            "spirituality": "Прямо — труд как молитва, путь мастера. Перевёрнуто — механическая практика, потеря света ремесла.",
        },
        "uk": {
            "reversed": "Одноманітність-у-надмірності, втрата інтересу до ремесла, недоробка.",
            "love": "Прямо — побудова стосунків поступово, кропітка турбота. Перевернуто — рутина замість почуттів, «майстер без натхнення».",
            "career": "Прямо — старанність, майстерність, навчання ремеслу. Перевернуто — монотонність, вигорання від завдань.",
            "health": "Прямо — вправи, дисципліна, дрібна копітка турбота. Перевернуто — автоматичні звички без усвідомлення.",
            "spirituality": "Прямо — праця як молитва, шлях майстра. Перевернуто — механічна практика, втрата світла ремесла.",
        },
        "en": {
            "reversed": "Monotony carried to excess, losing interest in the craft, shoddy work.",
            "love": "Upright — building the relationship step by step, painstaking care. Reversed — routine instead of feeling, a craftsman without inspiration.",
            "career": "Upright — diligence, craftsmanship, learning the trade. Reversed — monotony, task burnout.",
            "health": "Upright — exercise, discipline, small steady care. Reversed — automatic habits without awareness.",
            "spirituality": "Upright — work as prayer, the master's path. Reversed — mechanical practice, the craft's light lost.",
        },
    },
    "Pentacles-09": {
        "ru": {
            "reversed": "Одиночество достатка, материалы без радости, охрана от щедрости.",
            "love": "Прямо — достаток и спокойствие в чувствах. Перевёрнуто — богатство без тепла, статус вместо любви.",
            "career": "Прямо — самореализация, собственный сад, независимость. Перевёрнуто — «золотая клетка», избыток без смысла.",
            "health": "Прямо — отличная форма, цветущее благополучие. Перевёрнуто — самодостаточность в изоляции, пренебрежение связями.",
            "spirituality": "Прямо — самодостаточность духа, внутренний сад. Перевернуто — гордость достатком, духовное одиночество.",
        },
        "uk": {
            "reversed": "Самотність достатку, матеріали без радості, охорона від щедрості.",
            "love": "Прямо — достаток і спокій у почуттях. Перевернуто — багатство без тепла, статус замість любові.",
            "career": "Прямо — самореалізація, власний сад, незалежність. Перевернуто — «золота клітка», надмір без сенсу.",
            "health": "Прямо — чудова форма, квітуче благополуччя. Перевернуто — самодостатність в ізоляції, нехтування зв'язками.",
            "spirituality": "Прямо — самодостатність духу, внутрішній сад. Перевернуто — гордість достатком, духовна самотність.",
        },
        "en": {
            "reversed": "Loneliness of wealth, goods without joy, guarding against generosity.",
            "love": "Upright — ease and calm in feeling. Reversed — riches without warmth, status instead of love.",
            "career": "Upright — self-realisation, your own garden, independence. Reversed — a gilded cage, excess without meaning.",
            "health": "Upright — excellent form, flourishing wellbeing. Reversed — self-sufficiency in isolation, neglecting connections.",
            "spirituality": "Upright — self-sufficiency of spirit, the inner garden. Reversed — pride in wealth, spiritual loneliness.",
        },
    },
    "Pentacles-10": {
        "ru": {
            "reversed": "Наследственная ловушка, семья на грани, дела против чувств.",
            "love": "Прямо — семейное счастье, дом наполнен любовью. Перевёрнуто — традиции давят, приличия вместо радости.",
            "career": "Прямо — семейный бизнес, наследие, капитализация. Перевернуто — дележ наследства, неверная опора.",
            "health": "Прямо — наследственная крепость, хорошие гены. Перевёрнуто — наследственные болячки, перегруз обязанностей.",
            "spirituality": "Прямо — корни, род, преемственная мудрость. Перевёрнуто — груз рода, духовная наследственность в долг.",
        },
        "uk": {
            "reversed": "Спадкова пастка, родина на межі, справи проти почуттів.",
            "love": "Прямо — сімейне щастя, дім, наповнений любов'ю. Перевернуто — традиції тиснуть, пристойність замість радості.",
            "career": "Прямо — сімейний бізнес, спадщина, капіталізація. Перевернуто — поділ спадщини, невірна опора.",
            "health": "Прямо — спадкова міцність, добрі гени. Перевернуто — спадкові болячки, перевантаження обов'язками.",
            "spirituality": "Прямо — коріння, рід, успадкована мудрість. Перевернуто — тягар роду, духовна спадковість у борг.",
        },
        "en": {
            "reversed": "A hereditary trap, family on edge, business against feelings.",
            "love": "Upright — family happiness, a home full of love. Reversed — traditions pressing down, propriety instead of joy.",
            "career": "Upright — family business, legacy, capitalisation. Reversed — inheritance disputes, wrong support.",
            "health": "Upright — hereditary strength, good genes. Reversed — hereditary ailments, the burden of duty.",
            "spirituality": "Upright — roots, kin, inherited wisdom. Reversed — the weight of the lineage, borrowed spirituality.",
        },
    },
    "Pentacles-11": {
        "ru": {
            "reversed": "Рассеянный ученик, медленное усвоение, поверхностная учёба.",
            "love": "Прямо — серьёзная юная привязанность, любовь-обучение. Перевёрнуто — незрелость, «студент» чувств без усидчивости.",
            "career": "Прямо — усердный ученик, стажировка, начало карьеры. Перевернуто — прогулы, недоученное ремесло.",
            "health": "Прямо — прилежное освоение заботы о себе. Перевёрнуто — забывчивость в режиме, халатность новичка.",
            "spirituality": "Прямо — начинающий на пути, практика усердия. Перевёрнуто — поверхностность, интерес без погружения.",
        },
        "uk": {
            "reversed": "Розсіяний учень, повільне засвоєння, поверхневе навчання.",
            "love": "Прямо — серйозна юна прив'язаність, любов-навчання. Перевернуто — незрілість, «студент» почуттів без старанності.",
            "career": "Прямо — старанний учень, стажування, початок кар'єри. Перевернуто — прогули, недовчене ремесло.",
            "health": "Прямо — старанне освоєння турботи про себе. Перевернуто — забудькуватість у режимі, недбалість новачка.",
            "spirituality": "Прямо — новачок на шляху, практика старанності. Перевернуто — поверховість, інтерес без занурення.",
        },
        "en": {
            "reversed": "A distracted student, slow learning, shallow study.",
            "love": "Upright — a serious young attachment, love as learning. Reversed — immaturity, a student of feeling without diligence.",
            "career": "Upright — a diligent apprentice, internship, the start of a career. Reversed — skipping classes, an incompletely learned craft.",
            "health": "Upright — diligently learning self-care. Reversed — forgetful routine, beginner's negligence.",
            "spirituality": "Upright — a beginner on the path, practising diligence. Reversed — shallowness, interest without immersion.",
        },
    },
    "Pentacles-12": {
        "ru": {
            "reversed": "Стагнация упрямца, медлительность регресса, неповоротcкий настаивание.",
            "love": "Прямо — надёжный, терпеливый, верный партнёр. Перевёрнуто — упрямство, боязнь проявлять чувства, рутина.",
            "career": "Прямо — неспешный надёжный прогресс, стабильный исполнитель. Перевёрнуто — пробуксовка, «стойла», нежелание менять подход.",
            "health": "Прямо — постепенное прочное укрепление. Перевёрнуто — косность, медицина «по старинке» без прогресса.",
            "spirituality": "Прямо — степенный путь, верность практике. Перевёрнуто — духовная закостенелость, отвержение нового.",
        },
        "uk": {
            "reversed": "Стагнація впертюха, повільність регресу, незграбне наполягання.",
            "love": "Прямо — надійний, терплячий, вірний партнер. Перевернуто — впертість, страх проявляти почуття, рутина.",
            "career": "Прямо — неквапливий надійний прогрес, стабільний виконавець. Перевернуто — пробуксовка, «стійло», небажання змінювати підхід.",
            "health": "Прямо — поступове міцне зміцнення. Перевернуто — косність, медицина «по-старому» без прогресу.",
            "spirituality": "Прямо — розважливий шлях, вірність практиці. Перевернуто — духовна закостенілість, відкидання нового.",
        },
        "en": {
            "reversed": "A stubborn stall, slow regression, clumsy insistence.",
            "love": "Upright — a reliable, patient, faithful partner. Reversed — stubbornness, fear of showing feeling, routine.",
            "career": "Upright — steady reliable progress, a stable executor. Reversed — spinning wheels, a stall, refusing to change approach.",
            "health": "Upright — gradual solid strengthening. Reversed — inertia, old-school medicine with no progress.",
            "spirituality": "Upright — a steady path, faithfulness to practice. Reversed — spiritual rigidity, rejecting the new.",
        },
    },
    "Pentacles-13": {
        "ru": {
            "reversed": "Суета домашних дел, пренебрежение собой, забота в ущерб.",
            "love": "Прямо — дом, тепло, хлебосольная любовь. Перевёрнуто — быт пожирает чувства, «кухня вместо разговора».",
            "career": "Прямо — практичная зрелость, финансовая грамотность, управление. Перевернуто — микроменеджмент, заземление в мелочах.",
            "health": "Прямо — крепкая практичная форма, питание и земля. Перевёрнуто — переедание заботой, игнор себя ради других.",
            "spirituality": "Прямо — мудрость земли, щедрое гостеприимство духа. Перевёрнуто — дух в тени хозяйства, суета.",
        },
        "uk": {
            "reversed": "Метушня домашніх справ, нехтування собою, турбота на шкоду.",
            "love": "Прямо — дім, тепло, хлібосольна любов. Перевернуто — побут пожирає почуття, «кухня замість розмови».",
            "career": "Прямо — практична зрілість, фінансова грамотність, управління. Перевернуто — мікроменеджмент, заземлення в дрібницях.",
            "health": "Прямо — міцна практична форма, харчування й земля. Перевернуто — переїдання турботою, ігнорування себе заради інших.",
            "spirituality": "Прямо — мудрість землі, щедра гостинність духу. Перевернуто — дух у тіні господарства, метушня.",
        },
        "en": {
            "reversed": "A flurry of household chores, neglecting yourself, caring to a fault.",
            "love": "Upright — home, warmth, hospitable love. Reversed — chores devouring feelings, the kitchen replacing the talk.",
            "career": "Upright — practical maturity, financial literacy, stewardship. Reversed — micromanagement, getting stuck in details.",
            "health": "Upright — strong practical form, nourishment and earth. Reversed — overfed with care, ignoring yourself for others.",
            "spirituality": "Upright — wisdom of the earth, generous hospitality of spirit. Reversed — spirit in the shadow of housekeeping, bustle.",
        },
    },
    "Pentacles-14": {
        "ru": {
            "reversed": "Жадность материалиста, риски статуса, деньги как бог.",
            "love": "Прямо — надёжный, умелый, состоявшийся партнёр. Перевёрнуто — любовь через статус, холодный расчёт.",
            "career": "Прямо — король дела, финансовая вершина, управление богатством. Перевёрнуто — коррупция, тирания богатства, «одобрямс» деньгам.",
            "health": "Прямо — устойчивое здоровье, уверенная энергия. Перевёрнуто — «сидячий» образ жизни, излишества достатка.",
            "spirituality": "Прямо — мудрое владение материей, щедрый дух. Перевёрнуто — кумир маммоны, дух за деньги.",
        },
        "uk": {
            "reversed": "Жадібність матеріаліста, ризики статусу, гроші як бог.",
            "love": "Прямо — надійний, вмілий, успішний партнер. Перевернуто — любов через статус, холодний розрахунок.",
            "career": "Прямо — король справи, фінансова вершина, управління багатством. Перевернуто — корупція, тиранія багатства, «схвалення» грошей.",
            "health": "Прямо — стійке здоров'я, впевнена енергія. Перевернуто — «сидячий» спосіб життя, надмірність достатку.",
            "spirituality": "Прямо — мудре володіння матерією, щедрий дух. Перевернуто — кумир мамони, дух за гроші.",
        },
        "en": {
            "reversed": "Greed of the materialist, status risks, money as god.",
            "love": "Upright — a reliable, capable, accomplished partner. Reversed — love through status, cold calculation.",
            "career": "Upright — a master of the craft, financial summit, stewardship of wealth. Reversed — corruption, tyranny of wealth, money calling the shots.",
            "health": "Upright — robust health, confident energy. Reversed — a sedentary life, the excesses of plenty.",
            "spirituality": "Upright — wise command of matter, a generous spirit. Reversed — an idol of mammon, spirit for sale.",
        },
    },
}