# -*- coding: utf-8 -*-
"""Значения младших арканов Мечей (Swords, стихия Воздуха)."""
SWORDS = {
    "Swords-01": {
        "ru": {
            "reversed": "Запутанный ум, ложная ясность, отложенное решение.",
            "love": "Прямо — честность, прорыв к правде в отношениях. Перевёрнуто — резкость правды, словесные раны.",
            "career": "Прямо — ясность идеи, решительный старт, ментальный прорыв. Перевёрнуто — неверные выводы, поспешные планы.",
            "health": "Прямо — ясность диагноза, решимость лечиться. Перевёрнуто — запутанные симптомы, игнор правды о здоровье.",
            "spirituality": "Прямо — меч истины, прозрение, сила слова. Перевёрнуто — ум как шпага против себя, жестокость к себе.",
        },
        "uk": {
            "reversed": "Заплутаний розум, хибна ясність, відкладене рішення.",
            "love": "Прямо — чесність, прорив до правди у стосунках. Перевернуто — різкість правди, словесні рани.",
            "career": "Прямо — ясність ідеї, рішучий старт, ментальний прорив. Перевернуто — невірні висновки, поспішні плани.",
            "health": "Прямо — ясність діагнозу, рішучість лікуватися. Перевернуто — заплутані симптоми, ігнорування правди про здоров'я.",
            "spirituality": "Прямо — меч істини, прозріння, сила слова. Перевернуто — розум як шпага проти себе, жорстокість до себе.",
        },
        "en": {
            "reversed": "A tangled mind, false clarity, deferred decision.",
            "love": "Upright — honesty, a breakthrough to truth in the relationship. Reversed — the sharpness of truth, verbal wounds.",
            "career": "Upright — clarity of an idea, a decisive start, mental breakthrough. Reversed — wrong conclusions, hasty plans.",
            "health": "Upright — a clear diagnosis, resolve to treat it. Reversed — tangled symptoms, ignoring the truth about your health.",
            "spirituality": "Upright — the sword of truth, insight, the power of the word. Reversed — the mind as a rapier turned on yourself, self-harshness.",
        },
    },
    "Swords-02": {
        "ru": {
            "reversed": "Тупиковое молчание, затянутое решение, внутренний шум.",
            "love": "Прямо — пауза, взвешенность, нежелание выбирать. Перевёрнуто — замороженный конфликт, страх открыться.",
            "career": "Прямо — тщательное решение «или-или», анализ. Перевёрнуто — тупик выбора, паралич от «а если».",
            "health": "Прямо — осознанная пауза, баланс, невмешательство. Перевёрнуто — отказ замечать симптомы, голова в песке.",
            "spirituality": "Прямо — созерцание, внутренняя тишина при внешнем шуме. Перевёрнуто — внутренний раскол, «два себя спорящих».",
        },
        "uk": {
            "reversed": "Тупикове мовчання, затягнуте рішення, внутрішній шум.",
            "love": "Прямо — пауза, виваженість, небажання обирати. Перевернуто — заморожений конфлікт, страх відкритися.",
            "career": "Прямо — ретельне рішення «або-або», аналіз. Перевернуто — глухий кут вибору, параліч від «а раптом».",
            "health": "Прямо — усвідомлена пауза, баланс, невтручання. Перевернуто — відмова помічати симптоми, голова в пісок.",
            "spirituality": "Прямо — споглядання, внутрішня тиша при зовнішньому шумі. Перевернуто — внутрішній розкол, «двоє себе сперечаються».",
        },
        "en": {
            "reversed": "Dead-end silence, a dragged-out decision, inner noise.",
            "love": "Upright — a pause, weighing things up, avoiding a choice. Reversed — a frozen conflict, fear of opening up.",
            "career": "Upright — a careful either/or decision, analysis. Reversed — a dead end of choice, paralysis from 'what if'.",
            "health": "Upright — a conscious pause, balance, non-interference. Reversed — refusing to notice symptoms, head in the sand.",
            "spirituality": "Upright — contemplation, inner silence amid outer noise. Reversed — inner split, two selves arguing.",
        },
    },
    "Swords-03": {
        "ru": {
            "reversed": "Выход из боли, исцеление сердца, эмоции проясняются.",
            "love": "Прямо — сердечная рана, грустное расставание. Перевёрнуто — начало заживления, принятие потери.",
            "career": "Прямо — боль от неудачи, разбитый план. Перевёрнуто — пересбор, извлечение урока, новый план.",
            "health": "Прямо — боль, горе в теле, грусть. Перевёрнуто — лёгкое выздоровление, выход из депрессивного эпизода.",
            "spirituality": "Прямо — слёзы как очищение, рана души. Перевёрнуто — прощение, отпускание боли.",
        },
        "uk": {
            "reversed": "Вихід із болю, зцілення серця, емоції прояснюються.",
            "love": "Прямо — сердечна рана, сумне розставання. Перевернуто — початок загоєння, прийняття втрати.",
            "career": "Прямо — біль від невдачі, розбитий план. Перевернуто — перезбір, винесення уроку, новий план.",
            "health": "Прямо — біль, горе в тілі, сум. Перевернуто — легке одужання, вихід із депресивного епізоду.",
            "spirituality": "Прямо — сльози як очищення, рана душі. Перевернуто — прощення, відпускання болю.",
        },
        "en": {
            "reversed": "Coming out of pain, healing the heart, emotions clearing.",
            "love": "Upright — a heart wound, a sad parting. Reversed — the beginning of healing, accepting the loss.",
            "career": "Upright — pain of failure, a broken plan. Reversed — reassembling, drawing a lesson, a new plan.",
            "health": "Upright — pain, grief in the body, sadness. Reversed — mild recovery, leaving a depressive episode.",
            "spirituality": "Upright — tears as cleansing, a wound of the soul. Reversed — forgiveness, releasing the pain.",
        },
    },
    "Swords-04": {
        "ru": {
            "reversed": "Тревожный покой, вынужденная пауза, прорыв тайных мыслей.",
            "love": "Прямо — спокойствие, пауза для перезагрузки, отдых от эмоций. Перевёрнуто — тревожное затишье, недоговорённость.",
            "career": "Прямо — ответственный отдых, восстановление сил. Перевёрнуто — «дежурный» отдых, отпуск с телефоном.",
            "health": "Прямо — восстановление, сон, регенерация. Перевёрнуто — беспокойный сон, хроническая усталость.",
            "spirituality": "Прямо — медитация покоя, святая пауза. Перевёрнуто — молитва с тревогой, сон с мыслями.",
        },
        "uk": {
            "reversed": "Тривожний спокій, вимушена пауза, прорив таємних думок.",
            "love": "Прямо — спокій, пауза для перезавантаження, відпочинок від емоцій. Перевернуто — тривожне затишшя, недомовленість.",
            "career": "Прямо — відповідальний відпочинок, відновлення сил. Перевернуто — «чергування» під час відпочинку, відпустка з телефоном.",
            "health": "Прямо — відновлення, сон, регенерація. Перевернуто — неспокійний сон, хронічна втома.",
            "spirituality": "Прямо — медитація спокою, свята пауза. Перевернуто — молитва з тривогою, сон із думками.",
        },
        "en": {
            "reversed": "Anxious calm, a forced pause, secret thoughts breaking through.",
            "love": "Upright — calm, a reset pause, rest from emotions. Reversed — an uneasy lull, things unspoken.",
            "career": "Upright — responsible rest, restoring strength. Reversed — being on duty while resting, a holiday with a phone.",
            "health": "Upright — recovery, sleep, regeneration. Reversed — restless sleep, chronic fatigue.",
            "spirituality": "Upright — meditation of stillness, a holy pause. Reversed — prayer with anxiety, sleep full of thoughts.",
        },
    },
    "Swords-05": {
        "ru": {
            "reversed": "Сожаление о победе, желание мира, отход от конфликта.",
            "love": "Прямо — победа ценой разрыва, принцип дороже союза. Перевёрнуто — желание помириться, цена гордости становится ясной.",
            "career": "Прямо — жёсткая переговорная победа, удар по конкурентам. Перевёрнуто — поиск компромисса, усталость от конфликтов.",
            "health": "Прямо — агрессия к телу, «победный» стиль до истощения. Перевёрнуто — примирение с телом, забота.",
            "spirituality": "Прямо — самоуверенность, одержанная победа духа. Перевёрнуто — смирение, урок об истинной силе.",
        },
        "uk": {
            "reversed": "Жаль про перемогу, бажання миру, відхід від конфлікту.",
            "love": "Прямо — перемога ціною розриву, принцип дорожчий за союз. Перевернуто — бажання помиритися, зрозуміла ціна гордості.",
            "career": "Прямо — жорстка переговорна перемога, удар по конкурентах. Перевернуто — пошук компромісу, втома від конфліктів.",
            "health": "Прямо — агресія до тіла, «переможний» стиль до виснаження. Перевернуто — примирення з тілом, турбота.",
            "spirituality": "Прямо — самовпевненість, здобута перемога духу. Перевернуто — смирення, урок про справжню силу.",
        },
        "en": {
            "reversed": "Regret over victory, a wish for peace, withdrawal from conflict.",
            "love": "Upright — victory at the cost of a breakup, principle dearer than the union. Reversed — a wish to make up, the price of pride becomes clear.",
            "career": "Upright — a tough negotiating win, striking competitors. Reversed — seeking compromise, tired of conflict.",
            "health": "Upright — aggression toward the body, a winning style run to exhaustion. Reversed — making peace with your body, care.",
            "spirituality": "Upright — self-assurance, a won battle of the spirit. Reversed — humility, a lesson in true strength.",
        },
    },
    "Swords-06": {
        "ru": {
            "reversed": "Назад в шторм, незавершённый переход, страх воды.",
            "love": "Прямо — переход к спокойствию, совместный отъезд от проблем. Перевёрнуто — возврат к старым бурям, отложенное расставание.",
            "career": "Прямо — смена места/роли, переход в спокойные воды. Перевёрнуто — застрявший переход, разворот назад.",
            "health": "Прямо — путь к восстановлению, отход от острого состояния. Перевёрнуто — откат, возврат симптомов.",
            "spirituality": "Прямо — движение к свету, вера в дальнее. Перевёрнуто — страх пути, недоверие, топтание на берегу.",
        },
        "uk": {
            "reversed": "Назад у шторм, незавершений перехід, страх води.",
            "love": "Прямо — перехід до спокою, спільний від'їзд від проблем. Перевернуто — повернення до старих бур, відкладене розставання.",
            "career": "Прямо — зміна місця/ролі, перехід у спокійні води. Перевернуто — застряглий перехід, розворот назад.",
            "health": "Прямо — шлях до відновлення, відхід від гострого стану. Перевернуто — відкат, повернення симптомів.",
            "spirituality": "Прямо — рух до світла, віра в далечінь. Перевернуто — страх шляху, недовіра, топтання на березі.",
        },
        "en": {
            "reversed": "Back into the storm, an unfinished crossing, fear of the water.",
            "love": "Upright — moving toward calm, leaving problems together. Reversed — returning to old storms, deferred parting.",
            "career": "Upright — changing place/role, moving into calmer waters. Reversed — a stuck transition, turning back.",
            "health": "Upright — a path to recovery, moving away from an acute state. Reversed — a relapse, symptoms returning.",
            "spirituality": "Upright — moving toward light, faith in the far shore. Reversed — fear of the journey, mistrust, shuffling on the bank.",
        },
    },
    "Swords-07": {
        "ru": {
            "reversed": "Правда выходит на свет, самооправдание рушится.",
            "love": "Прямо — недоговорённости, хитрость в паре, «украденные» чувства. Перевёрнуто — разоблачение лжи, честный разговор.",
            "career": "Прямо — бегство от ответственности, хитрости, кража идей. Перевёрнуто — прозрение схемы, разрыв ловушки.",
            "health": "Прямо — самообман в стиле жизни, «тихушник». Перевёрнуто — признание проблемы, честность с врачом.",
            "spirituality": "Прямо — хитрость духа, ребяческая ловкость. Перевёрнуто — выход к честности, совесть празднует.",
        },
        "uk": {
            "reversed": "Правда виходить на світло, самовиправдання рушиться.",
            "love": "Прямо — недомовленості, хитрість у парі, «вкрадені» почуття. Перевернуто — викриття брехні, чесна розмова.",
            "career": "Прямо — втеча від відповідальності, хитрощі, крадіжка ідей. Перевернуто — прозріння схеми, розрив пастки.",
            "health": "Прямо — самообман у стилі життя, «тихушник». Перевернуто — визнання проблеми, чесність із лікарем.",
            "spirituality": "Прямо — хитрість духу, дитяча спритність. Перевернуто — вихід до чесності, совість святкує.",
        },
        "en": {
            "reversed": "Truth coming to light, self-justification crumbling.",
            "love": "Upright — hidden things, cunning in the couple, 'stolen' feelings. Reversed — a lie exposed, an honest talk.",
            "career": "Upright — dodging responsibility, tricks, stealing ideas. Reversed — seeing through the scheme, escaping the trap.",
            "health": "Upright — self-deception in lifestyle, hiding. Reversed — admitting a problem, honesty with a doctor.",
            "spirituality": "Upright — cunning of the spirit, childlike cleverness. Reversed — moving toward honesty, conscience celebrating.",
        },
    },
    "Swords-08": {
        "ru": {
            "reversed": "Освобождение от самоограничений, разрыв пут, действие.",
            "love": "Прямо — чувство связанности, страхи в отношениях. Перевёрнуто — шаг к свободе, та ясность, что снимает путы.",
            "career": "Прямо — ощущение ловушки обстоятельств, «не могу» ментальное. Перевёрнуто — выход, поиск ходов, решимость.",
            "health": "Прямо — напряжение от самокритики, «зажатая» спина. Перевёрнуто — расслабление, исцеление страхов.",
            "spirituality": "Прямо — скованность убеждениями, темнота веры. Перевёрнуто — освобождение ума, свет истины.",
        },
        "uk": {
            "reversed": "Звільнення від самообмежень, розрив пут, дія.",
            "love": "Прямо — відчуття зв'язаності, страхи у стосунках. Перевернуто — крок до свободи, ясність, що знімає пута.",
            "career": "Прямо — відчуття пастки обставин, ментальне «не можу». Перевернуто — вихід, пошук ходів, рішучість.",
            "health": "Прямо — напруга від самокритики, «затиснена» спина. Перевернуто — розслаблення, зцілення страхів.",
            "spirituality": "Прямо — скутість переконаннями, темрява віри. Перевернуто — звільнення розуму, світло істини.",
        },
        "en": {
            "reversed": "Breaking free from self-limitation, bursting bonds, action.",
            "love": "Upright — feeling bound, fears in relationships. Reversed — a step toward freedom, the clarity that lifts the bonds.",
            "career": "Upright — feeling trapped by circumstances, mental 'I can't'. Reversed — a way out, finding moves, resolve.",
            "health": "Upright — tension from self-criticism, a tight back. Reversed — relaxation, healing the fears.",
            "spirituality": "Upright — bound by beliefs, darkness of faith. Reversed — liberating the mind, the light of truth.",
        },
    },
    "Swords-09": {
        "ru": {
            "reversed": "Сон уходит, тревога спадает, наступает утро.",
            "love": "Прямо — ночная тревога о чувствах, накрутка. Перевёрнуто — прояснение, разговор, снятие кошмара.",
            "career": "Прямо — бессонница над проектом, страх неудачи. Перевёрнуто — паника уменьшается, план проясняется.",
            "health": "Прямо — тревожное состояние, вегетативные симптомы. Перевёрнуто — улучшение, нормализация сна.",
            "spirituality": "Прямо — тёмная ночь души, страхи на пределе. Перевёрнуто — рассвет, благодарный выход.",
        },
        "uk": {
            "reversed": "Сон минає, тривога спадає, настає ранок.",
            "love": "Прямо — нічна тривога про почуття, накрутка. Перевернуто — прояснення, розмова, зняття кошмару.",
            "career": "Прямо — безсоння над проєктом, страх невдачі. Перевернуто — паніка зменшується, план прояснюється.",
            "health": "Прямо — тривожний стан, вегетативні симптоми. Перевернуто — покращення, нормалізація сну.",
            "spirituality": "Прямо — темна ніч душі, страхи на межі. Перевернуто — світанок, вдячний вихід.",
        },
        "en": {
            "reversed": "Sleep passing, anxiety easing, morning coming.",
            "love": "Upright — night-time worries about feelings, catastrophising. Reversed — clarity, a talk, lifting the nightmare.",
            "career": "Upright — sleepless nights over a project, fear of failure. Reversed — panic fading, the plan becoming clear.",
            "health": "Upright — anxious state, vegetative symptoms. Reversed — improvement, sleep normalising.",
            "spirituality": "Upright — the dark night of the soul, fears at their peak. Reversed — dawn, a grateful exit.",
        },
    },
    "Swords-10": {
        "ru": {
            "reversed": "Восстание из пепла, исцеление глубокой раны, конец «дёрна».",
            "love": "Прямо — финиш отношений с болью, точка невозврата. Перевёрнуто — облегчение после конца, шанс выпрямиться.",
            "career": "Прямо — катастрофический конец, полный крах плана. Перевёрнуто — дно достигнуто, начало восстановления.",
            "health": "Прямо — кризис, истощение, глубокая усталость. Перевёрнуто — выход из кризиса, реабилитация.",
            "spirituality": "Прямо — крест души, предельное одиночество пути. Перевёрнуто — воскресение, внутренняя победа.",
        },
        "uk": {
            "reversed": "Повстання з попелу, зцілення глибокої рани, кінець «жнив».",
            "love": "Прямо — фініш стосунків із болем, точка неповернення. Перевернуто — полегшення після кінця, шанс випростатися.",
            "career": "Прямо — катастрофічний кінець, повний крах плану. Перевернуто — дно досягнуте, початок відновлення.",
            "health": "Прямо — криза, виснаження, глибока втома. Перевернуто — вихід із кризи, реабілітація.",
            "spirituality": "Прямо — хрест душі, гранична самотність шляху. Перевернуто — воскресіння, внутрішня перемога.",
        },
        "en": {
            "reversed": "Rising from the ashes, healing a deep wound, the end of the drudgery.",
            "love": "Upright — the end of a relationship with pain, a point of no return. Reversed — relief after the end, a chance to straighten up.",
            "career": "Upright — catastrophic end, total collapse of a plan. Reversed — rock bottom reached, recovery begins.",
            "health": "Upright — crisis, exhaustion, deep fatigue. Reversed — leaving the crisis, rehabilitation.",
            "spirituality": "Upright — a cross of the soul, the ultimate solitude of the path. Reversed — resurrection, inner victory.",
        },
    },
    "Swords-11": {
        "ru": {
            "reversed": "Острые слова без цели, наивная резкость, сплетни.",
            "love": "Прямо — любопытный лёгкий ум, флирт-интеллект, наблюдение. Перевёрнуто — колкие фразы, «двое детей с мечами».",
            "career": "Прямо — идеи-разведка, наблюдательность, новые слова. Перевёрнуто — недосказанные идеи, резкие заявления.",
            "health": "Прямо — гибкость ума, любознательность. Перевёрнуто — нервная живость, трепетная психика.",
            "spirituality": "Прямо — юность искателя, вопросы без ответов. Перевёрнуто — слова, опережающие мысль.",
        },
        "uk": {
            "reversed": "Гострі слова без мети, наївна різкість, плітки.",
            "love": "Прямо — допитливий легкий розум, флірт-інтелект, спостереження. Перевернуто — колючі фрази, «двоє дітей із мечами».",
            "career": "Прямо — ідеї-розвідка, спостережливість, нові слова. Перевернуто — недоказані ідеї, різкі заяви.",
            "health": "Прямо — гнучкість розуму, допитливість. Перевернуто — нервова жвавість, трепетна психіка.",
            "spirituality": "Прямо — юність шукача, питання без відповідей. Перевернуто — слова, що випереджають думку.",
        },
        "en": {
            "reversed": "Sharp words without aim, naive harshness, gossip.",
            "love": "Upright — an inquisitive light mind, intellectual flirtation, observation. Reversed — barbed phrases, two children with swords.",
            "career": "Upright — reconnaissance ideas, attentiveness, fresh vocabulary. Reversed — undeveloped ideas, sharp statements.",
            "health": "Upright — mental flexibility, curiosity. Reversed — nervous liveliness, delicate psyche.",
            "spirituality": "Upright — the youth of the seeker, questions without answers. Reversed — words outrunning thought.",
        },
    },
    "Swords-12": {
        "ru": {
            "reversed": "Догматик-гонец, опрометчивая скорость, требование играть по-своему.",
            "love": "Прямо — страстный умом разговор, рывок к пониманию. Перевёрнуто — агрессивные споры, скорость без слушания.",
            "career": "Прямо — прорывная аргументация, быстрые решения, адреналин сделок. Перевёрнуто — спешка в словах, конфликтные переговоры.",
            "health": "Прямо — энергия ума, бодрость. Перевёрнуто — нервы на пределе, бессонница гонца.",
            "spirituality": "Прямо — словно меч истины в движении, борьба света. Перевёрнуто — воинственность духа, войны за идею.",
        },
        "uk": {
            "reversed": "Догматик-гонець, нерозважлива швидкість, вимога грати по-своєму.",
            "love": "Прямо — пристрасна розумна розмова, ривок до розуміння. Перевернуто — агресивні суперечки, швидкість без слухання.",
            "career": "Прямо — проривна аргументація, швидкі рішення, адреналін угод. Перевернуто — поспіх у словах, конфліктні переговори.",
            "health": "Прямо — енергія розуму, бадьорість. Перевернуто — нерви на межі, безсоння гінця.",
            "spirituality": "Прямо — немов меч істини в русі, боротьба світла. Перевернуто — войовничість духу, війни за ідею.",
        },
        "en": {
            "reversed": "A dogmatic messenger, reckless speed, demanding to play your way.",
            "love": "Upright — a passionate, clever conversation, a rush toward understanding. Reversed — aggressive arguments, speed without listening.",
            "career": "Upright — breakthrough argumentation, quick decisions, adrenaline deals. Reversed — haste in words, confrontational meetings.",
            "health": "Upright — mental energy, vigour. Reversed — nerves at the limit, a messenger's insomnia.",
            "spirituality": "Upright — like a sword of truth in motion, the struggle of light. Reversed — bellicosity of spirit, wars over an idea.",
        },
    },
    "Swords-13": {
        "ru": {
            "reversed": "Холодная критика, жестокость ума, сухая логика без сердца.",
            "love": "Прямо — ясный взгляд на отношения, честность без сладкого. Перевёрнуто — холод в паре, язвительность.",
            "career": "Прямо — аналитика, независимый интеллект, кристальная честность. Перевёрнуто — критиканство, жёсткий менторинг.",
            "health": "Прямо — ясный диагноз, отрешённый ум. Перевёрнуто — стресс от самокритики, напряжение психе.",
            "spirituality": "Прямо — чистота истины, меч-прозрение. Перевёрнуто — безжалостность к себе, сухая вера.",
        },
        "uk": {
            "reversed": "Холодна критика, жорстокість розуму, суха логіка без серця.",
            "love": "Прямо — ясний погляд на стосунки, чесність без цукру. Перевернуто — холод у парі, уїдливість.",
            "career": "Прямо — аналітика, незалежний інтелект, кришталева чесність. Перевернуто — критиканство, жорсткий менторинг.",
            "health": "Прямо — ясний діагноз, відсторонений розум. Перевернуто — стрес від самокритики, напруга психіки.",
            "spirituality": "Прямо — чистота істини, меч-прозріння. Перевернуто — безжальність до себе, суха віра.",
        },
        "en": {
            "reversed": "Cold criticism, cruelty of the mind, dry logic without heart.",
            "love": "Upright — a clear view of the relationship, honesty without sugar-coating. Reversed — coldness in the couple, barbed remarks.",
            "career": "Upright — analytics, independent intellect, crystal honesty. Reversed — fault-finding, harsh mentoring.",
            "health": "Upright — a clear diagnosis, a detached mind. Reversed — stress from self-criticism, psychic strain.",
            "spirituality": "Upright — purity of truth, the sword of insight. Reversed — ruthlessness toward yourself, dry faith.",
        },
    },
    "Swords-14": {
        "ru": {
            "reversed": "Гнев ума, излишняя жёсткость, интеллект на службе эго.",
            "love": "Прямо — зрелый честный союз, ясные правила любви. Перевёрнуто — авторитаризм в паре, правда без такта.",
            "career": "Прямо — стратег, эксперт, ясный закон и порядок. Перевёрнуто — тирания ума, давление авторитетом.",
            "health": "Прямо — крепкая нервная система, ясность ума. Перевёрнуто — перегретый ум, головные боли принуждения.",
            "spirituality": "Прямо — мудрость, справедливый дух, зрелость искателя. Перевёрнуто — гордыня рациональности, отказ от тайны.",
        },
        "uk": {
            "reversed": "Гнів розуму, надмірна жорсткість, інтелект на службі его.",
            "love": "Прямо — зрілий чесний союз, ясні правила любові. Перевернуто — авторитаризм у парі, правда без такту.",
            "career": "Прямо — стратег, експерт, ясний закон і порядок. Перевернуто — тиранія розуму, тиск авторитетом.",
            "health": "Прямо — міцна нервова система, ясність розуму. Перевернуто — перегрітий розум, головний біль примушування.",
            "spirituality": "Прямо — мудрість, справедливий дух, зрілість шукача. Перевернуто — гординя раціональності, відмова від таємниці.",
        },
        "en": {
            "reversed": "Wrath of the mind, excessive harshness, intellect serving the ego.",
            "love": "Upright — a mature honest union, clear rules of love. Reversed — authoritarianism in the couple, truth without tact.",
            "career": "Upright — strategist, expert, clear law and order. Reversed — tyranny of the mind, pressure by authority.",
            "health": "Upright — a strong nervous system, clarity of mind. Reversed — an overheated mind, headaches from coercion.",
            "spirituality": "Upright — wisdom, a just spirit, maturity of the seeker. Reversed — pride of rationality, refusing mystery.",
        },
    },
}