# -*- coding: utf-8 -*-
"""Значения младших арканов Жезлов (Wands, стихия Огня): перевёрнутое + сферы."""
WANDS = {
    "Wands-01": {
        "ru": {
            "reversed": "Ложный старт, нерастраченный потенциал, оттяжка творчества.",
            "love": "Прямо — искра, новый интерес, флирт с огоньком. Перевёрнуто — нерешительный старт, угасшее влечение.",
            "career": "Прямо — старт! идея, вдохновение, решительный первый шаг. Перевёрнуто — откладывание запуска, страх первого шага.",
            "health": "Прямо — прилив энергии, желание двигаться. Перевёрнуто — слабая мотивация, застой жизненных сил.",
            "spirituality": "Прямо — искра духа, творческий импульс свыше. Перевёрнуто — творческий ступор, угасший огонь.",
        },
        "uk": {
            "reversed": "Хибний старт, невитрачений потенціал, відтягування творчості.",
            "love": "Прямо — іскра, новий інтерес, флірт із вогником. Перевернуто — нерішучий старт, згасле захоплення.",
            "career": "Прямо — старт! ідея, натхнення, рішучий перший крок. Перевернуто — відкладання запуску, страх першого кроку.",
            "health": "Прямо — приплив енергії, бажання рухатися. Перевернуто — слабка мотивація, застій життєвих сил.",
            "spirituality": "Прямо — іскра духу, творчий імпульс згори. Перевернуто — творчий ступор, згаслий вогонь.",
        },
        "en": {
            "reversed": "False start, unused potential, putting off creativity.",
            "love": "Upright — a spark, new interest, flirting with fire. Reversed — a hesitant start, faded attraction.",
            "career": "Upright — launch! an idea, inspiration, a decisive first step. Reversed — postponing the start, fear of the first step.",
            "health": "Upright — a surge of energy, the urge to move. Reversed — low motivation, stagnant vitality.",
            "spirituality": "Upright — a spark of spirit, creative impulse from above. Reversed — creative block, fire gone out.",
        },
    },
    "Wands-02": {
        "ru": {
            "reversed": "Страх масштаба, планы без действия, упущенные горизонты.",
            "love": "Прямо — планирование будущего с партнёром, видение союза. Перевёрнуто — сомнения в перспективе отношений.",
            "career": "Прямо — стратегия, амбиции, взгляд с высоты. Перевёрнуто — тяга «сам за всё», нежелание делегировать и решаться.",
            "health": "Прямо — планирование активного восстановления, спорт как проект. Перевёрнуто — «в понедельник начну», отсрочки.",
            "spirituality": "Прямо — широкий взгляд, выбор своего пути на распутье. Перевёрнуто — потеря горизонта, мелкотемье.",
        },
        "uk": {
            "reversed": "Страх масштабу, плани без дії, втрачені горизонти.",
            "love": "Прямо — планування майбутнього з партнером, бачення союзу. Перевернуто — сумніви в перспективі стосунків.",
            "career": "Прямо — стратегія, амбіції, погляд з висоти. Перевернуто — тяга «сам за все», небажання делегувати й наважуватися.",
            "health": "Прямо — планування активного відновлення, спорт як проєкт. Перевернуто — «з понеділка почну», відтермінування.",
            "spirituality": "Прямо — широкий погляд, вибір свого шляху на роздоріжжі. Перевернуто — втрата горизонту, дрібнотем'я.",
        },
        "en": {
            "reversed": "Fear of scale, plans without action, missed horizons.",
            "love": "Upright — planning a future with a partner, seeing the union. Reversed — doubts about the relationship's prospects.",
            "career": "Upright — strategy, ambition, a view from above. Reversed — doing everything yourself, refusing to decide and delegate.",
            "health": "Upright — planning active recovery, sport as a project. Reversed — starting Monday, postponing.",
            "spirituality": "Upright — a broad view, choosing your path at the crossroads. Reversed — losing the horizon, petty concerns.",
        },
    },
    "Wands-03": {
        "ru": {
            "reversed": "Перенапряжение, помехи, отложенный старт.",
            "love": "Прямо — союз развивается, совместный рост к общей цели. Перевёрнуто — разногласия по «маршруту» пары.",
            "career": "Прямо — первые плоды, выход на рынок, расширение. Перевёрнуто — задержки сбыта, непросчитанные риски.",
            "health": "Прямо — хороший прогресс, движение к цели по плану. Перевёрнуто — перегруз, тревожность от ожидания результатов.",
            "spirituality": "Прямо — плоды роста, видение, вера в развитие. Перевёрнуто — нетерпение, сомнение в плодотворности пути.",
        },
        "uk": {
            "reversed": "Перенапруження, перешкоди, відкладений старт.",
            "love": "Прямо — союз розвивається, спільне зростання до спільної мети. Перевернуто — розбіжності щодо «маршруту» пари.",
            "career": "Прямо — перші плоди, вихід на ринок, розширення. Перевернуто — затримки збуту, не прораховані ризики.",
            "health": "Прямо — добрий прогрес, рух до мети за планом. Перевернуто — перевантаження, тривожність від очікування результатів.",
            "spirituality": "Прямо — плоди зростання, бачення, віра в розвиток. Перевернуто — нетерпіння, сумнів у плодючості шляху.",
        },
        "en": {
            "reversed": "Overexertion, obstacles, delayed start.",
            "love": "Upright — the union grows, growing together toward a shared goal. Reversed — disagreements over the couple's path.",
            "career": "Upright — first fruits, going to market, expansion. Reversed — stalled sales, uncalculated risks.",
            "health": "Upright — good progress, moving toward the goal on plan. Reversed — overload, anxiety while waiting for results.",
            "spirituality": "Upright — fruits of growth, vision, faith in development. Reversed — impatience, doubting the fruitfulness of the path.",
        },
    },
    "Wands-04": {
        "ru": {
            "reversed": "Нестабильный фундамент, преждевременный праздник, укрытые проблемы.",
            "love": "Прямо — праздник, встреча с близкими, помолвка. Перевёрнуто — праздник «для галочки», напряжение в семье.",
            "career": "Прямо — завершение этапа, признание, командное торжество. Перевёрнуто — заслуги не оценены, показной успех.",
            "health": "Прямо — отличное самочувствие, восстановление после нагрузок. Перевёрнуто — усталость маскируется весельем.",
            "spirituality": "Прямо — радость от итогов, благодарность, дом души. Перевёрнуто — праздник как побег от глубины.",
        },
        "uk": {
            "reversed": "Нестабільний фундамент, передчасне свято, приховані проблеми.",
            "love": "Прямо — свято, зустріч із близькими, заручини. Перевернуто — свято «для формальності», напруга в родині.",
            "career": "Прямо — завершення етапу, визнання, командна радість. Перевернуто — заслуги не оцінені, показний успіх.",
            "health": "Прямо — чудове самопочуття, відновлення після навантажень. Перевернуто — втома маскується веселощами.",
            "spirituality": "Прямо — радість від підсумків, вдячність, дім душі. Перевернуто — свято як втеча від глибини.",
        },
        "en": {
            "reversed": "Unstable foundation, premature celebration, hidden problems.",
            "love": "Upright — celebration, meeting the family, an engagement. Reversed — celebrating for show, family tension.",
            "career": "Upright — closing a stage, recognition, team triumph. Reversed — merits unappreciated, ostentatious success.",
            "health": "Upright — great wellbeing, recovery after exertion. Reversed — fatigue masked by fun.",
            "spirituality": "Upright — joy at the outcome, gratitude, the home of the soul. Reversed — celebration as an escape from depth.",
        },
    },
    "Wands-05": {
        "ru": {
            "reversed": "Эскалация конфликта, обиды, нечестная борьба.",
            "love": "Прямо — споры в паре, вспышки, жар выяснения правды. Перевёрнуто — тлеющий конфликт, пассивная агрессия.",
            "career": "Прямо — конкуренция, жёсткие дебаты, борьба за место. Перевёрнуто — подковёрная борьба, старая вражда.",
            "health": "Прямо — воспалительные процессы, перенапряжение нервной системы. Перевёрнуто — затяжное раздражение, расшатанные нервы.",
            "spirituality": "Прямо — огонь испытаний, школа характера через конфликт. Перевёрнуто — разрозненность, конфликт внутри.",
        },
        "uk": {
            "reversed": "Ескалація конфлікту, образи, нечесна боротьба.",
            "love": "Прямо — суперечки в парі, спалахи, жар з'ясування правди. Перевернуто — тліючий конфлікт, пасивна агресія.",
            "career": "Прямо — конкуренція, жорсткі дебати, боротьба за місце. Перевернуто — підкилимна боротьба, стара ворожнеча.",
            "health": "Прямо — запальні процеси, перенапруження нервової системи. Перевернуто — затяжне роздратування, розхитані нерви.",
            "spirituality": "Прямо — вогонь випробувань, школа характеру через конфлікт. Перевернуто — роз'єднаність, внутрішній конфлікт.",
        },
        "en": {
            "reversed": "Escalating conflict, grudges, dirty fighting.",
            "love": "Upright — rows in the couple, flare-ups, the heat of truth-telling. Reversed — smouldering conflict, passive aggression.",
            "career": "Upright — competition, tough debates, fighting for your place. Reversed — back-room battles, old feuds.",
            "health": "Upright — inflammatory processes, nervous strain. Reversed — lingering irritation, frayed nerves.",
            "spirituality": "Upright — the fire of trials, character forged through conflict. Reversed — disunity, inner conflict.",
        },
    },
    "Wands-06": {
        "ru": {
            "reversed": "Задержанный триумф, самолюбование, неустойчивый успех.",
            "love": "Прямо — победа в делах сердца, признание, праздничная связь. Перевёрнуто — тщеславие вместо чувств, «победа любой ценой».",
            "career": "Прямо — признание, продвижение, почести. Перевёрнуто — эго-проект, слава без заслуг, спад после успеха.",
            "health": "Прямо — подъём, бодрость, уверенность в себе. Перевёрнуто — самоуверенность, игнор сигналов тела.",
            "spirituality": "Прямо — признание пути, свет победы духа. Перевёрнуто — гордыня, успех как вериги.",
        },
        "uk": {
            "reversed": "Затриманий тріумф, самолюбування, нестійкий успіх.",
            "love": "Прямо — перемога в справах серця, визнання, святковий зв'язок. Перевернуто — марнославство замість почуттів, «перемога будь-якою ціною».",
            "career": "Прямо — визнання, просування, почесті. Перевернуто — его-проєкт, слава без заслуг, спад після успіху.",
            "health": "Прямо — підйом, бадьорість, упевненість у собі. Перевернуто — самовпевненість, ігнорування сигналів тіла.",
            "spirituality": "Прямо — визнання шляху, світло перемоги духу. Перевернуто — гординя, успіх як пута.",
        },
        "en": {
            "reversed": "Delayed triumph, self-adoration, unstable success.",
            "love": "Upright — victory in matters of the heart, recognition, a celebratory bond. Reversed — vanity instead of feeling, winning at any cost.",
            "career": "Upright — recognition, promotion, honours. Reversed — an ego project, fame without merit, a post-success slump.",
            "health": "Upright — uplift, vigour, self-confidence. Reversed — overconfidence, ignoring the body's signals.",
            "spirituality": "Upright — recognition of the path, the light of a spiritual victory. Reversed — pride, success as shackles.",
        },
    },
    "Wands-07": {
        "ru": {
            "reversed": "Сдача позиций, усталое сопротивление, разобщённость.",
            "love": "Прямо — отстаивание отношений, готовность бороться за пару. Перевёрнуто — выматывающие переговоры, один «держится» за двоих.",
            "career": "Прямо — защита позиции, стойкость под давлением. Перевёрнуто — чувство осаждённости, страх сдаться или продолжать.",
            "health": "Прямо — иммунитет, сопротивление нагрузкам, стойкость. Перевёрнуто — истощение защитных сил, частые «бои» с болезнями.",
            "spirituality": "Прямо — духовная стойкость, отстаивание своих ценностей. Перевёрнуто — внутренняя осада, измотанность веры.",
        },
        "uk": {
            "reversed": "Здача позицій, втомлений опір, роз'єднаність.",
            "love": "Прямо — відстоювання стосунків, готовність боротися за пару. Перевернуто — виснажливі переговори, один «тримається» за двох.",
            "career": "Прямо — захист позиції, стійкість під тиском. Перевернуто — відчуття облоги, страх здатися чи продовжити.",
            "health": "Прямо — імунітет, опір навантаженням, стійкість. Перевернуто — виснаження захисних сил, часті «бої» з хворобами.",
            "spirituality": "Прямо — духовна стійкість, відстоювання своїх цінностей. Перевернуто — внутрішня облога, виснаження віри.",
        },
        "en": {
            "reversed": "Giving ground, weary resistance, disunity.",
            "love": "Upright — defending the relationship, ready to fight for the couple. Reversed — draining negotiations, one holding the line for two.",
            "career": "Upright — holding your position, standing firm under pressure. Reversed — feeling besieged, fear of giving up or going on.",
            "health": "Upright — immunity, resistance to strain, resilience. Reversed — depleted defences, frequent battles with illness.",
            "spirituality": "Upright — spiritual stamina, standing by your values. Reversed — inner siege, faith worn thin.",
        },
    },
    "Wands-08": {
        "ru": {
            "reversed": "Отложенная хорошая новость, суета, дурные вести-заминки.",
            "love": "Прямо — стремительное развитие, новости, полёт чувств. Перевёрнуто — спешка романтик-ковбоя, недосказанность на скорости.",
            "career": "Прямо — быстрый прогресс, обмен новостями, письма/сделки. Перевёрнуто — суета, задержки связи, «эффект кролика и черепахи».",
            "health": "Прямо — быстрые результаты, лёгкость, движение воздуха. Перевёрнуто — нервный темп, бессонница от скоростей.",
            "spirituality": "Прямо — поток, лёгкость духа, вести свыше. Перевёрнуто — суетливость вместо тишины, разбросанный ум.",
        },
        "uk": {
            "reversed": "Відкладена добра звістка, метушня, заминки.",
            "love": "Прямо — стрімкий розвиток, новини, політ почуттів. Перевернуто — поспіх, недомовленість на швидкості.",
            "career": "Прямо — швидкий прогрес, обмін новинами, листи/угоди. Перевернуто — метушня, затримки зв'язку, «ефект зайця й черепахи».",
            "health": "Прямо — швидкі результати, легкість, рух повітря. Перевернуто — нервовий темп, безсоння від швидкостей.",
            "spirituality": "Прямо — потік, легкість духу, вісті згори. Перевернуто — метушливість замість тиші, розпорошений розум.",
        },
        "en": {
            "reversed": "Delayed good news, flurry, hold-ups.",
            "love": "Upright — rapid development, news, a flight of feeling. Reversed — haste, things left unsaid at speed.",
            "career": "Upright — quick progress, exchange of news, letters/deals. Reversed — flurry, communication delays, the hare and the tortoise.",
            "health": "Upright — fast results, lightness, airy movement. Reversed — nervous pace, sleeplessness from speed.",
            "spirituality": "Upright — flow, lightness of spirit, tidings from above. Reversed — bustle instead of stillness, a scattered mind.",
        },
    },
    "Wands-09": {
        "ru": {
            "reversed": "На пределе, паранойя рисков, готовность сдаться после боя.",
            "love": "Прямо — бдительность в чувствах, защита сердца. Перевёрнуто — недоверие, страх, что партнёр «не тот».",
            "career": "Прямо — стойкость при финальной проверке, досмотреть проект. Перевёрнуто — хроническая оборона, выгорание стража.",
            "health": "Прямо — стойкая защита, хорошая сопротивляемость. Перевёрнуто — истощение, постоянная боеготовность без отдыха.",
            "spirituality": "Прямо — верная позиция, готовность к последней битве. Перевёрнуто — страхи как крепость, обороняющийся дух.",
        },
        "uk": {
            "reversed": "На межі, параноя ризиків, готовність здатися після бою.",
            "love": "Прямо — пильність у почуттях, захист серця. Перевернуто — недовіра, страх, що партнер «не той».",
            "career": "Прямо — стійкість на фінальній перевірці, додивитися проєкт. Перевернуто — хронічна оборона, вигорання вартового.",
            "health": "Прямо — стійкий захист, добра опірність. Перевернуто — виснаження, постійна бойова готовність без відпочинку.",
            "spirituality": "Прямо — вірна позиція, готовність до останньої битви. Перевернуто — страхи як фортеця, дух в обороні.",
        },
        "en": {
            "reversed": "At the limit, paranoia of risks, ready to surrender after the fight.",
            "love": "Upright — vigilance in feeling, guarding the heart. Reversed — mistrust, fearing the partner is 'not the one'.",
            "career": "Upright — standing firm at the final check, seeing the project through. Reversed — chronic defence, guard burnout.",
            "health": "Upright — sturdy defences, good resistance. Reversed — exhaustion, constant battle readiness without rest.",
            "spirituality": "Upright — holding your ground, ready for the last battle. Reversed — fears as a fortress, spirit on the defensive.",
        },
    },
    "Wands-10": {
        "ru": {
            "reversed": "Распределение ноши, делегирование, первые сброшенные брёвна.",
            "love": "Прямо — перегрузка в отношениях, когда чувства стали «доставкой». Перевёрнуто — перекладывание ответственности, готовность просить помощи.",
            "career": "Прямо — перегруз задач, финальный спринт перед сдачей. Перевёрнуто — разделение обязанностей, облегчение ноши.",
            "health": "Прямо — истощение, хроническая усталость, «несу всё». Перевёрнуто — шаг к разгрузке, делегирование ухода.",
            "spirituality": "Прямо — испытание ношей, дорога, ведущая в гору. Перевёрнуто — осознание «что можно не нести».",
        },
        "uk": {
            "reversed": "Розподіл ноші, делегування, перші скинуті колоди.",
            "love": "Прямо — перевантаження у стосунках, коли почуття стали «доставкою». Перевернуто — перекладання відповідальності, готовність просити допомоги.",
            "career": "Прямо — перевантаження завдань, фінальний спринт перед здачею. Перевернуто — розподіл обов'язків, полегшення ноші.",
            "health": "Прямо — виснаження, хронічна втома, «несу все». Перевернуто — крок до розвантаження, делегування турботи.",
            "spirituality": "Прямо — випробування ношею, дорога вгору. Перевернуто — усвідомлення «що можна не нести».",
        },
        "en": {
            "reversed": "Sharing the burden, delegating, first logs put down.",
            "love": "Upright — overload in the relationship, feeling like a courier for your feelings. Reversed — shifting responsibility, ready to ask for help.",
            "career": "Upright — task overload, final sprint before delivery. Reversed — splitting duties, lightening the load.",
            "health": "Upright — exhaustion, chronic fatigue, carrying everything. Reversed — a step toward unloading, delegating care.",
            "spirituality": "Upright — trial by burden, a road leading uphill. Reversed — realising what you need not carry.",
        },
    },
    "Wands-11": {
        "ru": {
            "reversed": "Отложенное сообщение, необдуманные слухи, новости вторых рук.",
            "love": "Прямо — игривость, вестник чувств, откровенное признание. Перевёрнуто — недосказанность, слухи о паре.",
            "career": "Прямо — новые идеи, энтузиазм стажёра, обучение. Перевёрнуто — разбросанность, переоценка своих сил.",
            "health": "Прямо — гибкость, лёгкость, энергия новичка. Перевёрнуто — нестабильный режим, перепады активности.",
            "spirituality": "Прямо — открытый ум, любопытство к духовному. Перевёрнуто — поверхностность, рассеянный поиск.",
        },
        "uk": {
            "reversed": "Відкладене повідомлення, необдумані чутки, новини з других рук.",
            "love": "Прямо — грайливість, вісник почуттів, відверте зізнання. Перевернуто — недомовленість, чутки про пару.",
            "career": "Прямо — нові ідеї, ентузіазм стажиста, навчання. Перевернуто — розкиданість, переоцінка своїх сил.",
            "health": "Прямо — гнучкість, легкість, енергія новачка. Перевернуто — нестабільний режим, перепади активності.",
            "spirituality": "Прямо — відкритий розум, цікавість до духовного. Перевернуто — поверховість, розпорошений пошук.",
        },
        "en": {
            "reversed": "A delayed message, thoughtless gossip, second-hand news.",
            "love": "Upright — playfulness, a messenger of feeling, an open confession. Reversed — things unsaid, gossip about the couple.",
            "career": "Upright — new ideas, a trainee's enthusiasm, learning. Reversed — scattered focus, overestimating your strength.",
            "health": "Upright — flexibility, lightness, beginner's energy. Reversed — unstable routine, swings of activity.",
            "spirituality": "Upright — an open mind, curiosity about the spiritual. Reversed — shallowness, scattered seeking.",
        },
    },
    "Wands-12": {
        "ru": {
            "reversed": "Спешка вкрива, упущенные детали, поспешные выводы.",
            "love": "Прямо — страстный рывок, кавалер-огонь, смелое признание. Перевёрнуто — быстрые чувства, слишком горячая голова.",
            "career": "Прямо — решительный прорыв, скорость, дерзость. Перевёрнуто — поспешные решения, поломки от спешки.",
            "health": "Прямо — взрывная энергия, порыв к движению. Перевёрнуто — перегруз сердца, травмы «на полном скаку».",
            "spirituality": "Прямо — дерзновение духа, огонь поиска. Перевёрнуто — импульсивность вместо глубины.",
        },
        "uk": {
            "reversed": "Поспіх підводить, втрачені деталі, поспішні висновки.",
            "love": "Прямо — пристрасний ривок, кавалер-вогонь, сміливе зізнання. Перевернуто — швидкі почуття, надто гаряча голова.",
            "career": "Прямо — рішучий прорив, швидкість, зухвалість. Перевернуто — поспішні рішення, поломки від поспіху.",
            "health": "Прямо — вибухова енергія, порив до руху. Перевернуто — перевантаження серця, травми «на повному скаку».",
            "spirituality": "Прямо — зухвалість духу, вогонь пошуку. Перевернуто — імпульсивність замість глибини.",
        },
        "en": {
            "reversed": "Haste betrays you, missed details, snap conclusions.",
            "love": "Upright — a passionate dash, a fiery suitor, bold confession. Reversed — fast feelings, too hot a head.",
            "career": "Upright — a decisive breakthrough, speed, daring. Reversed — rash decisions, breakdowns from haste.",
            "health": "Upright — explosive energy, urge to move. Reversed — heart strain, injuries at full gallop.",
            "spirituality": "Upright — boldness of spirit, fire of the search. Reversed — impulsiveness instead of depth.",
        },
    },
    "Wands-13": {
        "ru": {
            "reversed": "Ревность, собственничество, перегрев самооценки.",
            "love": "Прямо — яркая, страстная и независимая любовь. Перевёрнуто — ревность, эго, огонь, сжигающий пару.",
            "career": "Прямо — энергия, харизма, лидерство, тепло к команде. Перевёрнуто — тирания харизмы, выгорание команды.",
            "health": "Прямо — жизненный тонус, яркость, огненная энергия. Перевёрнуто — перегрев, гнев, «пожар» в теле.",
            "spirituality": "Прямо — ясная воля, духовная страсть, зрелый огонь. Перевёрнуто — эго-подпитка огня, выжженная душа.",
        },
        "uk": {
            "reversed": "Ревнощі, власництво, перегрівання самооцінки.",
            "love": "Прямо — яскраве, пристрасне й незалежне кохання. Перевернуто — ревнощі, его, вогонь, що спалює пару.",
            "career": "Прямо — енергія, харизма, лідерство, тепло до команди. Перевернуто — тиранія харизми, вигорання команди.",
            "health": "Прямо — життєвий тонус, яскравість, вогненна енергія. Перевернуто — перегрів, гнів, «пожежа» в тілі.",
            "spirituality": "Прямо — ясна воля, духовна пристрасть, зрілий вогонь. Перевернуто — его-підживлення вогню, випалена душа.",
        },
        "en": {
            "reversed": "Jealousy, possessiveness, overheated self-esteem.",
            "love": "Upright — bright, passionate, independent love. Reversed — jealousy, ego, fire burning the couple.",
            "career": "Upright — energy, charisma, leadership, warmth toward the team. Reversed — tyranny of charisma, team burnout.",
            "health": "Upright — vitality, brightness, fiery energy. Reversed — overheating, anger, a fire in the body.",
            "spirituality": "Upright — clear will, spiritual passion, mature fire. Reversed — ego feeding the fire, a scorched soul.",
        },
    },
    "Wands-14": {
        "ru": {
            "reversed": "Вспыльчивость кумира, догматизм, надломленный авторитет.",
            "love": "Прямо — щедрый и уверенный партнёр, тепло и покровительство любви. Перевёрнуто — властный покровитель, приказ вместо чувств.",
            "career": "Прямо — визионер, капитан, вдохновляющий лидер. Перевёрнуто — выгоревший лидер, команда под давлением.",
            "health": "Прямо — крепкая энергия, огонь как основа тонуса. Перевёрнуто — перегрев, давление, избыточные амбиции тела.",
            "spirituality": "Прямо — зрелое лидерство духа, щедрость огня. Перевёрнуто — тирания духа, гордыня вождя.",
        },
        "uk": {
            "reversed": "Запальність кумира, догматизм, надламаний авторитет.",
            "love": "Прямо — щедрий і впевнений партнер, тепло й заступництво любові. Перевернуто — владний покровитель, наказ замість почуттів.",
            "career": "Прямо — візіонер, капітан, надихаючий лідер. Перевернуто — вигорілий лідер, команда під тиском.",
            "health": "Прямо — міцна енергія, вогонь як основа тонусу. Перевернуто — перегрів, тиск, надмірні амбіції тіла.",
            "spirituality": "Прямо — зріле лідерство духу, щедрість вогню. Перевернуто — тиранія духу, гординя вождя.",
        },
        "en": {
            "reversed": "A fiery idol, dogmatism, a broken authority.",
            "love": "Upright — a generous, confident partner, warmth and protection of love. Reversed — a domineering patron, orders instead of feeling.",
            "career": "Upright — visionary, captain, inspiring leader. Reversed — a burned-out leader, team under pressure.",
            "health": "Upright — strong energy, fire as the basis of tone. Reversed — overheating, strain, excessive bodily ambition.",
            "spirituality": "Upright — mature spiritual leadership, generosity of fire. Reversed — tyranny of spirit, leader's pride.",
        },
    },
}